### ISSUE TITLE
LEDE（Linux Embedded Development Environment )软件仓库

### ISSUE THREAD

**Issue by tesroom** [ustclug/mirrorrequest#100]
**如何镜像**
使用 rsync://downloads.lede-project.org/downloads 以获取下载库的副本。

每12到24小时同步一次下载共享是理想的。 一旦镜子设置完毕，随时在 lede-adm@lists.lede-project.org上公布，以便可以在此页面上发布。

快照的数据量大约为35GB，我们预计每个版本的数据量增长30-40GB。 由于当前的带宽限制，我们请求在最初提取数据时使用类似rsync --bwlimit 8000的内容

=======================================================
LEDE（Linux Embedded Development Environment，Linux嵌入式开发环境）项目是一个基于OpenWrt的Linux操作系统。它完全可以替代广泛的网络设备和非网络设备中的原厂固件。 硬件列表（Table of Hardware） 列出了支持的设备。 前往 关于LEDE 以了解更多LEDE机构的信息。

**为何使用LEDE?**

LEDE相比制造商的原厂固件更加出色，才使得人们更倾向于使用LEDE。LEDE工作起来更加稳定、提供更多的功能，并且更加安全，同时具有良好的技术支持。

- 可扩展性： LEDE提供了许多以往只在高端设备上才提供的各种功能。它具有3000个以上的标准化应用软件包，您可以轻松地将他们应用于各种支持的设备，包括各种陈旧的路由器。 更多...
- 高安全性： 从安装开始，LEDE就以安全的标准来设计。例如Wi-Fi默认禁用，没有弱密码，没有任何后门程序。LEDE的系统组件始终保持最新，因此漏洞一旦被发现后会很快得到解决。 更多...
- 高性能、高稳定性 LEDE固件是由所支持的所有设备的标准化组件制作而成。这意味着每个组件都会接受更多的测试和bug修复，而不像原厂固件那样一旦为生产线的产品提供固件后就再也不去碰它。 更多...
- 强大的社区支持： LEDE团队成员会经常参与到LEDE论坛、LEDE开发者、LEDE管理员以及LEDE的IRC频道中去。您可以直接与开发人员，管理软件模块的志愿者和其他LEDE用户交流，大大增加您解决问题的机会。 更多...
- 研发： 许多团队使用LEDE作为他们对网络性能研究的平台。这意味着他们的成功实验案例将会首先在LEDE中实现，而原厂固件将会落后许多。更多...
- 开源/无额外支出： 使用LEDE没有任何金钱成本。它完全是由志愿者团队、开发者、维护人员、个人以及一些公司创建的。 如果您喜欢LEDE，可以考虑将它变得更好。作为开源社区的一部分，LEDE由强大的Linux Kernel驱动 获取源代码...。
- 以及更多… 不妨看看 使用LEDE的理由...

**Comment by knight42** [comment]
http://mirrors.ustc.edu.cn/lede/

每小时同步一次

**Comment by tesroom** [comment]
非常感谢哦

2017年3月1日 23:10，"Jian Zeng" <notifications@github.com>写道：
