### ISSUE TITLE
申请增加 packagist 镜像

### ISSUE THREAD

**Issue by icemanpro** [ustclug/mirrorrequest#101]
项目 https://packagist.org

Packagist 是 Composer 默认的 package repository。国内用 composer 安装包时，比较慢。

**Comment by gaoyifan** [comment]
https://github.com/hirak/packagist-crawler

**Comment by RobberPhex** [comment]
实际上，目前有一个还在维护中的packagist镜像 <https://packagist.phpcomposer.com/packages.json>。

但是这种镜像都有一个很严重的问题。
比如[apache/log4php](https://packagist.phpcomposer.com/p/apache/log4php%244773988716300ebe8a642fc87a1c892a197a5e506c19cfb170f23ecd5b78346c.json) 2.3.0版本的信息如下：
```json
{
  "name": "apache/log4php",
  "description": "A versatile logging framework for PHP",
  "keywords": [
    "log",
    "logging",
    "php"
  ],
  "homepage": "http://logging.apache.org/log4php/",
  "version": "2.3.0",
  "version_normalized": "2.3.0.0",
  "license": [
    "Apache-2.0"
  ],
  "authors": [],
  "source": {
    "type": "git",
    "url": "https://git-wip-us.apache.org/repos/asf/logging-log4php.git",
    "reference": "cac428b6f67d2035af39784da1d1a299ef42fcf2"
  },
  "dist": null,
  "type": "library",
  "time": "2012-10-26T09:13:25+00:00",
  "autoload": {
    "classmap": [
      "src/main/php/"
    ]
  },
  "require": {
    "php": ">=5.2.7"
  },
  "uid": 23288
}
```
composer在使用了镜像的情况下，还是从https://git-wip-us.apache.org/repos/asf/logging-log4php.git clone `cac428b6f67d2035af39784da1d1a299ef42fcf2`的代码。
**这甚至比从github上下载还慢！**

---

后来我自己有看packagist的镜像。可以对从github、bitbucket等下载的url做反向代理，对于上面说的这种，可以在镜像站点直接clone并压缩，提供给最终用户。当然，对于所有包的元信息，只能自己保存一份了。
可以看下我自己写的工具 [pkgist](https://github.com/RobberPhex/pkgist)。

**Comment by taoky** [comment]
前几天收到了请求加 Composer 2.0 的邮件，所以我搜索了一下有关的情况：

- [Packagist 文档](https://packagist.org/mirrors) 推荐使用 [Webysther/packagist-mirror](https://github.com/Webysther/packagist-mirror)，但是其只兼容 Composer 1。
- 根据 <https://github.com/tuna/issues/issues/1280#issuecomment-868384414>，Composer 2 API 需要镜像站提供动态内容，但是目前不会考虑在镜像站上运行这类程序。
- Packagist/Composer 镜像事实上只镜像了 index，实际包内容没有镜像。

因此从目前已知的信息来看，可能不会优先考虑做 packagist 的镜像。
