### ISSUE TITLE
希望可以 增加 Composer 镜像

### ISSUE THREAD

**Issue by imxieke** [ustclug/mirrorrequest#102]
官方源：https://packagist.org/
介    绍：Composer : PHP 包管理工具 类似 `npm pip`
原    因： 由于某种神秘力量 在大陆有很多国外网站在国内无法打开或者打开很慢，很不幸的的是Composer             也是其中之一 ， 之前国内有个镜像但是已经没人维护了 希望可以增加！
国内镜像：https://pkg.phpcomposer.com/

**Comment by zhsj** [comment]
dup #101
