### ISSUE TITLE
[New] 新支点 NewStart Linux 软件仓库和ISO镜像

### ISSUE THREAD

**Issue by Cassidy** [ustclug/mirrorrequest#104]
上游地址：
软件仓库：
http://mirrors.gd-linux.com/newstart/
rsync://mirrors.gd-linux.com/newstart/
ISO镜像：
http://mirrors.gd-linux.com/newstart-cd/
rsync://mirrors.gd-linux.com/newstart-cd/

项目介绍
中兴新支点桌面操作系统是国内基于 Linux 定制的发行版之一，支持 x86 ，龙芯，飞腾等CPU架构。

为什么希望添加该镜像
可能国内使用的人数比较多，官网软件仓库的网速有时会比较慢。
作为国内为数不多的操作系统发行版之一，推动了国内软硬件厂商的发展，希望大家能够顶起来。

**Comment by jiangyong123** [comment]
支持

**Comment by esileme** [comment]
期待

**Comment by zhsj** [comment]
Please answer the following question, otherwise we can't accept this request.
Where is the source rpm packages? Or how can I get the source of this OS?

**Comment by zhsj** [comment]
We will reopen this if we have strong belief that this software is an **Open Source** software.
