### ISSUE TITLE
申请添加kubernetes软件仓库

### ISSUE THREAD

**Issue by colachg** [ustclug/mirrorrequest#105]
* 上游地址：

    https://packages.cloud.google.com/apt/dists/kubernetes-xenial

* 项目介绍：

    [kubernetes](https://github.com/kubernetes/kubernetes)是google开源的容器管理和调度系统。

* 为什么：
    由于GFW,国内不科学上网是装不了这些方便的工具。该仓库中包含了快速搭建一套kubernetes系统的工具。
[详情](https://kubernetes.io/docs/getting-started-guides/kubeadm/)。

**Comment by knight42** [comment]
http://mirrors.ustc.edu.cn/kubernetes/apt/

**Comment by zhsj** [comment]
@knight42 rpm support?

**Comment by knight42** [comment]
@zhsj 有需求再说吧..

**Comment by zhsj** [comment]
redhat 为代表的 yum 用户群还是很大的嘛

**Comment by colachg** [comment]
@knight42 Thanks a lot.

**Comment by zhsj** [comment]
* [ ] apt
  * [ ] minikube
* [ ] yum
  * [ ] kubernetes
  * [ ] minikube

**Comment by colachg** [comment]
这是阿里云的yum源，要是有需求的可以先用用这个。
https://mirrors.aliyun.com/kubernetes/

**Comment by silenceshell** [comment]
@colachg 阿里云的yum源更新的不及时，官方已经到1.8.2了，阿里云还是停留在1.7.5。ustc的apt源倒是更新的比较及时，可惜就是没有yum源。

**Comment by zhuwenjie11** [comment]
请添加yum源，国内的kubernetes用户越来越多了

**Comment by muyiben** [comment]
请添加yum源

**Comment by wynn5a** [comment]
请添加yum源，谢谢啦。。。

**Comment by xianfengsong** [comment]
请添加yum源

**Comment by yotoobo** [comment]
同求yum源

**Comment by donilan** [comment]
请添加yum源

**Comment by vsxen** [comment]
阿里现在更新挺及时的 
https://mirrors.aliyun.com/kubernetes/
APIServer等可以用阿里acs团队的镜像  
registry.vpc.{region}.aliyuncs.com/acs/kube-apiserver-amd64
或者
aliyuncs.com/acs/kube-controller-manager-amd64

**Comment by Qizhd** [comment]
add yum for kubernetes

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/kubernetes/yum/ 同步完成啦。

**Comment by colachg** [comment]
刚收到邮件提示，时间过得真快啊，都四年了。

**Comment by waitingsong** [comment]
CentOS 8 可以使用 el7 的版本么

**Comment by taoky** [comment]
> CentOS 8 可以使用 el7 的版本么

我猜是可以的？上游只有 el7 的版本，[文档的安装手册](https://kubernetes.io/zh/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#%E5%AE%89%E8%A3%85-kubeadm-kubelet-%E5%92%8C-kubectl)也直接写了 el7。
