### ISSUE TITLE
建议增加manjaro的iso镜像

### ISSUE THREAD

**Issue by lulinux** [ustclug/mirrorrequest#108]
上游源（官方镜像）的地址：
https://downloads.sourceforge.net/manjarolinux/manjaro-xfce-17.0-stable-x86_64.iso
https://downloads.sourceforge.net/manjarolinux/manjaro-xfce-17.0-stable-i686.iso
https://downloads.sourceforge.net/manjarolinux/manjaro-kde-17.0-stable-x86_64.iso
https://downloads.sourceforge.net/manjarolinux/manjaro-kde-17.0-stable-i686.iso
https://downloads.sourceforge.net/manjarolinux/manjaro-gnome-17.0-stable-x86_64.iso
https://downloads.sourceforge.net/manjarolinux/manjaro-gnome-17.0-stable-i686.iso
可参考https://mirrors.tuna.tsinghua.edu.cn/manjaro-cd/release/17.0/gnome/manjaro-gnome-17.0-stable-x86_64.iso的方式放置文件，谢谢

该项目的介绍：
Manjaro Linux是快速的、用户友好的、面向桌面的、基于Arch Linux的操作系统。它的一些显著特性包括：一份直观的安装程序、自动硬件检测、稳定的滚动式发布模式、对安装多个内核的支持、用于管理图形卡的特别Bash脚本、高度的桌面可配置性。Manjaro Linux提供Xfce桌面作为核心选项，并为高级用户提供一份最小主义的Net版本。用户还可以获得社区支持的GNOME 3/Cinnamon及KDE版本。Manjaro的社区论坛可提供帮助并充满活力，用户受益其中。 

为什么希望添加该镜像：
manjaro在distrowatch上排名迅速上升，大量普通用户需要一个好安装的archlinux衍生版。

**Comment by wck963** [comment]
TUNA就有，而且个人觉得发行版iso相对于软件源冗余的需求小很多了。。

**Comment by zzh1996** [comment]
@gaoyifan https://github.com/ustclug/mirrorrequest/issues/45 这里已经有 10 个 upvote 了

**Comment by gaoyifan** [comment]
备忘。 rsync://mirrorservice.org/downloads.sourceforge.net/m/ma/manjarolinux/

**Comment by gaoyifan** [comment]
同步完成，欢迎使用：http://mirrors.ustc.edu.cn/manjaro-cd/

**Comment by volltin** [comment]
已经添加到主页（ https://mirrors.ustc.edu.cn ）“获取安装镜像”中。
