### ISSUE TITLE
建议增加nodesource的镜像

### ISSUE THREAD

**Issue by 1354092549** [ustclug/mirrorrequest#109]
建议增加nodesource的镜像（参考：https://github.com/nodesource/distributions ）

**Comment by Blealtan** [comment]
提供的链接404了。

**Comment by 1354092549** [comment]
@Blealtan 可以访问啊

**Comment by littlehz** [comment]
建议增加 nodesource 镜像

**Comment by gaoyifan** [comment]
http://mirrors.ustc.edu.cn/nodesource
