### ISSUE TITLE
Error in docker.mirrors.ustc.edu.cn

### ISSUE THREAD

**Issue by Nesty92** [ustclug/mirrorrequest#111]
I'm using this mirror but i have the following error when pull images

Look the output of this docker request url

https://docker.mirrors.ustc.edu.cn/v2/library/nginx/manifests/latest

errors	
0	
code	"MANIFEST_UNKNOWN"
message	"manifest unknown"
detail	
Op	"Get"
URL	"https://registry-1.docker.io/v2/"
Err	
Op	"dial"
Net	"tcp"
Source	
Addr	
Err	
Err	"read udp 127.0.0.1:53295->127.0.0.11:53: read: connection refused"
Name	"registry-1.docker.io"
Server	"127.0.0.11:53"
IsTimeout	false
IsTemporary	false

**Comment by zhsj** [comment]
Can you try again? I notice there's some network issue and the docker mirror has been restarted automatically.

**Comment by Nesty92** [comment]
i trying again, now is working but only for some images, when i try to pull aarch64/alpine obtains the same error

https://docker.mirrors.ustc.edu.cn/v2/aarch64/alpine/manifests/latest

sorry for my english is not very good.

**Comment by gaoyifan** [comment]
fixed

```
$ docker pull docker.mirrors.ustc.edu.cn/aarch64/alpine
Using default tag: latest
latest: Pulling from aarch64/alpine
e92c575fea6b: Pull complete
Digest: sha256:fea6984b3a5b422c41f20a95ff290e77405dd3cb4ff163dd3ad64572e41de0cf
Status: Downloaded newer image for docker.mirrors.ustc.edu.cn/aarch64/alpine:latest
```
