### ISSUE TITLE
建议增加 Jenkins 软件和插件镜像

### ISSUE THREAD

**Issue by stanzgy** [ustclug/mirrorrequest#112]
上游源（官方镜像）的地址
https://pkg.jenkins.io/

该项目的介绍
Jenkins 是目前广泛使用的 CI/CD 开源软件，官方源提供了 debian opensuse redhat 安装包

为什么希望添加该镜像
这个官方源从国内的下载速度比较慢，希望 ustc mirror 能提供国内镜像加速，谢谢

**Comment by zhsj** [comment]
upstream: rsync://rsync.osuosl.org/jenkins/

**Comment by gaoyifan** [comment]
size 82G

**Comment by gaoyifan** [comment]
http://mirrors.ustc.edu.cn/jenkins/
