### ISSUE TITLE
建议增加chromium镜像

### ISSUE THREAD

**Issue by 0ct0cat** [ustclug/mirrorrequest#113]
上游源（官方镜像）的地址
https://chromium.googlesource.com/

该项目的介绍
包含了chromium, webrtc等项目。webrtc项目是目前p2p通信比较热门的研究项目。

为什么希望添加该镜像
这个官方源从国内的下载速度比较慢。

**Comment by cheese** [comment]
git config --global url.https://beijing.source.codeaurora.org/quic/lc.insteadOf https://chromium.googlesource.com

**Comment by fawdlstty** [comment]
thank for @terasum and @cheese , I found type to download chromium source:

```cmd
git config --global url.https://source.codeaurora.org/quic/lc.insteadOf https://chromium.googlesource.com
git clone --progress -v --depth 1 "https://chromium.googlesource.com/chromium.git" -b "chromium.org/trunk" "E:\chromium"
```

**Comment by fawdlstty** [comment]
After testing, this is quite different from the original image, and many steps need to be modified to achieve the following operation.Using depot_tools, for example, is still blocked.If you can, add the original image and suggest alternatives to using the depot_tools tool

**Comment by taoky** [comment]
https://github.com/tuna/issues/issues/138#issuecomment-502491547

**Comment by fawdlstty** [comment]
这个保留open状态比较好。上面这位说的有道理，但很显然一个脚本能搞定，不能因为还没这样的脚本，就认为同步chromium镜像无用

**Comment by fawdlstty** [comment]
或者换种思路，不用脚本，用host

**Comment by taoky** [comment]
> 或者换种思路，不用脚本，用host

首先我们对 Chromium 的代码都不熟悉，并且在 mirrorrequest 已经积压了大量请求的情况下，恐怕没有足够的精力出来写可靠的同步脚本。

如果「用 host」指的是使用反代的话，目前我们对反向代理的添加非常谨慎，很可能不会考虑。

如果能有可靠完整的同步方式的话，大家应该都会很乐意去同步的。但是从 TUNA 那里的讨论来看的话，很困难。

**Comment by fawdlstty** [comment]
chromium镜像鸽十年也没关系呀，不过保留其中一个chromium镜像issue的open状态，有利于了解这方面技能的人对其提供更好的建议

**Comment by taoky** [comment]
> chromium镜像鸽十年也没关系呀，不过保留其中一个chromium镜像issue的open状态，有利于了解这方面技能的人对其提供更好的建议

嗯，也可以 :)

**Comment by jingjingxyk** [comment]
> 跌跌撞撞的，过了很久，鄙人终于能把它同步下来，并且编译出了linux版chromium 


现在我把过程写到这里了

1.  [通过代理服务器快速下载chromium源码](https://www.cnblogs.com/jingjingxyk/p/16575572.html)
2.  [快速下载webRTC源码](https://www.cnblogs.com/jingjingxyk/p/16575388.html)
3.  [nginx TLSv1.3配置](https://www.cnblogs.com/jingjingxyk/p/16576333.html)
4. 代理服务器用的是 nginx，用了这个模块[ngx_http_proxy_connect_module](https://github.com/chobits/ngx_http_proxy_connect_module.git)
5.  服务是用爱发电

```conf
# nginx 服务器只允许特定地址访问
map $host $tls_proxy_allow_url_flag {
     default 0;
     ~^([\w|-]+?)\.googlesource\.com$ 1;
     ~^([\w|-]+?)\.googleapis\.com$ 1;
     ~^chrome-infra-packages\.appspot\.com$ 1;
}

```
