### ISSUE TITLE
建议增加 hackage 镜像

### ISSUE THREAD

**Issue by knight42** [ustclug/mirrorrequest#115]
脚本方式参考：https://github.com/tuna/tunasync-scripts/blob/master/hackage.sh

**Comment by VonFry** [comment]
+1

**Comment by bojieli** [comment]
+1

目前国内应该只有 TUNA 有 hackage 镜像，hackage 国外源站虽然可以访问但一些运营商网络访问速度很慢，希望 USTC 做个 hackage 镜像。

如果初始同步比较慢，可以用 ipv6 反代 TUNA 的 hackage 镜像。

初始同步方法：
```lftp -e "mirror -c --parallel=10 http://hackage.haskell.org/packages"```

更新方法：
```http://bitcheese.net/wiki/howto/setup-hackage-mirror```

**Comment by gloit042** [comment]
我也+1

**Comment by bojieli** [comment]
补充一下，TUNA 的自己写的 hackage 和 stackage 同步脚本似乎更好（stackage 是 hackage 的 stable snapshot）

```
https://github.com/tuna/tunasync-scripts/blob/master/hackage.sh
https://github.com/tuna/tunasync-scripts/blob/master/stackage.py
```

使用帮助：

```
https://github.com/tuna/mirror-web/blob/master/_posts/help/1970-01-01-hackage.md
https://github.com/tuna/mirror-web/blob/master/_posts/help/1970-01-01-stackage.md
```

**Comment by gaoyifan** [comment]
初始同步：`rsync mirrors.tuna.tsinghua.edu.cn::hackage`

**Comment by gloit042** [comment]
已完成
http://mirrors.ustc.edu.cn/hackage/
