### ISSUE TITLE
希望能同步一下Wine官方源，国内下载速度奇慢

### ISSUE THREAD

**Issue by feihong-gz** [ustclug/mirrorrequest#117]
deb源地址 https://dl.winehq.org/wine-builds/debian/

**Comment by 1354092549** [comment]
+1

**Comment by abcfy2** [comment]
+1 希望镜像wine，不过暂时没找到wine-builds的同步方式，似乎只能爬取http链接

**Comment by 1354092549** [comment]
懒得处理就丢个反代，然后加个缓冲吧

**Comment by wangqr** [comment]
WineHQ提供FTP方式，其中的 ftp://ftp.winehq.org/pub/ 等价于 https://dl.winehq.org/

**Comment by gaoyifan** [comment]
@wangqr  感谢~  近期我来尝试同步一下。

**Comment by gaoyifan** [comment]
已同步完成：http://mirrors.ustc.edu.cn/wine/ 
欢迎反馈~

**Comment by zhsj** [comment]
wine-builds 从 ftp://ftp.winehq.org/pub 中消失了

**Comment by abcfy2** [comment]
似乎官方停掉了ftp服务，只能从https://dl.winehq.org/访问了

**Comment by TonySue2000** [comment]
再在此挖坟，请求加上wine-builds的mirror，不然下这个实在太慢

**Comment by WangYneos** [comment]
挖坟，同求wine-builds的mirror

**Comment by jzengc** [comment]
@zhsj 一定要 ftp 吗，还是还有其他可能选项？

**Comment by zhsj** [comment]
> @zhsj 一定要 ftp 吗，还是还有其他可能选项？

可以提供其他的同步方式，然后现在的管理员会评估可行性，并修改配置。

**Comment by ihipop** [comment]
> > @zhsj 一定要 ftp 吗，还是还有其他可能选项？
> 
> 可以提供其他的同步方式，然后现在的管理员会评估可行性，并修改配置。

https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Debian_10/

这个OBS支持mirror 见 https://forum.winehq.org/viewtopic.php?f=8&t=32192

**Comment by cxwx** [comment]
+1

**Comment by jzengc** [comment]
我问了 WineHQ 的运维，他说关掉 ftp 是主要因为大约一年前有大量爬虫从 ftp 爬东西占用了 WineHQ 的很多带宽，直接影响了其他基础设施的运行。如果还需要做镜像，目前只能从 HTTPS 同步（`wget --mirror`？）。

另外，目前 https://dl.winehq.org/wine-builds/ 已经加了 CDN，不知道对国内的用户下载速度有没有改善？

**Comment by abcfy2** [comment]
dl.winehq.org早就用了CDN了，用的是fastly.net，这玩意在国内会定向到日本东京节点，非常慢，基本上日本的CDN节点都被和谐完了，s3也一样，github的release用的是S3，国内定向到日本节点，一样各种无法下载，改hosts改成美国西海岸节点才会好很多

**Comment by gdlwolf** [comment]
@gaoyifan 可以添加下wine ubuntu的源吗？https://dl.winehq.org/wine-builds/ubuntu/    非常感谢了

**Comment by skyzh** [comment]
> 用[https://download.opensuse.org也很慢，求添加源，感谢](https://download.opensuse.org%E4%B9%9F%E5%BE%88%E6%85%A2%EF%BC%8C%E6%B1%82%E6%B7%BB%E5%8A%A0%E6%BA%90%EF%BC%8C%E6%84%9F%E8%B0%A2)

OpenSUSE 镜像国内到处都有

**Comment by taoky** [comment]
最近也收到了有关 wine-builds 的请求的邮件，等期末季结束之后（七月）我准备测试一下用 rclone sync 同步 wine-builds（android, macosx 和 mageia 目录排除同步），看一下能不能同步成功。

**Comment by taoky** [comment]
> 最近也收到了有关 wine-builds 的请求的邮件，等期末季结束之后（七月）我准备测试一下用 rclone sync 同步 wine-builds（android, macosx 和 mageia 目录排除同步），看一下能不能同步成功。

我今天测试了一下 rclone 和 lftp 用 HTTP 同步 wine-builds，发现用这两个工具无法同步 wine-builds 的文件。

lftp 使用 `mirror` 命令无法同步任何文件：

```
lftp -c 'set cmd:fail-exit true;open https://dl.winehq.org/wine-builds/;lcd /local/path/to/wine-builds/;mirror --verbose=3 -aec ./'
```

rclone 同步软件包会出现 503 错误：

```
sudo docker run --network=host --rm -e DEBUG=true -e RCLONE_CONFIG_REMOTE_TYPE=http -e RCLONE_CONFIG_REMOTE_URL=https://dl.winehq.org/ -e RCLONE_PATH=/wine-builds/ -e RCLONE_EXTRA="--exclude android/** --exclude macosx/** --exclude mageia/**" -e RCLONE_TRANSFERS=1 -e RCLONE_CHECKERS=4 -v /local/path/to/wine-builds:/data/ ustcmirror/rclone:latest
```

```
2022/07/12 19:55:59 DEBUG : fedora/35/i686/wine-devel-7.5-1.1.i686.rpm: skipping because of error: failed to stat: HTTP Error 503: 503 Service Unavailable
2022/07/12 19:56:01 DEBUG : fedora/34/i686/wine-devel-7.0.rc1-1.1.i686.rpm: skipping because of error: failed to stat: HTTP Error 503: 503 Service Unavailable
```

目前的测试结果表明，如果需要同步 wine-builds，要么让上游提供更方便的方式，要么采取类似 [docker-ce 同步](https://github.com/ustclug/ustcmirror-images/tree/master/docker-ce)的方案，手写相关的同步脚本。

**Comment by abcfy2** [comment]
本地实测了下，`apt-mirror`可以同步成功，还需要稍微调教下

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/wine-builds/

包含 Debian, Ubuntu 与 Fedora 的包。
