### ISSUE TITLE
建议增加 Anaconda 免费软件仓库

### ISSUE THREAD

**Issue by Blealtan** [ustclug/mirrorrequest#119]
上游源地址：https://repo.continuum.io/pkgs/free
项目介绍：Anaconda 是一个用于科学计算的 Python 发行版，支持 Linux, Mac, Windows, 包含了众多流行的科学计算、数据分析的 Python 包。它有着可以和 PyPI 协作的独立包管理系统 `conda`，可以通过不同于 PyPI 的源进行许多 Python 包的安装。
建议原因：在国内链接官方源速度较慢，清华大学的 tuna 源在部分网络下速度也不甚理想。

**Comment by knight42** [comment]
http://mirrors.ustc.edu.cn/anaconda/pkgs/free/

如果不麻烦的话，可以向 https://github.com/ustclug/mirrorhelp 提 PR 来协助我们完善帮助文档
