### ISSUE TITLE
能否建立一个bioconda的国内镜像

### ISSUE THREAD

**Issue by zd200572** [ustclug/mirrorrequest#125]
bioconda是conda上一个分发生物信息软件的频道，现在已经有超过2700款软件。由于国内没有基镜像，下载安装生物信息软件速度十分缓慢，经常中断，生物信息人迫切需要一个国内镜像。Bioconda is a channel for the conda package manager specializing in bioinformatics software。

**Comment by zd200572** [comment]
http://bioconda.github.io/

**Comment by gaoyifan** [comment]
我没有找到可靠的同步方法。
希望能由bioconda用户想办法找寻一个同步方案。

**Comment by zd200572** [comment]
我邮件联系了bioconda的Johannes Köster，他的回复是可以先找到一个中国的anaconda源(我知道清华镜像站有一个这个源)。 他建议联系support@anaconda.org。这样同步的问题可以解决了吗？
附上邮件内容:

 So, technically, all bioconda packages are uploaded to the corresponding bioconda channel on anaconda.org, which is hosted by Continuum Analytics. To really solve your problem, you would need a China-accessible mirror of not only the bioconda channel but also the conda-forge channel and the default anaconda channel, because bioconda packages depend on packages from these channels and won't work without. As all three are hosted by Continuum Analytics, I would suggest to approach them via support@anaconda.org and ask about the issue. They are usually very open to academic collaborations, and they for sure will have an interest to make conda accessible in China.

**Comment by gaoyifan** [comment]
备忘：TUNA的脚本 https://github.com/tuna/tunasync-scripts/blob/master/anaconda.sh

**Comment by knight42** [comment]
@gaoyifan 我们已经有 anaconda 这个源了， http://mirrors.ustc.edu.cn/anaconda/

**Comment by gaoyifan** [comment]
@knight42  我们目前是怎么同步的呢？（由于yuki跪了, 没查到）方便添加第三方的channel吗？

**Comment by knight42** [comment]
@gaoyifan 目前是通过 lftp 同步的。我不是 anaconda用户，不知道怎么添加第三方 channel

**Comment by gaoyifan** [comment]
@knight42 
https://conda.anaconda.org/bioconda/linux-64
https://conda.anaconda.org/bioconda/osx-64

P.S. 列目录比较慢

**Comment by zd200572** [comment]
可以使用这个工具来同步镜像：https://github.com/maxpoint/conda-mirror

Example:

conda-mirror --upstream-channel bioconda --target-directory <local_mirror> --platform linux-64


https://github.com/bioconda/bioconda-recipes

**Comment by zd200572** [comment]
有同学在清华源上呐喊了一下，已经搞定了嘛！
https://github.com/tuna/issues/issues/112

有一台服务器硬盘快满了，因此只在另一台上镜像了 bioconda
https://nanomirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/

**Comment by shexuan** [comment]
@zd200572  https://nanomirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/这个地址是错误的  刚刚看了下，还是跟原来的在一起 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64/

**Comment by taoky** [comment]
bioconda 的动态缓存已经上线。
