### ISSUE TITLE
可否添加clojars语言库的repo

### ISSUE THREAD

**Issue by wsrhp** [ustclug/mirrorrequest#127]
项目名称与简介(Project Intro.)

clojure语言库的repo

上游地址与镜像方法(How to Mirror)

https://clojars.org/
https://github.com/clojars/clojars-web/wiki/Data

其他信息(Other)

镜像大小(Mirror Size):
未知

**Comment by jiacai2050** [comment]
clojars 偶尔会抽风被 block，希望能加上这个

**Comment by gaoyifan** [comment]
同步完成，欢迎使用： http://mirrors.ustc.edu.cn/clojars/

**Comment by jiacai2050** [comment]
同步周期是多少？是每天同步一次嘛？

**Comment by gaoyifan** [comment]
@jiacai2050  是的，每天7:47同步。

**Comment by chanshunli** [comment]
@gaoyifan 👍 👍 👍

**Comment by jiacai2050** [comment]
使用方式可参考：https://github.com/clojars/clojars-web/wiki/Mirrors
