### ISSUE TITLE
[new] alpine linux mirror

### ISSUE THREAD

**Issue by yaroot** [ustclug/mirrorrequest#13]
- rsync://rsync.alpinelinux.org/alpine/ 
- from its website [Alpine Linux is a security-oriented, lightweight Linux distribution based on musl libc and busybox.]
- light-weight, hardened kernel (Grsecurity), stable or rolling release 主要流行在防火墙/网关等偏服务类用途, 可以无盘或安装使用, 包数量增加很快, 因为体积比较小, 作为docker base image有一定用户量

**Comment by dereknex** [comment]
+1

**Comment by lianghyv** [comment]
+1

**Comment by yaroot** [comment]
Just an FYI, docker official images are moving to Alpine ([source](https://www.brianchristner.io/docker-is-moving-to-alpine-linux/)).

**Comment by zhsj** [comment]
Approved.
http://mirrors.ustc.edu.cn/alpine/

**Comment by zhsj** [comment]
Call for help to write the HELP for Alpine Linux at https://github.com/ustclug/mirrorhelp
