### ISSUE TITLE
sbt-plugin-releases 反向代理 or 镜像

### ISSUE THREAD

**Issue by sadhen** [ustclug/mirrorrequest#132]
+ 上游源：https://dl.bintray.com/sbt/sbt-plugin-releases
+ 项目介绍：

sbt 是 Scala 的构建工具，因为“网络”的缘故这个工具饱受诟病，也阻碍了很多Scala初学者的学习之路。

sbt 1.0 发布之后，对于Scala/Java工程的一般依赖，下载的速度有了大幅提升（国内可以使用aliyun的maven仓库）。但目前sbt 的插件是host在bintray的，插件的下载速度实在太慢。

所以，请求添加 https://dl.bintray.com/sbt/sbt-plugin-releases/  的反向代理。

+ 目前的使用方法:
在 `~/.sbt/repositories` 添加
```
[repositories]
  community-plugins-ivy-releases: https://dl.bintray.com/sbt/sbt-plugin-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

**Comment by armnotstrong** [comment]
原来sbt ivy库已经有人提了啊, 太好了

希望能将整个http://dl.bintray.com/typesafe/ivy-releases/ 镜像下来,国内太球慢了, 另外好像sbt每次build的时候都要重新更新sbt, 到国外太慢了

scala 语言用来搞spark做数据计算需求还挺大的

**Comment by sadhen** [comment]
@armnotstrong 

Hi，师兄，就体积而言，这个镜像和mirrors上面其它镜像比，算是很小的了。

community的那个做镜像应该是没有问题的，typesafe那个可能需要联系一下官方。

我这边尝试用 lftp 做镜像，未果，正在写一个sbt插件来做这件事。

**Comment by sadhen** [comment]
Aborted, @sbt 1.0 is aweome enough for artifect fetching.

and https://github.com/lihaoyi/mill is here, do not hesitate to test it.
