### ISSUE TITLE
pip 不能自动选择正确的软件版本

### ISSUE THREAD

**Issue by Smart-Hypercube** [ustclug/mirrorrequest#133]
你好:

我在使用贵站的镜像网站时, 发现 pip 不能只懂选择正确的 IPython 版本.  

下面是出错信息, 同时我在SO上提了个问题 https://stackoverflow.com/questions/45996547/install-ipython-from-pypi-mirrors-with-pip.
@Matt 给出了线索, 如果您感兴趣, 可以处理下

[root@localhost ~]# cat ~/.pip/pip.conf
[global]
index-url = https://mirrors.ustc.edu.cn/pypi/web/simple
format = columns
[root@localhost ~]# pip --version
pip 9.0.1 from /usr/lib/python2.7/site-packages (python 2.7)
[root@localhost ~]# python --version
Python 2.7.5
[root@localhost ~]# pip install ipython
Collecting ipython
  Using cached https://mirrors.ustc.edu.cn/pypi/web/packages/79/63/b671fc2bf0051739e87a7478a207bbeb45cfae3c328d38ccdd063d9e0074/ipython-6.1.0.tar.gz
    Complete output from command python setup.py egg_info:

    IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2.
    When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
    Beginning with IPython 6.0, Python 3.3 and above is required.

    See IPython `README.rst` file for more information:

        https://github.com/ipython/ipython/blob/master/README.rst

    Python sys.version_info(major=2, minor=7, micro=5, releaselevel='final', serial=0) detected.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-amothg/ipython/

谢谢

**Comment by zzh1996** [comment]
对，这个很坑，我用别人的 dockerfile，前面加上使用科大源，中间的安装步骤就可能会报错。把 pip 包的版本写死就好了。。。这还导致了我以前一直以为一些 pip 包只支持 python2 或者 python3，而实际上是都支持的。

**Comment by zzh1996** [comment]
https://github.com/tuna/issues/issues/341

**Comment by zhsj** [comment]
Bug report on pip https://github.com/pypa/pip/issues/5967

**Comment by zzh1996** [comment]
现在我们重定向到 tuna 源，tuna 源已经解决这个问题
