### ISSUE TITLE
gravatar反代已挂

### ISSUE THREAD

**Issue by leo108** [ustclug/mirrorrequest#134]
test link: https://gravatar.proxy.ustclug.org/avatar/60eb307c5a5be00af65e36616fd2c6d9
source link https://secure.gravatar.com/avatar/60eb307c5a5be00af65e36616fd2c6d9

**Comment by zhsj** [comment]
Removed according to regulations.

**Comment by gaoyifan** [comment]
从mirrors首页删掉吧，误导群众啊
