### ISSUE TITLE
希望添加nginx官方源的镜像，里面有最新版的nginx

### ISSUE THREAD

**Issue by zwl1619** [ustclug/mirrorrequest#137]
官方仓库：
http://nginx.org/packages/

理由是nginx最新的主线版本在里面都能找到。

**Comment by zhz** [comment]
nginx 现在使用频率很高，确实需要一个 nginx 的国内镜像

**Comment by gaoyifan** [comment]
欢迎使用~  http://mirrors.ustc.edu.cn/nginx/
