### ISSUE TITLE
希望增加 hackage 镜像

### ISSUE THREAD

**Issue by bojieli** [ustclug/mirrorrequest#139]
目前国内应该只有 TUNA 有 hackage 镜像，hackage 国外源站虽然可以访问但一些运营商网络访问速度很慢，希望 USTC 做个 hackage 镜像。

如果初始同步比较慢，可以用 ipv6 反代 TUNA 的 hackage 镜像。

初始同步方法：
```
lftp -e "mirror -c --parallel=10 http://hackage.haskell.org/packages"
```

更新方法：
```
http://bitcheese.net/wiki/howto/setup-hackage-mirror
```

**Comment by gloit042** [comment]
Duplicate of #115
