### ISSUE TITLE
能否添加remi的源

### ISSUE THREAD

**Issue by zwl1619** [ustclug/mirrorrequest#140]
官方仓库：
http://rpms.remirepo.net/

理由：
有最新版的php，官方网站上列出了中国镜像，是清华大学的镜像https://mirrors.tuna.tsinghua.edu.cn/remi/ ，但是有时清华大学的镜像不能访问，比如现在发帖时就不能访问，所以申请添加。

**Comment by gaoyifan** [comment]
rsync://rpms.remirepo.net

**Comment by gaoyifan** [comment]
done
http://mirrors.ustc.edu.cn/remi/
