### ISSUE TITLE
申请添加AUR（Arch User Repository）源

### ISSUE THREAD

**Issue by Aitkots** [ustclug/mirrorrequest#141]
官方仓库：
https://aur.archlinux.org/

理由：
目前国内好用而快速的AUR源只有清华镜像做的不错，但因为地域原因（也可能是线路原因）清华源的访问速度不是很理想。而且AUR包含了很多有用的开源软件，给Arch的使用带来了极大的便利。说AUR是世界最大的软件仓库也不为过，希望官方能够增加对AUR源的支持 ：）

**Comment by hosiet** [comment]
Duplicate with #41.
