### ISSUE TITLE
能否添加ansible的镜像

### ISSUE THREAD

**Issue by zwl1619** [ustclug/mirrorrequest#142]
官方仓库地址：
http://releases.ansible.com/ansible/

添加理由：
官方的ansible仓库，有时断线，国内主要的镜像貌似都没有这个仓库，访问不方便，所以申请添加，以方便访问。

**Comment by zhsj** [comment]
我觉得意义不大，ansible可以通过pypi安装，而我们镜像了pypi。而且一般都是直接从github clone最新git版使用的，而github没有被墙。
