### ISSUE TITLE
建议增加 stackage 镜像

### ISSUE THREAD

**Issue by be5invis** [ustclug/mirrorrequest#143]
**注意：这不是 Hackage**
Stackage 是另一个（更稳定的）用于 Haskell 的软件包管理体系
同步脚本参考：https://github.com/tuna/tunasync-scripts/blob/master/stackage.py

**Comment by bojieli** [comment]
+1

**Comment by bojieli** [comment]
两个 Haskell 官方网站都推荐 Stack（取代 Cabel）作为 Haskell 的 build tool 和 package manager。

- https://www.haskell.org/downloads
- https://haskell-lang.org/

**Comment by bojieli** [comment]
Thanks @gloit042

**Comment by gloit042** [comment]
同步完成
https://mirrors.ustc.edu.cn/stackage/

**Comment by gloit042** [comment]
使用说明: http://mirrors.ustc.edu.cn/help/stackage.html
