### ISSUE TITLE
希望增加brew 镜像

### ISSUE THREAD

**Issue by zzvv** [ustclug/mirrorrequest#15]

**Comment by zhsj** [comment]
不知道你说的 brew 是否指 homebrew

我们已经有 homebrew 的镜像，使用帮助见 https://lug.ustc.edu.cn/wiki/mirrors/help/homebrew.git

**Comment by zzvv** [comment]
@zhsj 找到了.但是感觉和连墙外一样很慢.都是DNS污染惹的祸啊..诶~

顺带问下,你们的wiki 是开源程序搭建的吗?

**Comment by zhsj** [comment]
wiki 是 [dokuwiki](https://www.dokuwiki.org).

**Comment by zzvv** [comment]
对了,我看到有docker源,点过去是错误页面

**Comment by zhsj** [comment]
因为确实没有对应的 wiki 的页面。

另外，请不要在这里讨论与主题 **无关** 的事情。

**Comment by gaoyifan** [comment]
@zzvv 新增Homebrew Bottles源（二进制代码包）

**Comment by zzvv** [comment]
已用起~ 速度飞起!
