### ISSUE TITLE
申请(重新)添加 Rust 编译器 镜像

### ISSUE THREAD

**Issue by ZeroAurora** [ustclug/mirrorrequest#153]
在 Rust 中文 Wiki 中写到，中科大开源镜像站[提供了 Rust 编译器的镜像](https://wiki.rust-china.org/%E5%9B%BD%E5%86%85%E9%95%9C%E5%83%8F#rust-编译器)，但是实际访问时，返回404。

所以我希望知道，这是已经不再维护了，还是临时停止维护？如果可以，我希望可以重新启用，因为在国内不论是执行 `curl https://sh.rustup.rs/ -sSf | sh` 还是直接下载安装都是**非常非常困难**

如果可以，能否将 rustup 脚本 也进行镜像以方便使用？

**Comment by zhsj** [comment]
可以访问 https://mirrors.ustc.edu.cn/rust-static/

**Comment by ZeroAurora** [comment]
Reply @zhsj :抱歉，在看文档时看错了。。
后一个问题可否解答？谢谢

**Comment by zhsj** [comment]
你可以从 https://github.com/rust-lang-nursery/rustup.rs/blob/master/rustup-init.sh 这里下载 rustup 脚本。

**Comment by zhsj** [comment]
https://cdn.jsdelivr.net/gh/rust-lang-nursery/rustup.rs/rustup-init.sh 也可以，有国内节点。

**Comment by ZeroAurora** [comment]
Reply@zhsj :好的，明白了。抱歉提了一个无用问题。
