### ISSUE TITLE
建议增加IUS源

### ISSUE THREAD

**Issue by shalk** [ustclug/mirrorrequest#155]
**上游源（官方镜像）的地址**：

IUS Community Project  https://ius.io/

**该项目的介绍**：

> IUS is a community project that provides RPM packages for newer versions of select software for Enterprise Linux distributions.
> 
> Project Goals
> Create high quality RPM packages for Red Hat Enterprise Linux (RHEL) and CentOS.
> Promptly release updated RPM packages once new versions are released by the upstream developers.
> No automatic replacement of stock RPM packages.

> IUS是一个社区项目， 提供较新版本的软件用于企业级Linux发行版。
> 
> 项目目标
> - 为RHEL和Centos创建高质量的RPM包
> - 一旦上游开发者发布了新版本，快速发布更新了的RPM包。
> - 不会自动替换已经存在RPM包
> 

**为什么希望添加该镜像**

IUS为Centos提供很多新版本的软件，例如git ngin php 等，稳定的新版本。

**同步建议**

可以参考https://ius.io/Mirrors/

希望能考虑～

**Comment by gaoyifan** [comment]
补充：
rsync://dl.iuscommunity.org/ius
193.7GB

**Comment by gaoyifan** [comment]
同步完成，欢迎使用：http://mirrors.ustc.edu.cn/ius/
P.S. 由于archive体积巨大（存放了所有历史版本），但使用频率很低，目前没有同步这个目录。
