### ISSUE TITLE
建议添加PacBSD的镜像源

### ISSUE THREAD

**Issue by KnightBlood** [ustclug/mirrorrequest#156]
这是一个基于FreeBSD使用Pacman包管理的项目
这个项目与Archlinux非常相似
一下是官方原话：
 You've reached the website for PacBSD, a lightweight and flexible BSD® distribution that provides a base system for use of Pacman package manager.

Our packages match closely to ArchLinux packaging standards where possible. We Currently have official packages optimized for the x86_64 architectures.
此为官网:https://www.pacbsd.org/

官网目前只有这两个镜像源：
## Germany
Server = https://mirror-frankfurt.pacbsd.org/$repo/os/$arch

## United States
Server = https://packages.pacbsd.org/$repo/os/$arch

在中国使用非常缓慢

我认为这是一个非常有前途的项目

**Comment by gaoyifan** [comment]
补充：
rsync://packages.pacbsd.org/packages
12.8GB
