### ISSUE TITLE
建议在“获取发行版映像“中添加fedora的iso

### ISSUE THREAD

**Issue by sirius1242** [ustclug/mirrorrequest#159]
我认为fedora是一个很好的发行版，原先”获取发行版映像中有fedora的iso，但现在没有了。希望能够添加回去，毕竟在目录里找iso是一件较麻烦的事情，而且也对新手不友好。

**Comment by zhsj** [comment]
bug in Fedora iso path https://git.ustclug.org/mirrors/mirrors-index/blob/d0bd775754026994bac63055eff0461d3427c5a5/genisolist.ini#L165-167

**Comment by gloit042** [comment]
已修复
