### ISSUE TITLE
希望能增加 https://crates.io 的镜像

### ISSUE THREAD

**Issue by tennix** [ustclug/mirrorrequest#16]
[Rust](https://www.rust-lang.org) 语言的包仓库 https://crates.io 都是放在 AWS S3 上面，国内 Rust 语言爱好者通过其包管理工具 [cargo](https://github.com/rust-lang/cargo) 构建 Rust 项目时不用代理基本没法下载依赖。

不过由于 https://crates.io 是一个动态网站，直接镜像比较困难，我写了两个工具基本可以解决这个问题， [crates-mirror](https://github.com/tennix/crates-mirror) 用来同步官方所有的包，服务器端只需要静态托管这些压缩包就可以了，然后用户利用 [cargo-mirror](https://github.com/tennix/cargo-mirror) 就可以愉快地通过镜像下载依赖了。

USTC 的镜像源一直比较稳定，速度也很快，Linux 上我都是把 USTC 镜像设为第一个，希望 USTC 开源镜像站也能提供 crates.io 的镜像，方便国内 Rust 语言用户。

顺带安利一下 Rust：Rust 是一门设计非常棒的语言，1.0 还没正式出来，就已经倍受好评。不需要垃圾回收器就可以实现内存安全，并且效率非常高，是为数不多的可以与 C/C++ 这些底层语言匹敌的，同时还有各种函数式语言特性，强大的类型系统以及类型推断让其写起来像动态语言一样方便，是最近新出的语言中最具特色的也是最值得花时间学习的语言

**Comment by timzaak** [comment]
+1

**Comment by sjxxHero** [comment]
严重同意。

**Comment by fengqi** [comment]
+1

**Comment by l1nxy** [comment]
非常需要这个
国内的Rust开发环境会因为这个更好的

**Comment by 030io** [comment]
+10086

**Comment by zhsj** [comment]
貌似建一个反向代理比镜像更合理。

**Comment by vFix** [comment]
跪求rust干死c++！

**Comment by wangyuzhong** [comment]
非常需要，希望USTC同意，造福大家

**Comment by moon2l** [comment]
+1

**Comment by lilydjwg** [comment]
@zhsj 我也倾向于用反代+缓存。

**Comment by lansn** [comment]
+1

**Comment by cv9essex** [comment]
+1

**Comment by daogangtang** [comment]
+1

**Comment by zyings** [comment]
这个必须有啊，支持支持！！

**Comment by xiaokekeT** [comment]
+1

**Comment by zonyitoo** [comment]
+1

**Comment by messense** [comment]
+1

**Comment by carllhw** [comment]
+1

**Comment by anzhihun** [comment]
Rust是非常非常有吸引力的语言， 希望能有镜像来帮助广大学子顺畅学习， 校园网大家都懂的，谢谢！

**Comment by 5m1le71ger** [comment]
+1

**Comment by sablib** [comment]
+1

**Comment by Saklhc** [comment]
+1

**Comment by hawkbee** [comment]
+1

**Comment by niceskylei** [comment]
+1,支持

**Comment by F001** [comment]
+1 顶

**Comment by LuoLee** [comment]
+1

**Comment by liuhuancom** [comment]
+1

**Comment by wangyu190810** [comment]
支持。

**Comment by yuqaf1989** [comment]
+1

**Comment by HiWill** [comment]
+1

**Comment by marvin-min** [comment]
println!("{}赞",2^5}

**Comment by Eqistyre** [comment]
+1

**Comment by daleione** [comment]
+1

**Comment by qdao** [comment]
十分同意。。。建立国内镜像刻不容缓啊~~~~~~~~~~~~~

**Comment by airycanon** [comment]
+1

**Comment by hdczsf** [comment]
严重支持
每次cargo还要fq，太麻烦了

**Comment by sunng87** [comment]
:+1:

**Comment by hex1984** [comment]
+1

**Comment by zhsj** [comment]
由于此请求被刷屏，且support数也已经足够多了。我把这个issue改为仅管理员可发言。

如果有相关更新，我们会在这里回复。

**Comment by gaoyifan** [comment]
+1 不过我感觉官方源挺快的。。。。

**Comment by zhsj** [comment]
@gaoyifan ，不如你来建一个吧，
从cargo的配置来看，http://doc.crates.io/config.html
有两个参数较有用，一个是 `registry.index`，一个是`http.proxy`，

所以我们可以先做一份 https://github.com/rust-lang/crates.io-index 的 git 镜像，

然后做一个 http forward proxy，可以用 nginx，只代理 aws 和 crates 的网址。

**Comment by gaoyifan** [comment]
@zhsj 我过几天弄吧，最近还有有一门量子信息导论要考。。。。
P.S. 我想直接把文件都下载下来，可能效果会更好一些

**Comment by knight42** [comment]
我像 @zhsj 说的加了个反代, 大家可以在 .cargo/config 里加入:
```
[registry]
index = "git://crates.mirrors.ustc.edu.cn/index"
```

试用一下. 欢迎反馈 :-D

**Comment by wangyu190810** [comment]
已经试用，感觉完美。
版本ubuntu 14.04
用户目录下隐藏文件夹下：.cargo
创建 config
       [registry]
       index = "git://crates.mirrors.ustc.edu.cn/index"

**Comment by gaoyifan** [comment]
嗯嗯 现在index已经能够从USTC Mirrors下载了。但是真正的文件，仍然从S3上下载。

**Comment by gaoyifan** [comment]
@knight42 如果不修改cargo，我没有想到太好的办法。似乎只能给git仓库打patch，把config.son文件中的URI改掉。 或者我们追踪上游的修改，把patch打到我们自己的仓库上。

**Comment by tennix** [comment]
我提的这个方案是使用 cargo 插件机制实现下载 crates 功能，镜像站只需要静态伺服 crates 即可。因为绝大部分需求是下载问题， 而 publish, yank 等只有少部分用户会用到。
通过设置环境变量可以不用在当前 git 项目目录里添加 .cargo 目录，影响比较小，同时如果镜像出了问题也会平稳过渡到正常的 cargo build

**Comment by zhsj** [comment]
@gaoyifan 方法就是用 http forward proxy(不是 reverse proxy)，这样就能保证用户只改 cargo 配置就可以了

**Comment by daogangtang** [comment]
目前，“嗯嗯 现在index已经能够从USTC Mirrors下载了。但是真正的文件，仍然从S3上下载。”
还是没解决问题。

**Comment by gaoyifan** [comment]
@zhsj @knight42 mirrors的几条本地出口到S3的线路质量都不太高。如果是做代理，最好是把路由改成内网的网关(gateway-el)，通过出国隧道来访问S3。

**Comment by sunng87** [comment]
我还没有测试，不过 cargo 似乎是允许配置镜像地址的

在 index 的根目录会有一个 config.json 文件：

cat ~/.cargo/registry/index/github.com-88ac128001ac3a9a/config.json  
{
  "dl": "https://crates.io/api/v1/crates",
  "api": "https://crates.io/"
}

把这里的 dl 路径改为 ustc 的镜像路径就可以了

**Comment by gaoyifan** [comment]
@sunng87 这个文件是受git管理的。更新时，该文件会与上游保持一致。

**Comment by sunng87** [comment]
能否加一个脚本在更新后 patch 掉这个文件，或者如果是用git同步的话直接在本地的仓库里改掉这个文件并且提交？这个文件一般上游不会更新。

其实我这里下载 index 没问题，主要就是 dl 无法访问

**Comment by gaoyifan** [comment]
@sunng87  是的，我们正在这么实现。

**Comment by sunng87** [comment]
:+1: 赞

**Comment by tennix** [comment]
https://crates.io/api/v1/crates 这个 api 不是吐的 S3 的下载地址么，你们是怎么解决下载地址重定向到 S3 的，客户端的 cargo 会 follow 这个重定向地址，直接跳过你们这一层代理吧。
index 这个直接是 github repo，目前绝大部分用户访问应该没有什么问题，api 本身地址访问也应该没问题，问题主要是 crate 压缩包是放在 S3 上面的，这个一来相对来说比较大，二来 US 区的 S3 是在 GFW 外面的。所以要代理的话，需要保证用户下载 crate 时也是走你们的代理。我个人觉得把这些 crate 文件从 S3 拉到国内服务器上才是解决问题的最直接的方案，你们只需要跟传统的镜像站一样提供一个静态文件服务器然后定时同步一下就 OK 了

**Comment by gaoyifan** [comment]
@tennix 目前我们正在实现的方案是这样的：

1. 定时同步https://crates-io.s3-us-west-1.amazonaws.com/crates/ 整站。
2. 定时同步crates.io-index仓库，并改写其中的`config.json`文件。
3. nginx做crates.io的反向代理
4. 对`/api/v1/crates/{{name}}/{{version}}/download`的返回进行改写。

用户只需创建`~/.cargo/config`，设置registry即可。

**Comment by knight42** [comment]
唔... 我们走了一些弯路... 这次应该就真的可以了. 使用方法就是像上面说的, 在 .cargo/config 里指定 registry

```
[registry]
index = "git://crates.mirrors.ustc.edu.cn/index"
```

目前的处理是先把托管在 aws 的文件全部下载到服务器上, 然后 nginx 再做 rewrite.

由于最近有考试, 还没实现自动同步官方的 registry, 所以更新可能不太及时(后天就考完试了 \_(:з」∠)_), 请见凉.

如有问题, 欢迎反馈.

**Comment by sunng87** [comment]
还有一个小问题，能否不覆盖 config.json 里的 `api` 路径，这样 `publish` 的时候仍然可以发布到主仓库去。

也就是说把 config.json 设置为：

```json
{
  "dl": "https://crates.mirrors.ustc.edu.cn/api/v1/crates",
  "api": "https://crates.io/"
}
```

**Comment by knight42** [comment]
@sunng87 感谢反馈! 现在已经按照您说的修改了 :)

**Comment by sunng87** [comment]
感谢！亲测可用 :tada:

**Comment by gaoyifan** [comment]
@knight42  似乎并不需要反向代理。只用把/api/v1/crates/{{name}}/{{version}}/download重定向即可。cargo update时并不访问除了download以外的其他API。

**Comment by knight42** [comment]
@gaoyifan 嗯~ 我上面说的 nginx 做 rewrite 就是指把请求的地址重定向, 详情可查看现在服务器上 nginx 的配置.

**Comment by gaoyifan** [comment]
@knight42 nice！

**Comment by daogangtang** [comment]
挂了？

**Comment by daogangtang** [comment]
mike@tang:~/GIT/iota$ cargo build
    Updating registry `git://crates.mirrors.ustc.edu.cn/index`
 Downloading rustbox v0.8.1 (registry git://crates.mirrors.ustc.edu.cn/index)
error: unable to get packages from source

**Comment by axlrose** [comment]
严重支持，翻墙太痛苦了

**Comment by sunng87** [comment]
测试对我有效，可能是上游同步比较大超时了

**Comment by knight42** [comment]
@daogangtang 感谢报告. 这个文件服务器上是存在的, 我开 -v 测试了下, 发现有如下提醒
```
Caused by:
  SSL peer certificate or SSH remote key was not OK
```

我用 firefox 访问 https://crates.mirrors.ustc.edu.cn 以及 https://pypi.mirrors.ustc.edu.cn 都提示 SSL_ERROR_BAD_CERT_DOMAIN.

看来是我们泛域名的证书出问题了 @gaoyifan @zhsj

**Comment by gaoyifan** [comment]
问题确认。
昨天更换了新的SSL证书，但坑爹之处在于，网络信息中心给我们签发的不是泛域名证书，而是：
1. ustc.edu.cn
2. mirrors.ustc.edu.cn

这似乎意味着我们可以伪造科大主页（大误）

本来打算换回旧证书，但回退到旧版本的时候似乎将一些没有commit的配置给覆盖掉了，涉及以下两个文件：
sites-available/crates.mirrors.ustc.edu.cn
sites-available/npm.mirrors.ustc.edu.cn
@knight42 当时这两个文件是你修改的吗? 能否重做一次修改呢？
P.S. nginx还没有reload

**Comment by knight42** [comment]
我临时把下载地址改成 http 的了. 遇到此问题的用户可以先执行一下 `cargo update`, 再进行 build

**Comment by knight42** [comment]
@gaoyifan 学长这好像已经是第二次了... 我不太确定我还是否记得当时改了什么...

**Comment by gaoyifan** [comment]
@knight42  那我先reload nginx了

**Comment by tennix** [comment]
亲测已经恢复，多谢！

**Comment by daogangtang** [comment]
谢谢

**Comment by magj2006** [comment]
cargo install rustfmt 时，出错了
Caused by:
  [2/-1] Failed to connect to crates.mirrors.ustc.edu.cn: Network is unreachable

附: cat .cargo/config
[registry]
index = "git://crates.mirrors.ustc.edu.cn/index"

**Comment by zhsj** [comment]
@magj2006 这应该是你的网络问题，不过不建议在这个issue下讨论。可以发邮件到 lug@ustc.edu.cn，邮件请附上你的网络信息。

**Comment by sunng87** [comment]
Update:

最近 cargo 设置 mirror 有一些变化，自定义的 registry.index 要被废弃了：

https://github.com/rust-lang/cargo/pull/2857

**Comment by knight42** [comment]
@sunng87 感谢告知, 不过我已经更新了说明, 可以到[这里](https://lug.ustc.edu.cn/wiki/mirrors/help/crates)查看

**Comment by sunng87** [comment]
@knight42 赞，好快。话说新的这种方式会影响 `cargo publish` 吗？如果 publish 是发布到哪个 index 呢？

**Comment by knight42** [comment]
@sunng87 
我觉得这个问题应该只跟 index/config.json 里的 api 变量有关, 现在我们设置成了 "https://crates.io", 按理说应该是不影响的.

**Comment by sunng87** [comment]
@knight42 感谢！

**Comment by ScottHuangZL** [comment]
以前可以直接cargo run/build，不用特殊设置。
我7月底开始无法下载依赖，即使设置为中科镜像也不行。（晚上回家试试看镜像是否管用）
有何方案？

**Comment by knight42** [comment]
以前可以直接cargo run/build，不用特殊设置。
说明墙加高了 :/

     有何方案？
科学上网?

遇到问题烦请贴出 cargo build -v 的输出以及你现在的配置(~/.cargo/config), 以便我们定位问题.

**Comment by gaoyifan** [comment]
请不要滥用这个issue列表
镜像使用问题请致信官方邮箱lug（AT）ustc.edu.cn
镜像配置更新或修改请新开issue
