### ISSUE TITLE
建议增加KDE neon官方源镜像

### ISSUE THREAD

**Issue by FlyingheartCN** [ustclug/mirrorrequest#160]
官方仓库：http://archive.neon.kde.org/user/
KDE社区基于UbuntuLTS推出的系统，采用了最新的KDE桌面套件，是目前最适合的KDE发行版
这个系统简洁美观，而且与Ubuntu共享大部分软件，很方便使用

**Comment by zhsj** [comment]
上游似乎没有开发rsync？

**Comment by FlyingheartCN** [comment]
是的，没有
所以估计得找KDE那边谈一下

**Comment by zhsj** [comment]
duplicated with #110
