### ISSUE TITLE
request deepin server software repo

### ISSUE THREAD

**Issue by imxieke** [ustclug/mirrorrequest#163]
>Upstream   : rsync://rsync.deepin.com/deepin-server/
Description : Deepin Server, like Debian Server
Reason      ：offcial mirror speed very low(100k+)

## thinks

**Comment by hosiet** [comment]
@imxieke FYI, rsync.deepin.com 和 mirrors.ustc.edu.cn 服务器都在科大内（202.141.160.113）

**Comment by imxieke** [comment]
@hosiet  还真是 但是为啥没有 Deepin Server 镜像呢？

**Comment by gaoyifan** [comment]
@imxieke  mirrors.ustc.edu.cn 由 [USTC LUG](https://lug.ustc.edu.cn/) 管理。rsync.deepin.com 有deepin官方管理。  二者是独立运营的。

**Comment by imxieke** [comment]
@gaoyifan 同一机房 不同 ip 好大的差距 我是合肥移动 ![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f615.png)
![deepinscreenshot_select-area_20171209121300](https://user-images.githubusercontent.com/6483352/33792445-8aa32372-dcda-11e7-82ab-b2572d2ff92d.png)
![deepinscreenshot_select-area_20171209121325](https://user-images.githubusercontent.com/6483352/33792446-8ad81d34-dcda-11e7-8144-6eaa371d11a5.png)
![deepinscreenshot_select-area_20171209121407](https://user-images.githubusercontent.com/6483352/33792447-8b0a2c5c-dcda-11e7-90e3-b65f9e7f62c6.png)

**Comment by gaoyifan** [comment]
202.141.160.x 是电信地址；202.141.176.0 是移动地址。  deepin的服务器似乎没有接入移动线路。

访问202.141.176.x 是在合肥移动的省网中传输，自然比较快。
