### ISSUE TITLE
建议增加 NixOS 镜像

### ISSUE THREAD

**Issue by OlingCat** [ustclug/mirrorrequest#165]
## 上游源地址：
NixOS 的源需要用 nix 来同步，具体参见 https://nixos.org/nix-dev/2016-October/022029.html
例如，要添加 unstable channel 的源：
```bash
nix copy -r --store https://cache.nixos.community/ --to file:///tmp/my-mirror \
$(curl -L https://nixos.org/channels/nixos-unstable/store-paths.xz | xz -d)
```
## 项目简介
NixOS 是一个函数式发行版，它使用 nix 包管理器，通过声明式的配置文件来安装和更新，并可回滚至任意版本。nix 旨在彻底解决不同软件版本间的依赖问题，亦可多版本共存。

## 希望添加该镜像的原因
因为不明原因干扰，NixOS 的官方源在国内访问十分缓慢，希望 USTC 可以添加镜像用以加速。

## NixOS 更改源参考
http://nix-cookbook.readthedocs.io/en/latest/faq.html#how-do-i-add-a-new-binary-cache

**Comment by zhsj** [comment]
nix copy 可以处理增量同步吗？

如果上游可以给直接同步 s3 bucket 的权限，我们就可以用 [rclone](https://github.com/ustclug/ustcmirror-images#rsync) 同步了。

**Comment by OlingCat** [comment]
这个不清楚呃.. 乃来 https://github.com/NixOS/nixpkgs/issues/32659 这里问下 @edolstra 好了= =

**Comment by OlingCat** [comment]
https://github.com/NixOS/nixpkgs/issues/32659 里建议改为 https://cache.nixos.community/

**Comment by zhsj** [comment]
Basically, we hope upstream can provide a easy way to sync, e.g.

* rsync
* if upstream uses some cloud storage that [rclone](https://rclone.org/overview/) supports, please provide the credential like s3 access key and secret key(for read-only list).

otherwise, someone needs to devote his time to develop a custom sync tool which is easy to maintain and robust. But currently we [lack of a programmer](https://github.com/orgs/ustclug/projects/1#card-4094652)

**Comment by ZeroAurora** [comment]
同求啊啊啊

**Comment by ZeroAurora** [comment]
> Channel

> The usual way to obtain Nixpkgs is to subscribe to the Nixpkgs channel, which always contains the latest version of Nixpkgs:

> $ nix-channel --add https://nixos.org/channels/nixpkgs-unstable
> $ nix-channel --update

> After this, you can use nix-env to install available packages.

From: https://nixos.org/nixpkgs/download.html

这里只需要将 `https://nixos.org/channels/nixpkgs-unstable` 加入 nix-channel，是否就意味着只要同步 `https://nixos.org/channels/nixpkgs-unstable` 即可？

**Comment by ZeroAurora** [comment]
@zhsj  能否通过镜像https://nixos.org/channels/nixpkgs-unstable 或者构建 nixpkgs 仓库来达到目的？
看了一下，这仓库里的文件只有5个，跟之前许多文件的说法搭不上边，但它确实是 Nix 软件包仓库。（可能是因为 Nix 本身的改动）
（某 tuna 那里也没动静了。 。NixOS这么冷门的吗。。

**Comment by zhsj** [comment]
@ZeroAurora 我不使用 nix，我无法验证你说的方法对不对。

如果你可以给出具体的方法，并可以验证可行，那我们就可以镜像。如果没有人提供 **具体**、**可行** 的方法，那这个请求不会有任何进展。

**Comment by zhsj** [comment]
如果有人找到镜像的方法，欢迎在 https://github.com/ustclug/ustcmirror-images 提供 PR。

**Comment by shankerwangmiao** [comment]
所以你们这面情况如何了？我们这边貌似仍然没任何进展。

**Comment by yuchangyuan** [comment]
这个链接上面的方法有人尝试过吗：

https://nixos.org/nix-dev/2016-October/022029.html

**Comment by yuchangyuan** [comment]
最近试了下，大概下载了80G的内容。其中narinfo有45K个，nar有45K个。用的使用19.09的channel

**Comment by dramforever** [comment]
Draft of a syncing script: https://github.com/tuna/tunasync-scripts/pull/49

**Comment by yuchangyuan** [comment]
写了一个原型脚本，有条件的同学是否能测试一下。我自己在家测试功能应该是没有问题的。

https://github.com/shanghailug/nix_mirror

**Comment by yuchangyuan** [comment]
@dramforever 同学已经新增了NixOS同步需要的docker image（ustclug/ustcmirror-images#57），但 http://mirrors.ustc.edu.cn/ 上并没有新增NixOS的镜像，新增镜像还需要什么工作吗？

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/nix-channels/

欢迎测试与贡献帮助（<https://github.com/ustclug/mirrorhelp>）

:-)

**Comment by dramforever** [comment]
建议不允许列出 `store` 目录和 `store/nar` 目录内容，很长……

**Comment by taoky** [comment]
> 建议不允许列出 `store` 目录和 `store/nar` 目录内容，很长……

现在设置了 `autoindex off`，访问 `store` 和 `store/nar` 会返回 403.

**Comment by ZeroAurora** [comment]
实际使用的时候有些构建过程会从源代码缓存仓库 tarballs.nixos.org 下载文件（会fallback到源代码源站），感觉似乎这个网站可以反代（不过大概需求不大？）

**Comment by Freed-Wu** [comment]
Is it possible to add mirror for [nixpkgs.git](https://github.com/NixOS/nixpkgs)?

**Comment by taoky** [comment]
> Is it possible to add mirror for [nixpkgs.git](https://github.com/NixOS/nixpkgs)?

Please create a new issue about this git repo.
