### ISSUE TITLE
建议增加 FreeBSD Ports 镜像源

### ISSUE THREAD

**Issue by ykla** [ustclug/mirrorrequest#166]
目前已经完成了对 FreeBSD PKG 源的镜像，建议增加 Ports 源的镜像。目前 FreeBSD 在国内的处境十分尴尬，希望可以完善 FreeBSD 的源，比如 freebsd-update 源，portsnap 源。参见http://www.chinafreebsd.cn/article/chinafreebsd-resouce

**Comment by gaoyifan** [comment]
FreeBSD Port与 PKG的目录结构并不一样，并且上游关闭了列目录，分析起来有些麻烦。 暂时没有精力写同步器。 如果有人感兴趣欢迎撸一个。

**Comment by ykla** [comment]
参考www.chinafreebsd.cn
已经进行了镜像同步，使用lftp。

**Comment by gaoyifan** [comment]
> 已经进行了镜像同步，使用lftp。

@ykla FreeBSD Ports没有开列目录，如何lftp呢？  我在chinafreebsd网站上也没有看到这类说明。

**Comment by ykla** [comment]
http://www.chinafreebsd.cn/article/59db8e5079c1d
http://www.chinafreebsd.cn/article/59db8f6082121

目录好像的确克隆不了，苦笑

**Comment by zhsj** [comment]
@gaoyifan chinafreebsd 用的脚本里用了 http://ftp2.za.freebsd.org/pub/FreeBSD/ports/ 这个上游，可以列目录。

如果可以像 pkg 源写个特制的脚本，就比较好了

**Comment by ykla** [comment]
这里的脚本是否可以解惑？
https://github.com/ykla/freebsd-mirrors/

**Comment by gaoyifan** [comment]
@ykla 

就像之前 @zhsj 所说，这个脚本本质是从 `ftp2.za.freebsd.org` 用lftp强行将包拖下来。 然而 `ftp2.za.freebsd.org` 里的数据并不全，似乎只有head分支的源代码包。我检查了几个近期的历史版本（比如FreeBSD 11.0）的软件（如[vim](https://svn.freebsd.org/ports/tags/RELEASE_10_0_0/editors/vim/distinfo)），[源码包](http://distcache.FreeBSD.org/ports-distfiles/vim/7.4.004)并不存在。

鉴于此，我认为 lftp 强行拖一个半残的镜像并不是一个好的主意。

刚枚举了一下head分支，占用空间超过120GB，估计整个仓库尺寸远大于4TB。考虑到ports并不是一个常用的仓库，全量同步性价比实在太低。

个人不建议同步这个仓库。

**Comment by gaoyifan** [comment]
> 如果可以像 pkg 源写个特制的脚本，就比较好了

@zhsj  似乎很容易借助svn仓库枚举， 但Ports会占据比较大的空间。我倾向于量力而行，要不就算了吧?

**Comment by zhsj** [comment]
不懂 freebsd 用户的具体需求
加入 needvote 标签

**Comment by ykla** [comment]
@zhsj 
FreeBSD 有 四类源：
PKG源类似于二进制包安装管理器，比如pacman；
PORTS类似于源代码编译方式安装，主要是软件的源代码包；
freebsd-update是更新源，小版本更新，跨版本更新会用到；
Portsnap是ports包的快照，类似于gentoo portage 的  ebuild  快照，事实上，gentoo借鉴了Freebsd。

**Comment by gaoyifan** [comment]
@ykla  想向您请教一个问题： FreeBSD Ports 是否只有HEAD分支，而没有历史版本的概念？  如果我希望从源码安装一个历史版本的软件，Ports可以做到吗？

**Comment by ykla** [comment]
@gaoyifan 不是只有一个分支。
见：

http://meatwad.mouf.net/rubick/poudriere/

一般来说Ports会同时保留一个软件的多个版本。过旧的做不到。

**Comment by ykla** [comment]
@gaoyifan  
In general, most FreeBSD port work will be done within the head/ branch of the ports tree which is the actual ports tree used to install software. 

来自
https://www.freebsd.org/doc/en_US.ISO8859-1/articles/committers-guide/subversion-primer.html

5.2.5小节

**Comment by gaoyifan** [comment]
@ykla  如果只有一个head分支，应该不会消耗多少空间。  我近期尝试一下。

**Comment by gaoyifan** [comment]
同步完成，欢迎使用！ http://mirrors.ustc.edu.cn/freebsd-ports/

**Comment by ykla** [comment]
下午试试。

**Comment by gaoyifan** [comment]
@ykla  如有问题，欢迎反馈。
另外，特别感谢您给予的帮助~
