### ISSUE TITLE
Gentoo的镜像源没有正常更新同步

### ISSUE THREAD

**Issue by YangMame** [ustclug/mirrorrequest#167]
例如[amd64](http://mirrors.ustc.edu.cn/gentoo/releases/amd64/)
里面空掉了。。。

**Comment by zhsj** [comment]
应该是上游的问题，我们用的上游是 rsync://rsync3.tw.gentoo.org 也就是
http://ftp.isu.edu.tw/pub/Linux/Gentoo/releases/amd64/

**Comment by YangMame** [comment]
@zhsj 不考虑更换源地址么 tuna源正常

**Comment by gaoyifan** [comment]
更换上游：rsync://mirror.us.leaseweb.net/gentoo/
预计3小时后恢复

**Comment by gaoyifan** [comment]
已恢复
