### ISSUE TITLE
freebsd-pkg镜像存在问题：提示size mismatch

### ISSUE THREAD

**Issue by ykla** [ustclug/mirrorrequest#169]
pkg install vim
提示:
pkg: cached package *:size mismatch, cannot continue

尝试pkg update -f
以及rm /var/db/pkg/*

环境：FreeBSD11.1

源配置过程:

----------------------------------------------------------------------------------------------------
========================
freebsd-pkg 源使用帮助
========================

地址
====

https://mirrors.ustc.edu.cn/freebsd-pkg/

说明
====

FreeBSD PKG 软件源

收录架构
========

i386，amd64，aarch64, armv6, mips, mips64

收录版本
========

FreeBSD 8, FreeBSD 9, FreeBSD 10, FreeBSD 11, FreeBSD 12

使用方法
========
 
 
创建用户级PKG源文件 :
					`#mkdir -p /usr/local/etc/pkg/repos` ：
					`#cd /usr/local/etc/pkg/repos` ：
					`#ee 1.ustc.conf` 或 file:`#vi 1.ustc.conf` ：

* 添加以下内容以使用USTC源：

::

		ustc: {
		  url: "pkg+http://mirrors.ustc.edu.cn/freebsd-pkg/${ABI}/latest",
		  mirror_type: "srv",
		  signature_type: "none",
		  fingerprints: "/usr/share/keys/pkg",
		  enabled: yes
		}
	

* （建议）禁用系统级PKG源

	
	``mv /etc/pkg/FreeBSD.conf /etc/pkg/FreeBSD.conf.back``

 
然后运行 ``pkg update -f`` 更新索引以生效。 

相关链接
========

:官方主页: https://www.freebsd.org
:论坛: https://forums.freebsd.org/
:文档: https://www.freebsd.org/doc

**Comment by ykla** [comment]
url: "pkg+http://pkg1.freebsd.org/${ABI}/quarterly",

无此问题。（官方默认）
另外chinafreebsd.cn也有这个问题。
不知道是不是孤例。

**Comment by gaoyifan** [comment]
感谢报告！

这似乎是我在写同步脚本时没有考虑到的一种特殊情况，即：文件名不变，但文件内容发生变化。

我这两天抽空改下脚本吧

**Comment by ykla** [comment]
latest 和  quarterly 不知道有什么区别，但是FreeBSD 11默认是 quarterly。
使用 latest 会提示更新 pkg。

**Comment by gaoyifan** [comment]
quarterly 频道每个季度更新一次。

**Comment by gaoyifan** [comment]
同步估计需要数小时的时间~  同步完成后我会在这里反馈。

**Comment by gaoyifan** [comment]
已同步完成。请再试试看哈😆

**Comment by ykla** [comment]
@gaoyifan 
经过测试，目前没有问题。
另外我向mirrors-help的pull能否允许合并？

**Comment by gaoyifan** [comment]
请参考 review 信息修改文档。这个 issue 先关啦。

**Comment by gaoyifan** [comment]
@ykla  增加了 quarterly channel
