### ISSUE TITLE
 建议新增freebsd-update 源和portsnap 源，合并现有的FreeBSD 源

### ISSUE THREAD

**Issue by ykla** [ustclug/mirrorrequest#170]
现在USTC关于FreeBSD的镜像：

1、原FreeBSD 源，包含FreeBSD 镜像以及废弃的仓库。
http://mirrors.ustc.edu.cn/freebsd/

2、FreeBSD的pkg 二进制仓库源
http://mirrors.ustc.edu.cn/freebsd-pkg/

3、FreeBSD的ports 源
http://mirrors.ustc.edu.cn/freebsd-ports/

目前能否新增freebsd-update 源及 portsnap 源 ？

并对几个源进行合并。例如ports 源可以合并进入http://mirrors.ustc.edu.cn/freebsd/ports/ 这个目录。

freebsd-update 源可以进行更新。
portsnap 源用来同步更新ports 目录。

**Comment by gaoyifan** [comment]
我们不倾向于修改官方仓库的内容。另外，修改后还会增加帮助文档的维护难度（需要将freebsd-*的帮助文档都合并到freebsd）
目前这种方式有什么缺陷吗？

另外，请确保一个 issue 只包含一个镜像申请。

**Comment by ykla** [comment]
没有缺陷。
明天会重新请求。
