### ISSUE TITLE
建议新增FreeBSD portsnap源

### ISSUE THREAD

**Issue by ykla** [ustclug/mirrorrequest#171]
portsnap 是 ports 目录的快照，定时更新。

portsnap工具用于获取和更新FreeBSD ports的压缩快照，并提取和更新未压缩的ports。在正常的更新操作中，portsnap会定期将修改后的本地文件恢复到初始状态，并删除无法识别的本地文件。
 
如果要使用ports 则必须通过portsnap 源来下载更新ports 目录。(对于FreeBSD 11， FreeBSD 12来说，通过源码安装的方式过于复杂，且速度不超过10kb/s)。

**Comment by gaoyifan** [comment]
我近期刚开始使用 FreeBSD, 对各项工具都不太熟悉。
请问你知道如何同步 portsnap 吗？

**Comment by cnBSD** [comment]
portsnap 可以使用 http://sourcefire.portsnap.freebsd.org 作为源进行更新。

**Comment by ykla** [comment]
@cnBSD
请问有没有同步方法或者脚本？

**Comment by cnBSD** [comment]
@ykla 
命令如下，仅供参考：
`lftp -c open -e "mirror -c --parallel=128 --delete / /Storage/portsnap" http://sourcefire.portsnap.freebsd.org`

**Comment by ykla** [comment]
portsnap 已经废弃。该问题由于时间问题关闭。
