### ISSUE TITLE
建議添加Void Linux的鏡像和源

### ISSUE THREAD

**Issue by qiyunluoxing** [ustclug/mirrorrequest#173]
Void Linux是一個很有特點的發行版。
官網 https://www.voidlinux.eu/
維基百科 https://en.wikipedia.org/wiki/Void_Linux

使用runit作爲啓動與服務管理員，並且是滾動式發行版。
在國內沒有找到鏡像站。還勞煩可以添加到科大的鏡像中。

**Comment by iBug** [comment]
与 #73 重复，请到 #73 投票
