### ISSUE TITLE
建议增加FreeNas国内镜像源

### ISSUE THREAD

**Issue by dpzhang314** [ustclug/mirrorrequest#174]
> FreeNAS是一个基于BSD和集成RAID支持了ZFS文件系统的NAS（Network Attached Storage）系统。
>     采用 ZFS 文件系统存储、管理和保护数据。支持众多的插件和虚拟化应用。

## 常见应用

- 家庭、企业文件共享；
- 为虚拟化服务提供后端存储，
- 构建影音媒体中心和 DLNA 设备。

## FreeNas
[官方主页](http://www.freenas.org/) 
[邮件列表](http://lists.freenas.org/mailman/listinfo)
[官方论坛](http://forums.freenas.org/)

## [镜像源](http://download.freenas.org)  download.freenas.org

国内下载非常缓慢，安装更新和添加jail及VMs很困难，希望把他加到ustc的mirrors中方便国人使用。多谢。

**Comment by Lookinfres** [comment]
支持

**Comment by dpzhang314** [comment]
**非常感谢thumbs up的各位兄弟，非常感谢ustc的管理员的辛勤工作，在第一时间回复。**

经过一段时间的摸索发现：freenas的下载站点更新中的版本众多，不同版本的iso很多，plugins中的版本也是非常多，估计管理员是打包狂人。所以没有必要在国内占用ustc宝贵的空间和带宽搞这么一个鸡肋的事情。

**现给出完美的解决方案。**

>先啰嗦一下。
      freenas 管理 plugins的实质
        plugins的实质 是基于plugin的模板定制的jail
        安装freenas的plugins之前会先安装plugin的模板
       如果能提前在storage中安装plugins的模板，系统安装的速度就会明显提速，当然也就可以离线安装各个plugins了。

**步骤**：

- 下载 [jails模板](http://download.freenas.org/jails/)   pluginjail的那个文件。
- 创建数据集mystore和shared并共享后者，通过samba将模板拖到共享中。
- 打开ssh连接或者系统的命令行
- `warden template create -nick pluginjail -tar /mnt/mystore/shared/freenas-pluginjail-11.0-RELEASE.bz2`

**Comment by pifeifei** [comment]
哈哈，打包狂人
