### ISSUE TITLE
申请增加jenkins的插件的镜像

### ISSUE THREAD

**Issue by Tempal** [ustclug/mirrorrequest#176]
Jenkins是一个开源软件项目，是基于Java开发的一种持续集成工具，用于监控持续重复的工作，旨在提供一个开放易用的软件平台，使软件的持续集成变成可能。
jenkins官网镜像下载经常有问题，希望能有jenkins插件的镜像，谢谢。
ps：可以使用下面命令同步jenkins的镜像
rsync -avz rsync://rsync.osuosl.org/jenkins/updates/

**Comment by zhsj** [comment]
merge with #112

**Comment by gaoyifan** [comment]
http://mirrors.ustc.edu.cn/jenkins/
