### ISSUE TITLE
kubernates 的 docker 镜像仓库 k8s.gcr.io(Google Cloud Registry (GCR))

### ISSUE THREAD

**Issue by loverto** [ustclug/mirrorrequest#177]
#### 项目名称与简介(Project Intro.)
kubernates 的 docker 镜像仓库 k8s.gcr.io(Google Cloud Registry (GCR))
#### 上游地址与镜像方法(How to Mirror)
k8s.gcr.io 应该类似于docker官方的镜像仓库第同步方式,不是yum安装的,是docker镜像
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by zhsj** [comment]
目前可以使用 `sed s|k8s.gcr.io|gcr.mirrors.ustc.edu.cn/google-containers|g`

**Comment by loverto** [comment]
这个是镜像还是反向代理

**Comment by loverto** [comment]
下载的好慢,不如docker镜像快

**Comment by zhsj** [comment]
@loverto 反代，所有docker相关的内容无法镜像

**Comment by loverto** [comment]
Ok, 了解了

**Comment by isaacdong** [comment]
目前可以使用 sed s|k8s.gcr.io|gcr.mirrors.ustc.edu.cn/google-containers|g 在哪里执行这个命令呢？
