### ISSUE TITLE
Archlinux镜像同步的上游能换成别的吗？

### ISSUE THREAD

**Issue by kosmosoahc** [ustclug/mirrorrequest#178]
不明白为什么是清华的镜像，这样子那我不是直接用**tuna**的镜像更好？
_Upstream：rsync://mirrors.tuna.tsinghua.edu.cn/archlinux/_
他们的时好时坏，更新也不稳定，能换成国外及时同步更新的上游吗？

**Comment by gaoyichuan** [comment]
tuna 是 archlinux 国内唯一的 Tier 1 mirror，如果你发现我们(tuna)的服务出现不稳定的情况，请到 https://github.com/tuna/issues 汇报，谢谢！

**Comment by Harry-Chen** [comment]
因为TUNA镜像是Tier-1的。
另外，遇到TUNA镜像的问题，可以到 github.com/tuna/issues/issues 报告
目前我们没有接到我们提供的 Arch Linux 镜像「时好时坏」的报告，维护者在使用时也没有遇到此类问题。
多谢理解。

**Comment by zhsj** [comment]
镜像站之间不是竞争关系，用户应该根据自己的网络情况，择优选择速度更好的，不存在直接使用 tuna 是否更好的问题。

**Comment by zhsj** [comment]
All tuna related upstream urls are changed to rsync://nanomirrors.vip.s.tuna.tsinghua.edu.cn/ since tuna doesn't guarantee the same content between nanomirrors and neomirrors.
