### ISSUE TITLE
[New] Elasticsearch & Logstash mirror request

### ISSUE THREAD

**Issue by bojieli** [ustclug/mirrorrequest#18]
Elasticsearch repo: https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html
Logstash repo: https://www.elastic.co/guide/en/logstash/current/package-repositories.html

These repos seem to host on Amazon S3 and GFW certified.

Mirror can be created with apt-mirror (Debian) and reposync (CentOS).

**Comment by zhsj** [comment]
为什么单单把 ELK 里的 Kibana 漏了呢。。。

对于这些仅仅因为被 GFW 且可能十分小众的源，是否提供一个统一的加入方法？毕竟很多人来请求加一些小众的源，理由都是因为被 GFW。
比如，建一个反向代理，对此类需要的源只做代理，相当于只是提供一个 FQ 途径。
另外，对这类源做一个总的速度限制，比如从 mirrors 现有带宽里抽出 10M 来做这个。

**Comment by gaoyifan** [comment]
上次Parrot Security OS也是类似需求。我给它用百度云加速CDN做了个代理。
我觉得我们可以给ustclug.org备个案，这样就可以使用国内的CDN做反代。

**Comment by bojieli** [comment]
2016-02-06 18:48 GMT+08:00 Shengjing Zhu <notifications@github.com>:

> 为什么单单把 ELK 里的 Kibana 漏了呢。。。
>
因为我不知道 Kibana…… 只用了 ElasticSearch 和 Logstash……

**Comment by TurnOffNOD** [comment]
@zhsj 不管是什么方案，都只能针对校内开放。

**Comment by zhsj** [comment]
@TurnOffNOD 反向代理没必要只限制校内。
一，代理肯定是白名单的，和我们提供镜像从外面看上去是一样的；
二，这个代理我希望是限制带宽的，也就不会对现有源的流量造成影响。

**Comment by gaoyifan** [comment]
@zhsj 如果要用国内CDN，得先给ustclug.org备案，或者让James Zhang帮忙验证ustc.edu.cn。

**Comment by gaoyichuan** [comment]
我希望可以做一个统一的平台，提供网页或者API之类的接口，便于大家提交需要反代的页面，经人工审核(？)后发布

**Comment by zhsj** [comment]
2016-02-13 16:35 GMT+08:00 Gao Yichuan <notifications@github.com>:

> 我希望可以做一个统一的平台，提供网页或者API之类的接口，便于大家提交需要反代的页面，经人工审核(？)后发布
>

这倒没必要，申请可以继续在这个 github issue 上。


-- 
Best regards,
Zhu Shengjing

**Comment by TurnOffNOD** [comment]
@zhsj 我的意思是只有校内ip访问这个反代的时候给代理作用，校外ip就直接拒绝或者其他手段。
放假在校外怎么办？lug-vpn嘛。

**Comment by zhsj** [comment]
2016-02-13 19:51 GMT+08:00 Thomas Copper <notifications@github.com>:

> @zhsj <https://github.com/zhsj> 我的意思是只有校内ip访问这个反代的时候给代理作用，校外ip就直接拒绝或者其他手段。
> 放假在校外怎么办？lug-vpn嘛。


你可能没理解这个反代的作用，这个反代达成的目的是和mirrors一样，提供一个类似的镜像，所以服务对象是所有人而不只是科大同学。


-- 
Best regards,
Zhu Shengjing

**Comment by knight42** [comment]
packages.elastic.co -> elastic.proxy.ustclug.org
