### ISSUE TITLE
建议增加 Ubuntu Mate ARM 镜像

### ISSUE THREAD

**Issue by qrzbing** [ustclug/mirrorrequest#180]
在获取 Ubuntu 衍生版安装镜像时发现没有 Ubuntu Mate ARM 版本的镜像，希望能加入该镜像（主要是为了树莓派）。

**Comment by Alkaid-Benetnash** [comment]
我们ubuntu衍生版镜像的上游是ubuntu cdimage, 在上游就没找到arm的镜像。用的人太少了吧。

http://cdimage.ubuntu.com/ubuntu-mate/releases/16.04.3/release/

**Comment by qrzbing** [comment]
这样子啊。。
