### ISSUE TITLE
建议增加 MELPA 镜像

### ISSUE THREAD

**Issue by ksqsf** [ustclug/mirrorrequest#182]
Site: https://melpa.org/
Site: https://github.com/melpa/melpa

MELPA 是 Emacs 最大最重要的 package archive，但国内访问速度很不理想。

**Comment by xiaozhu1337** [comment]
咋没下文了

**Comment by ksqsf** [comment]
1. 目前已有 Emacs China、TUNA 镜像，没有迫切需求。
2. Mirrors 目前还有一些优先级更高的任务，在这些任务完成之前暂时不会做。

**Comment by ksqsf** [comment]
Done.
