### ISSUE TITLE
希望增加CDH镜像

### ISSUE THREAD

**Issue by all3n** [ustclug/mirrorrequest#185]
上游源（官方镜像）的地址：
archive.cloudera.com

该项目的介绍：
CDH (Cloudera's Distribution, including Apache Hadoop)，是Hadoop众多分支中的一种，由Cloudera维护，基于稳定版本的Apache Hadoop构建，并集成了很多补丁，可直接用于生产环境。
Cloudera Manager则是为了便于在集群中进行Hadoop等大数据处理相关的服务安装和监控管理的组件，对集群中主机、Hadoop、Hive、Spark等服务的安装配置管理做了极大简化。

为什么希望添加该镜像：
国内访问非常缓慢

**Comment by zhsj** [comment]
dup #56
