### ISSUE TITLE
建议新增 gcr.io 镜像，内附方法

### ISSUE THREAD

**Issue by bubbleatgit** [ustclug/mirrorrequest#187]
## 项目介绍
gcr.io 主要为 kubernetes 的一些组件，国内用户在初始化 kubernetes 的时候，不翻墙压根初始化不了。

## 镜像方法
* Upstream:  https://gcr.io
* 道具: Docker registry:latest

```
proxy:
  #remoteurl: https://registry-1.docker.io
  remoteurl: https://gcr.io
```

## 测试结果
`这是自己的 vps ，带宽有限，请大家测试的时候悠着点流量`

```
$ sudo docker pull registry.u17.io/google_containers/kubernetes-dashboard-amd64:v1.7.1
v1.7.1: Pulling from google_containers/kubernetes-dashboard-amd64
fb18e0636263: Pull complete 
Digest: sha256:327cfef378e88ffbc327f98dd24adacf6c9363c042db78e922d050f2bdcf6f78
Status: Downloaded newer image for registry.u17.io/google_containers/kubernetes-dashboard-amd64:v1.7.1
$ sudo docker pull registry.u17.io/google_containers/kubedns-amd64:1.9
1.9: Pulling from google_containers/kubedns-amd64
8ddc19f16526: Pull complete 
a3ed95caeb02: Pull complete 
acc68ed00435: Pull complete 
Digest: sha256:3d3d67f519300af646e00adcf860b2f380d35ed4364e550d74002dadace20ead
Status: Downloaded newer image for registry.u17.io/google_containers/kubedns-amd64:1.9

**Comment by zhsj** [comment]
dup #91 

https://gcr.mirrors.ustc.edu.cn/

**Comment by bubbleatgit** [comment]
这个不是反代的吗？速度有点跟不上？

**Comment by gaoyifan** [comment]
@bubbleatgit  我们目前使用的就是 *registry:latest*。docker registry 本质也只是反代+缓存，并不是完整镜像。

**Comment by bubbleatgit** [comment]
@gaoyifan ok，这样就好点，registry 还是比单纯的反代要好的多的。

**Comment by ok-dok** [comment]
现在是不能用了吗

**Comment by taoky** [comment]
> 现在是不能用了吗

http://mirrors.ustc.edu.cn/help/dockerhub.html

**Comment by zjcnew** [comment]
又不对外了？
docker pull gcr.mirrors.ustc.edu.cn/google_containers/kube-scheduler:v1.18.2
Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>openresty</center>\r\n</body>\r\n</html>\r\n"

**Comment by skyzh** [comment]
> 又不对外了？
> 
> `docker pull gcr.mirrors.ustc.edu.cn/google_containers/kube-scheduler:v1.18.2`
> 
> `Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>openresty</center>\r\n</body>\r\n</html>\r\n"`

> 由于访问原始站点的网络带宽等条件的限制，导致 Docker Hub, Google Container Registry (gcr.io) 与 Quay Container Registry (quay.io) 的镜像缓存处于基本不可用的状态。故从 2020 年 4 月起，从科大校外对 Docker Hub 镜像缓存的访问会被 302 重定向至其他国内 Docker Hub 镜像源。从 2020 年 8 月 16 日起，从科大校外对 Google Container Registry 的镜像缓存的访问会被 302 重定向至阿里云提供的公开镜像服务（包含了部分 gcr.io 上存在的容器镜像）；从科大校外对 Quay Container Registry 的镜像缓存的访问会被 302 重定向至源站。

> 2020/08/21 更新：考虑到 gcr 镜像重定向至阿里云提供的公开镜像服务可能存在的安全隐患（见 mirrorhelp#158），目前校外对 gcr 镜像的访问返回 403。

请参见文档。
