### ISSUE TITLE
申请建立 wine-builds 镜像

### ISSUE THREAD

**Issue by njlyf2011** [ustclug/mirrorrequest#188]
项目名称与简介(Project Intro.)
WineHQ 项目的二进制包，WineHQ 简单来说就是个在 Linux 上跑 Windows 程序的兼容层，具体可以百度。
wine-builds 在国内访问实在是太慢，故申请建立一个同步镜像。。。

上游地址与镜像方法(How to Mirror)
http://dl.winehq.org/wine-builds/

镜像方法：看样子可以 rsync

**Comment by zhsj** [comment]
1. 没有找到可以 rsync 的地址

2. 和 #117 重复，之前好像通过同步 ftp://ftp.winehq.org/pub/ 的方式同步了 wine-builds，但最近 wine-builds 从 ftp 里不见了。

所以，我把  #117 重新 open 了，后续讨论请集中在 #117
