### ISSUE TITLE
rust-static 镜像有问题,无法升级工具链

### ISSUE THREAD

**Issue by autumnshine** [ustclug/mirrorrequest#191]
这是设置的环境变量：

![nrnct2 u1gtib qg 34w5g7](https://user-images.githubusercontent.com/28615195/39701589-50e810fa-5234-11e8-845d-8f25b8e26522.png)

这是出现的问题：

![yeu y 885 bpf p tgbf](https://user-images.githubusercontent.com/28615195/39701625-76bc6bf0-5234-11e8-9c04-ce619bd06dc6.png)

**Comment by autumnshine** [comment]
补一张图：



![tim 20180507202520](https://user-images.githubusercontent.com/28615195/39701778-0dfbf3dc-5235-11e8-9870-73b36c054990.png)

**Comment by knight42** [comment]
问题原因是缓存的 toml 的哈希值与缓存的 .toml.sha256 里的内容对不上。现在已经在 @Alkaid-Benetnash 的帮助下解决了，目前的做法是禁止缓存 .toml 与 .toml.sha256 文件。

如有其它问题，欢迎继续提出。

**Comment by autumnshine** [comment]
好的，感谢你们提供的镜像，谢谢！

在 2018年5月11日，下午4:05，Jian Zeng <notifications@github.com<mailto:notifications@github.com>> 写道：


问题原因是缓存的 toml 的哈希值与缓存的 .toml.sha256 里的内容对不上。现在已经在 @Alkaid-Benetnash<https://github.com/Alkaid-Benetnash> 的帮助下解决了，目前的做法是禁止缓存 .toml 与 .toml.sha256 文件。

如有其它问题，欢迎继续提出。

**Comment by autumnshine** [comment]
好的，感谢你们提供的镜像！谢谢！

在 2018年5月11日，下午4:05，Jian Zeng <notifications@github.com<mailto:notifications@github.com>> 写道：


问题原因是缓存的 toml 的哈希值与缓存的 .toml.sha256 里的内容对不上。现在已经在 @Alkaid-Benetnash<https://github.com/Alkaid-Benetnash> 的帮助下解决了，目前的做法是禁止缓存 .toml 与 .toml.sha256 文件。

如有其它问题，欢迎继续提出。
