### ISSUE TITLE
建议添加 OpenWrt 旧版本软件源

### ISSUE THREAD

**Issue by rwv** [ustclug/mirrorrequest#193]
现今的 [LEDE/OpenWrt](https://mirrors.ustc.edu.cn/lede/) 源是对 https://downloads.lede-project.org/ 的完整镜像，而老版本的 OpenWrt 源如 Chaos Calmer 15.05.1 的软件包均存放在 http://archive.openwrt.org 域名下，如 http://archive.openwrt.org/chaos_calmer/15.05.1/
因此希望添加一个对 archive.openwrt.org 的单独镜像。

**Comment by dfc643** [comment]
同希望添加，今天 archive 挂了

**Comment by youxiaojie** [comment]
支持

**Comment by imlk0** [comment]
+1
