### ISSUE TITLE
ros源使用的umd上游频繁发生问题，建议更换

### ISSUE THREAD

**Issue by htfy96** [ustclug/mirrorrequest#195]
本月ros源的上游 rsync://mirror.umd.edu/packages.ros.org/ros/ 已发生过两次12h以上的故障。SJTUG镜像站已更换成了 rsync.osuosl.org::ros-main 同步到原来地址的`/ubuntu`下，目前运作良好

**Comment by gaoyifan** [comment]
感谢反馈。 我来将上游切换到官方源吧。

**Comment by gaoyifan** [comment]
已更换为 http://packages.ros.org/ros/ubuntu
