### ISSUE TITLE
nvidia cuda 镜像

### ISSUE THREAD

**Issue by all3n** [ustclug/mirrorrequest#196]
上游源（官方镜像）的地址:http://developer.download.nvidia.com/compute/cuda/repos/
该项目的介绍:nvidia cuda 官方镜像，用于深度学习
为什么希望添加该镜像：国内访问比较慢

**Comment by zhsj** [comment]
请列出 NVIDIA 对该软件是否可进行再分发的说明。

**Comment by cuihaoleo** [comment]
应该可以分发，毕竟很多发行版都有自己打包。
不过不是开源软件（

**Comment by zhsj** [comment]
> 应该可以分发，毕竟很多发行版都有自己打包。
是否有官方的说明？

**Comment by gaoyifan** [comment]
@zhsj   可以重分发，但不能改变内容。 https://docs.nvidia.com/cuda/eula/index.html#toolkit-os
