### ISSUE TITLE
docker.elastic.co 镜像

### ISSUE THREAD

**Issue by exherb** [ustclug/mirrorrequest#198]
上游地址：https://docker.elastic.co
介绍：elastic 官方 docker 镜像, https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
为什么希望添加该镜像：elastic 官方镜像国内访问速度基本为 0, 严重影响工作效率

**Comment by zhsj** [comment]
我个人赞成这个镜像，但我发现每个 docker registry 镜像我们都要起一个“反向代理”[1] 的实例，这让我感到不能接受。

不知道大家有什么代理 docker registry 好的工具？

[1] https://github.com/docker/distribution

**Comment by vsxen** [comment]
https://github.com/AliyunContainerService/sync-repo  
这个怎么样？

**Comment by ykfq** [comment]
> 我个人赞成这个镜像，但我发现每个 docker registry 镜像我们都要起一个“反向代理”[1] 的实例，这让我感到不能接受。
> 
> 不知道大家有什么代理 docker registry 好的工具？
> 
> [1] https://github.com/docker/distribution

Docker 代理当然是 Nexus3 最好了，可以添加 Docker Hub、Google Container、qury.io 以及你提到的 elastic.io 镜像代理，我们已经在公司内部实现这个功能了，强大好用

**Comment by exherb** [comment]
out of date.
