### ISSUE TITLE
Request for LibreOffice download mirror

### ISSUE THREAD

**Issue by Bambooin** [ustclug/mirrorrequest#199]
What's LibreOffice:
LibreOffice is community-driven and developed software, and is a project of the not-for-profit organization, The Document Foundation. LibreOffice is free and open source software, originally based on OpenOffice.org (commonly known as OpenOffice), and is the most actively developed OpenOffice.org successor project.

Reasons:
Though the download speed is not bad, we should have a better mirror for mainland of China. The mirror will speed download speeds sharply.

Info:
Information on how to mirror: https://wiki.documentfoundation.org/Infra/Mirroring

**Comment by zhsj** [comment]
Already mirrored long long ago, https://mirrors.ustc.edu.cn/tdf/
