### ISSUE TITLE
  [New] FreeBSD pkgng 软件仓库

### ISSUE THREAD

**Issue by hosiet** [ustclug/mirrorrequest#2]
有关 pkgng 的详情，请参考 FreeBSD Wiki：https://wiki.freebsd.org/pkgng
自 FreeBSD 10 以后，FreeBSD 默认使用 pkg(8) 作为二进制软件包管理器，且正在替代 ports 的作用。

上游地址：http://pkg.freebsd.org/
相关邮件存档：https://lists.freebsd.org/pipermail/freebsd-pkg/2013-October/000107.html

据说 FreeBSD 现在不接受新的官方镜像，也未提供镜像工具与方式。

**Comment by cuihaoleo** [comment]
根据： https://www.freebsd.org/doc/en/articles/hubs/mirror-official.html#mirror-official-become
既然不接受，先打上 wontfix 吧。
