### ISSUE TITLE
提供 nodesource 配置脚本

### ISSUE THREAD

**Issue by ksqsf** [ustclug/mirrorrequest#200]
[Nodesource 上游](https://github.com/nodesource/distributions) 提供一个 setup_N.x 的配置脚本，这个脚本可以自动设置软件源并自动安装。

我们的镜像站似乎没有同步这个脚本，但实际上可以把里面的 [deb|rpm].nodesource.com 相应地替换为 mirrors.ustc.edu.cn/[deb|rpm] 从而提供更好的用户体验。

**Comment by iBug** [comment]
Dismissed: <https://servers.ustclug.org/2021/02/nodesource-removal/>
