### ISSUE TITLE
termux-root

### ISSUE THREAD

**Issue by yangzhaofeng** [ustclug/mirrorrequest#202]
上游源（官方镜像）的地址  https://grimler.se
该项目的介绍 https://github.com/termux/termux-root-packages/blob/master/README.md
为什么希望添加该镜像 提升termux在國內的使用體驗

**Comment by iBug** [comment]
这个东西是不是已经存在好久了？

<https://mirrors.ustc.edu.cn/termux/termux-root-packages-24/>
