### ISSUE TITLE
Lede镜像源的/snapshots/targets目录404

### ISSUE THREAD

**Issue by NorthNanmu** [ustclug/mirrorrequest#203]
http://mirrors.ustc.edu.cn/lede/snapshots/targets/
打开后报错404

而官方的
https://downloads.lede-project.org/snapshots/targets/
是有内容的

以上。

**Comment by gaoyifan** [comment]
考虑到snapshot更新较为频繁，且用户有限， 因此我们没有同步该目录。

原始讨论见：
1. https://groups.google.com/forum/#!topic/ustc_lug/XFPsyGf72c4
2. https://github.com/ustclug/mirrorrequest/issues/44

**Comment by gaoyifan** [comment]
已增加跳转规则，请测试。
***
patch:
```diff
+    rewrite ^/lede/snapshots/(.*?)$ $scheme://downloads.lede-project.org/snapshots/$1;
```

**Comment by gaoyifan** [comment]
未收到回复，issue关闭。

**Comment by zuosc** [comment]
#240 
是否可以考虑每7天同步一次snapshots   

koolshare不知为何默认配置的是这个源。所以还是有一定用户需求的
