### ISSUE TITLE
Fedora Sliverblue 镜像

### ISSUE THREAD

**Issue by bobby285271** [ustclug/mirrorrequest#204]
**请不要在此反馈镜像故障** ，请在 https://github.com/ustclug/discussions/issues 反馈镜像故障！
**Please don't report mirror faults here**, please report faults at https://github.com/ustclug/discussions/issues

请介绍新镜像
* 上游源（官方镜像）的地址

https://kojipkgs.fedoraproject.org/atomic/repo/

镜像方法 https://miabbott.github.io/2018/03/16/setting-up-faw-pirate-mirror.html

* 该项目的介绍

原 Fedora Atomic Workstation.
https://docs.fedoraproject.org/en-US/fedora-silverblue/

* 为什么希望添加该镜像

Fedora Sliverblue 的镜像能在 fedora 目录中获取，然而 fedora 目录不提供其软件仓库。

Please tell more about your request
* Upstream URL
* Introduction of the project
* Why do you hope we add this mirror

**Comment by skyzh** [comment]
We have set up a beta mirror at SJTUG. Would you please have a try?

https://github.com/sjtug/mirror-requests/issues/87

**Comment by bobby285271** [comment]
> We have set up a beta mirror at SJTUG. Would you please have a try?
> 
> [sjtug/mirror-requests#87](https://github.com/sjtug/mirror-requests/issues/87)

![screenshot](https://user-images.githubusercontent.com/20080233/104181735-4234c600-544a-11eb-888e-f6ff1b7f8297.png)

用上了，非常感谢！
