### ISSUE TITLE
添加helm charts的官方反向代理

### ISSUE THREAD

**Issue by loverto** [ustclug/mirrorrequest#205]
**请不要在此反馈镜像故障** ，请在 https://github.com/ustclug/discussions/issues 反馈镜像故障！
**Please don't report mirror faults here**, please report faults at https://github.com/ustclug/discussions/issues

请介绍新镜像
* 上游源（官方镜像）的地址
https://kubernetes-charts.storage.googleapis.com/
* 该项目的介绍

HELM charts的官方镜像
* 为什么希望添加该镜像

安装镜像时需要用到这个

Please tell more about your request
* Upstream URL
* Introduction of the project
* Why do you hope we add this mirror

**Comment by loverto** [comment]
@Alkaid-Benetnash

**Comment by yifeikong** [comment]
请问有更新么? 国内貌似还没有 helm 的镜像

**Comment by ksqsf** [comment]
Hi，刚刚部署了 http[s]://kubernetes-charts.proxy.ustclug.org/ ，由于没有相关经验，所以不知道是否正常工作。可否测试并告知我们呢？

**Comment by yifeikong** [comment]
@ksqsf 可以正常使用

```
-> % helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈

-> % helm repo list
NAME    URL
stable  http://kubernetes-charts.proxy.ustclug.org/
local   http://127.0.0.1:8879/charts
```
