### ISSUE TITLE
Adding Ubuntu Server

### ISSUE THREAD

**Issue by ZhengxuWu** [ustclug/mirrorrequest#206]
https://cn.ubuntu.com/server/
Different from Ubuntu For Desktop,Ubuntu Server provides a very different way to customize ubuntu like changing your GUI

**Comment by cuihaoleo** [comment]
Ubuntu Server 版本使用的软件仓库与桌面版是一样的，我站已经提供。安装镜像也可以在 ubuntu-cdimage 或者 ubuntu-releases 下找到。

请再明确一下你需要什么镜像？
