### ISSUE TITLE
Armbian 软件仓库和发行版镜像

### ISSUE THREAD

**Issue by Jamesits** [ustclug/mirrorrequest#207]
## 上游源（官方镜像）的地址

正式版软件源：
https://apt.armbian.com/
rsync://rsync.armbian.com/apt

Beta 版软件源：
https://beta.armbian.com/
rsync://rsync.armbian.com/beta

镜像下载：
https://dl.armbian.com/
rsync://rsync.armbian.com/dl

## 该项目的介绍

Armbian 是一个针对大量 ARM 开发板的 Debian/Ubuntu 适配项目，在现有的系统基础上加入了大量自有及来自 linux-sunxi 等社区的 patch 和软件，使这些 ARM 设备的硬件功能能够开箱即用。通常来说，Armbian 会比厂商提供的 BSP 更干净，用户体验也更好。同时，Armbian 对各类 ARM 处理器的 Linux 主线化工作亦有贡献。

## 为什么希望添加该镜像

Armbian 适配的很大一部分硬件均产自中国也销往中国，但是其下载站和软件源在中国的连接性不佳，这使得 Armbian 在国内的推广很难进行，很多用户仍然在使用厂商发布的万年不更新并且开源状况和版权状况均很混乱的 BSP 系统。请求该镜像是因为希望每个 ARM 开发板用户都能平等地用上开源、自由、安全的 Linux 发行版。

**Comment by LuvLetter** [comment]
![image](https://user-images.githubusercontent.com/9290109/47948788-8aa2f000-df72-11e8-9559-1ba3b9e28d39.png)
最近好久没动 Armbian 的板子, 结果发现包下起来贼慢. 也突然才想到 USTC 没有.
- 以及希望USTC的sed脚本能好好写,之前那些sed通用性太差-

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/armbian/

https://mirrors.ustc.edu.cn/armbian-dl/
