### ISSUE TITLE
reactos软件仓库和ISO镜像

### ISSUE THREAD

**Issue by youxiaojie** [ustclug/mirrorrequest#210]
source code:
https://github.com/reactos/reactos
iso:
https://reactos.org/download
ReactOS 旨在实现和NT与XP操作系统二进制下的完全应用程序和驱动设备的兼容性，通过使用类似构架和提供完全公共接口。 [1] 
根据专利法,目前模拟DOS和WINDOWS2.0是合法的,除了微软在1990年以后注册的专利.
2020年,本系统有可能不违反专利法
自由软件倡导者认同自由软件操作系统现状的改善促进了竞争，ReactOS也同样获益匪浅ReactOS是最完整的类 Windows操作系统的工作平台， 因此，参与开发的程序员需要花费许多精力去学习ReactOS源码 和研究ReactOS开发文档。
ReactOS组件也越来越多，兼容性也越来越好，但 ReactOS 不会有任何束缚。 ReactOS已经并将继续吸收最新版本的Win32 API，跟踪甚至发展最新的操作系统技术 。尽我们所能，使用最新的技术，并不断的融合新的特点到最新版本。
简单地说，ReactOS目标就是用您的硬件设备去运行您的应用程序，最后，诞生一个任何人都可以免费使用的 FOSS 操作系统。
请记住，ReactOS仍在 alpha 试验阶段，不推荐日常工作使用
ReactOS 市场定位 很明确：
（第二点内容是ReactOS目标的必然结果）
一要开源自由；二要针对普通老百姓。
ReactOS 目前 不足：
能兼容的硬件和软件比较有限。
（系统稳定性，似乎已经够用了。）
另外，ReactOS团队审核完了所有源代码，已经完全确认了不包含任何从微软公司中泄露出的代码。
<ReactOS 的终极目标是能使你安装 ReactOS 来替代 Windows&reg; 而感觉不到最终端用户体验的变化。>

**Comment by zhsj** [comment]
duplicated with #8
