### ISSUE TITLE
[New] 申请添加 homebrew-cask-versions 源

### ISSUE THREAD

**Issue by steve3d** [ustclug/mirrorrequest#212]
源的上游地址如下：
https://github.com/Homebrew/homebrew-cask-versions

目前中科大的homebrew tap中已经有了homebrew-casks源， 但有些版本，例如著名的Java8/JDK8是不在homebrew-casks源中， 而是在homebrew-cask-versions中。

希望能够把这个源一与homebrew-casks源一并同步。

**Comment by cismous** [comment]
同申请添加

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/homebrew-cask-versions.git/

帮助也已添加：https://mirrors.ustc.edu.cn/help/homebrew-cask-versions.git.html
