### ISSUE TITLE
申请移除 PyPI 镜像

### ISSUE THREAD

**Issue by Smart-Hypercube** [ustclug/mirrorrequest#213]
PyPI 作为一个没有门槛、没有维护者制度、从来只进不出的仓库，却[占用着 USTC mirrors 最多磁盘空间](https://mirrors.ustc.edu.cn/status/)。它里面大多数代码质量远远比不上我们提供的其他镜像的价值，而且它本身也没有经过良好的设计，居然还有 #133 这种问题影响我们提供的服务质量。继续提供它是不合理的，不利于我们将有限的资源用在最有性价比的事情上。

（当然了，可以改成反代，设置一个容量上限，只缓存最常用的一部分包，用”常用程度“这个标准筛掉其中的垃圾仓库。）

**Comment by volltin** [comment]
https://servers.ustclug.org/2019/01/pypi-%E9%95%9C%E5%83%8F%E5%8F%98%E6%9B%B4%E9%80%9A%E7%9F%A5/

**Comment by frostming** [comment]
tuna的black包是坏的，然后想换用科大的源，发现你们又重定向到TUNA，但看到这些，支持你们的决定

**Comment by LucasD11** [comment]
LUG 会考虑类似 artifactory 这种三方的cache类型的代理工具吗，或者自己实现一个开源的 cache mirror，只缓存三个月内用过的package，超过三个月的就相当于是proxy，同时建立缓存。

**Comment by DukeWF** [comment]
我们用devpi做了一个缓存+反代，效果还不错。LUG这边有考虑过devpi吗

**Comment by skyzh** [comment]
@taoky 似乎在计划相关的工作（

**Comment by taoky** [comment]
> @taoky 似乎在计划相关的工作（

今年 OSPP 我准备搞一个通用的反代缓存的项目提案，过一段时间 proposal 应该就会放出来。我希望能够把 pypi, conda 以及其他可能很难全量同步的镜像都一起解决掉。

**Comment by cxwx** [comment]
> LUG 会考虑类似 artifactory 这种三方的cache类型的代理工具吗，或者自己实现一个开源的 cache mirror，只缓存三个月内用过的package，超过三个月的就相当于是proxy，同时建立缓存。

是3个月内更新过的package的意思？

**Comment by skyzh** [comment]
> > LUG 会考虑类似 artifactory 这种三方的cache类型的代理工具吗，或者自己实现一个开源的 cache mirror，只缓存三个月内用过的package，超过三个月的就相当于是proxy，同时建立缓存。
> 
> 
> 
> 是3个月内更新过的package的意思？
> 
> 

应该是三个月内有人下载过的 package？

**Comment by taoky** [comment]
Update: 基于新方案的 PyPI 镜像已经上线。
