### ISSUE TITLE
请增加homebrew的linuxbrew-core源

### ISSUE THREAD

**Issue by fcying** [ustclug/mirrorrequest#227]
请介绍新镜像
* 上游源（官方镜像）的地址
https://github.com/Homebrew/linuxbrew-core
* 该项目的介绍
homebrew的linux版本
* 为什么希望添加该镜像
现在已经有homebrew其他的镜像了, linuxbrew-core是刚合入Homebrew的

**Comment by zzh1996** [comment]
https://github.com/ustclug/mirrorrequest/issues/98

**Comment by fcying** [comment]
重复了啊. 关掉关掉
