### ISSUE TITLE
申请移除 Anaconda 镜像

### ISSUE THREAD

**Issue by Smart-Hypercube** [ustclug/mirrorrequest#228]
> 根据 Anaconda [软件源](https://repo.continuum.io/pkgs/)上的说明，Anaconda 和 Miniconda 是 Anaconda, Inc. 的商标，任何未经授权的公开镜像都是不允许的。

——TUNA [关于停止Anaconda镜像服务的通知](https://mirrors.tuna.tsinghua.edu.cn/news/close-anaconda-service/)

出于合规性考虑，申请移除 Anaconda 镜像。

mention #119

**Comment by hubutui** [comment]
可以考虑使用反代么？

**Comment by Smart-Hypercube** [comment]
由于 Anaconda 的软件源设计缺陷，其缺少正常发行版软件源所包含的签名校验功能，任何非官方网站提供的软件包都有可能被篡改过，产生安全隐患。因此我认为不应该鼓励公开的镜像或反代。

如果希望改善国内的 Anaconda 使用体验，可以建议他们官方改善网络质量，或者改善软件源设计，使其能安全地被镜像，再予以考虑。

**Comment by Smart-Hypercube** [comment]
已移除

**Comment by Jqdnrn** [comment]
现在镜像关了 怎么去升级这一些？
