### ISSUE TITLE
请求提供Cloudera(CDH)的镜像支持

### ISSUE THREAD

**Issue by anjia0532** [ustclug/mirrorrequest#229]
项目名称与简介(Project Intro.)
CDH是Hadoop一个十分重要的分支，是Cloudera公司维护的Hadoop发行版，在社区中名望很高。最重要的的是，CDH是有Linux发行版仓库的，无疑给部署带来了极大地便利。但是CDH官方镜像速度奇慢，国内这边连接经常超时，有些组件又很大，直接使用官方仓库苦不堪言，不亚于用S3仓库。希望tuna能镜像。

上游地址与镜像方法(How to Mirror)
直接同步官方的仓库即可: http://archive.cloudera.com/cdh5/ 这个主机也有https访问的方法
这是cdh6.2的获取方式

https://www.cloudera.com/documentation/enterprise/latest/topics/cm_ig_create_local_package_repo.html#internal_package_repo

ref https://github.com/tuna/issues/issues/551

**Comment by zhsj** [comment]
duplicated with #56
