### ISSUE TITLE
请求添加 googleapi 公钥的反向代理

### ISSUE THREAD

**Issue by wyudong** [ustclug/mirrorrequest#232]
## 上游源的地址

共两个：

- https://www.googleapis.com/oauth2/v1/certs
- https://www.googleapis.com/oauth2/v3/certs

## 该项目的介绍

以上两个链接是 [googleapi](https://developers.google.com/identity/sign-in/web/backend-auth) 验证签名的两个公钥地址。开发者在后端验证 Google 生成的 ID Token 时，需要用到某个公钥，但由于国内服务器无法访问，所以想问问看能否添加这两个公钥的反向代理。

官方文档说这两个公钥会定期 rotate，具体周期我也不清楚。只知道响应头里的缓存是这样：

```
cache-control: public, max-age=22114, must-revalidate, no-transform
```

**Comment by zhsj** [comment]
我们不是提供公共翻墙服务的机构。

**Comment by wyudong** [comment]
@zhsj 我没明白你的“公共翻墙服务”的意思，这里所有接受的镜像不都是由于国内网络访问困难而创建的吗？

我在 issues 里搜索 googleapis，结果也存在与 google 相关的镜像或反向代理，为什么那些申请是 accepted 的呢？愿闻其详。

**accepted:** #70 #205 
**needvote:** #216

**Comment by zhsj** [comment]
Go, helm, Flutter 至少是开源软件。

**Comment by wyudong** [comment]
@zhsj 公钥不是公开的吗

**Comment by iBug** [comment]
我们内部讨论认为，现有的对 googleapis.com 的反向代理已经带来了一些政策上的风险，因此我们目前不接受新的可能带来更多或其他风险的请求。
