### ISSUE TITLE
请增加ros2.0源

### ISSUE THREAD

**Issue by henjue** [ustclug/mirrorrequest#239]
请介绍新镜像
* 上游源（官方镜像）的地址
http://packages.ros.org/ros2/ubuntu
* 该项目的介绍
Robot Operating System 2.0
* 目前国内似乎还没有2.0的镜像。速度很慢甚至打不开(http://mirrors.ustc.edu.cn/ros/  已经有ROS的，但是没有ROS2)

**Comment by desstiony** [comment]
请增加

**Comment by bojieli** [comment]
ROS 2.0 是 ROS 1.0 的升级版，USTC mirrors 已经有 ROS 1.0 的镜像，ROS 2.0 的镜像大小估计在 10 GB 左右，不会占用很多硬盘空间。

ROS 2.0 的源站在国内访问很慢，目前国内仅有 TUNA 源有镜像，我们可以把 TUNA 作为上游来镜像，也可以直接从 ROS 2.0 源站镜像。

**Comment by WhenMelancholy** [comment]
ROS 2.0 的镜像已经同步完成，可以正常使用了
