### ISSUE TITLE
希望能够更新openwrt镜像

### ISSUE THREAD

**Issue by HgO-Ghost** [ustclug/mirrorrequest#24]
似乎从2.26起，，openwrt官方开始改革了，除了15.05新版镜像以外其他版本都用不了，特别是Barrier Breaker 14.07和Attitude Adjustment 12.09，，目前大多人用的都是这两个版本。。希望能修复下
BTW:我先贡献一个在2.27还能用的14.07镜像，希望中科大能暂时额外添加一下： http://ba.mirror.garr.it/mirrors/openwrt/barrier_breaker/14.07

**Comment by zhsj** [comment]
openwrt 官网是 15.05 之前的下载都指向了 http://old-releases.openwrt.org ，但是该网站无法访问，所以我们也无法镜像。
