### ISSUE TITLE
openwrt/lede 增加 snapshot 镜像

### ISSUE THREAD

**Issue by zuosc** [ustclug/mirrorrequest#241]
请介绍新镜像
* 上游源（官方镜像）的地址
https://downloads.openwrt.org

* 该项目的介绍
https://openwrt.org/zh/downloads

* 为什么希望添加该镜像
openwrt的源，看了下http://mirrors.ustc.edu.cn/lede/   ，只同步了OpenWrt 18.06.4和LEDE 17.01.6的源。
Snapshot download则没有同步。
是忽略了呢，还是故意没同步？
并且官网https://openwrt.org/zh/downloads 也没有ustc的列表。
希望都可以加上~

**Comment by jack9603301** [comment]
不建议一使用snap，可以使用flatpak

**Comment by Harry-Chen** [comment]
https://github.com/tuna/issues/issues/619

**Comment by Harry-Chen** [comment]
高校镜像站维护 snapshot 的意义并不大，使用者不多，但是同步代价很大。可以尝试腾讯的源： https://mirrors.cloud.tencent.com/openwrt/snapshots/targets/
