### ISSUE TITLE
希望增加 Microsoft 开源软件库的镜像

### ISSUE THREAD

**Issue by realJingYang** [ustclug/mirrorrequest#242]
* 上游源（官方镜像）的地址
  https://packages.microsoft.com/repos/
* 该项目的介绍
  微软的开源软件仓库
* 为什么希望添加该镜像
  官方站点速度慢且不支持ipv6

**Comment by cuihaoleo** [comment]
看起来顶级目录 https://packages.microsoft.com/ 还有一些其他内容？

另外没有 rsync 地址，同步会比较麻烦。

**Comment by TonySue2000** [comment]
求微软镜像+1，dotnet和VSCode动辄5,60MB，用着几十K的网速下是真的顶不住

**Comment by iBug** [comment]
Duplicate of #217
