### ISSUE TITLE
请求添加wasm_bindgen包镜像

### ISSUE THREAD

**Issue by XerxesSultan** [ustclug/mirrorrequest#244]
使用 Rust语言编写编译成 WebAssembly，官方有这个镜像，但是国内install太慢太慢了，希望能帮忙添加到你们的镜像仓库

**Comment by zhsj** [comment]
我不是很明白你希望镜像啥？

看文档，这是一个 rust 的包，rust 的包的话，我们有 http://mirrors.ustc.edu.cn/help/crates.io-index.html

**Comment by XerxesSultan** [comment]
不好意思哈，我没说清楚，我的意思是你们这个crates镜像中没有这个包



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhsj <notifications@github.com&gt;
发送时间: 2019年10月10日 16:04
收件人: ustclug/mirrorrequest <mirrorrequest@noreply.github.com&gt;
抄送: XerxesSultan <191818715@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ustclug/mirrorrequest] 请求添加wasm_bindgen包镜像 (#244)




我不是很明白你希望镜像啥？
 
看文档，这是一个 rust 的包，rust 的包的话，我们有 http://mirrors.ustc.edu.cn/help/crates.io-index.html

**Comment by XerxesSultan** [comment]
不好意思哈，我没说清楚，我的意思是你们这个crates镜像中没有这个包，
Updating `git://mirrors.ustc.edu.cn/crates.io-index` index
error: could not find `wasm_bindgen` in registry ，这是报错的信息

**Comment by taoky** [comment]
> 不好意思哈，我没说清楚，我的意思是你们这个crates镜像中没有这个包，
> Updating `git://mirrors.ustc.edu.cn/crates.io-index` index
> error: could not find `wasm_bindgen` in registry ，这是报错的信息

https://crates.io/crates/wasm-bindgen

看起来应该是 `wasm-bindgen`，而不是 `wasm_bindgen`。另外根据这份 tutorial，应该安装 `wasm-pack`（PS：我不是 Rust 用户）

**Comment by XerxesSultan** [comment]
好的，谢谢，我按照你说的再重新跑一下看看，我看的csdn的文章是cargo install wasm_bindgen，用的下划线，我试看看中横线
