### ISSUE TITLE
请增加GMT数据镜像

### ISSUE THREAD

**Issue by seisman** [ustclug/mirrorrequest#247]
* **官方主页:** https://www.generic-mapping-tools.org/
* **官方镜像地址:** https://oceania.generic-mapping-tools.org (此网页不可通过浏览器访问)
* **项目介绍:** GMT是一个开源（LGPLv3协议）的绘图软件，也是地球科学界最常用的制图软件。该软件首个正式版本发布于1988年，并一直维护至今。
* 为什么希望添加该镜像
  - USTC mirror 目前已经镜像了GMT的软件FTP服务器 (http://mirrors.ustc.edu.cn/gmt/) 。这里请求增加了是GMT的**数据服务器**，其中包含了地球科学最常用的地形起伏数据，未来会进一步增加其它地学数据。
  - 官方镜像位于夏威夷，国内下载速度慢
  - 镜像大小为50 GB左右，未来也基本不会超过 100 GB

**同步方式：**

`rsync -av --delete rsync://oceania.generic-mapping-tools.org/gmtdata gmtdata`

说明：

- GMT数据服务器中的 `cache` 目录是被GMT软件所使用的，因而也需要同步

**Comment by seisman** [comment]
Any updates on this issue?

**Comment by taoky** [comment]
在多处网络环境下测试，oceania.generic-mapping-tools.org 似乎都不允许使用 rsync 协议连接。同步方式是在近一年的时间里更新了吗？

**Comment by seisman** [comment]
我会跟上游确认之后再反馈给你。

**Comment by seisman** [comment]
@taoky 上游的问题已经解决了。请再试试

**Comment by taoky** [comment]
@seisman 嗯，上游可以用 rsync 连接到了，但是我还有一个问题是，GMT 数据的 license 是否允许进行镜像（重分发）？如果这一点没有问题的话，基于投票结果，会考虑加入镜像中。

**Comment by seisman** [comment]
我是 [GMT](https://github.com/GenericMappingTools/gmt) 的 [core developer](https://github.com/GenericMappingTools/gmt/blob/master/AUTHORS.md) 之一。GMT数据服务器中的数据没有License限制（这一点在GMT网站上没有提到。我们稍后会对网站做些修改以强调这一点）。

在 https://github.com/GenericMappingTools/gmtserver-admin/issues/18, https://github.com/GenericMappingTools/gmtserver-admin/issues/16, https://github.com/GenericMappingTools/gmtserver-admin/issues/15 中有分别讨论在北美、欧洲以及亚洲建立数据镜像。

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/gmtdata/

目前没有加 rsync，如果有需要的话可以再回复这个 issue。

**Comment by seisman** [comment]
> https://mirrors.ustc.edu.cn/gmtdata/

Thanks!

> 目前没有加 rsync。

请问这个具体是什么意思？是指USTC只镜像了这个数据，但没有每天同步吗？还是指USTC镜像会每天同步，但是其它人不能通过rsync的方式对USTC mirror 进行镜像。

**Comment by taoky** [comment]
> > https://mirrors.ustc.edu.cn/gmtdata/
> 
> Thanks!
> 
> > 目前没有加 rsync。
> 
> 请问这个具体是什么意思？是指USTC只镜像了这个数据，但没有每天同步吗？还是指USTC镜像会每天同步，但是其它人不能通过rsync的方式对USTC mirror 进行镜像。

是在 rsync://rsync.mirrors.ustc.edu.cn 里面没有加，当然如果需要的话，因为 gmtdata 看起来不大，也可以顺便加入。

**Comment by seisman** [comment]
谢谢回复。目前还没有rsync USTC mirror的需求。如果有需求的话，我会再申请。

**Comment by taoky** [comment]
@seisman 看起来上游 `rsync://oceania.generic-mapping-tools.org/gmtdata/` 的 rsync 又出问题了。

```
$ rsync rsync://oceania.generic-mapping-tools.org/gmtdata/
rsync: read error: Connection reset by peer (54)
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.2/rsync/io.c(604) [receiver=2.6.9]
```

mirrors 上截止到目前也有十天没有连接成功了。

**Comment by seisman** [comment]
多谢提醒，我会反馈到上游。

**Comment by seisman** [comment]
上游已修复，请确认是否正常。

**Comment by taoky** [comment]
> 上游已修复，请确认是否正常。

可以正常同步了。

**Comment by taoky** [comment]
@seisman Hi, 似乎 oceania.generic-mapping-tools.org 的 rsync 服务再次中断了。

```
$ rsync rsync://oceania.generic-mapping-tools.org
rsync: [Receiver] safe_read failed to read 1 bytes: Connection reset by peer (54)
rsync error: error in rsync protocol data stream (code 12) at io.c(276) [Receiver=3.2.3]
```

**Comment by seisman** [comment]
@taoky 请检查一下现在是否可以正常运行。

**Comment by taoky** [comment]
> @taoky 请检查一下现在是否可以正常运行。

可以了。

**Comment by taoky** [comment]
@seisman rsync://oceania.generic-mapping-tools.org not working again :-(

**Comment by seisman** [comment]
@taoky Thanks. I think it has been fixed now.
