### ISSUE TITLE
请求增加 mozilla-central

### ISSUE THREAD

**Issue by misaka00251** [ustclug/mirrorrequest#251]
* 项目地址：https://hg.mozilla.org/mozilla-central/
* mozilla-central 为 Mozilla Firefox 的开发分支。
* 在自己 Build 或开发 Firefox 时会使用到 mozilla-central，但下载速度十分缓慢，希望增加 :D

**Comment by taoky** [comment]
我正在本地测试 Mercurial (hg) 的同步，但是因为我平时不使用 Mercurial，有一些迷惑的地方：

1. 可以接受镜像站只将 `.hg` 作为静态文件 serve 吗？我在本地测试了一下，hg 能够 clone，但这样的话就不会有和 https://hg.mozilla.org/mozilla-central/ 类似的 web 界面。如果要部署出 web 界面的话可能会比较麻烦。
2. 如果使用单纯静态 serve 文件的方案，服务端 Mercurial 的版本可能会给客户端版本带来限制 (<https://www.mercurial-scm.org/wiki/MissingRequirement>)。一般来讲有需求使用本镜像（或者类似的使用 Mercurial 的代码仓库的镜像）的用户的 `hg` 版本会大于多少？
