### ISSUE TITLE
希望添加openSUSE ARM架构 源

### ISSUE THREAD

**Issue by ghost** [ustclug/mirrorrequest#254]
### 上游源地址
https://ftp.gwdg.de/pub/opensuse/ports/
### 这个源的简介

- openSUSE ARM架构 源

- 内含openSUSE的软件包，Rootfs和一些虚拟机镜像

### 添加源的原因
现在ARM架构也比较流行，添加该源方便用户更新，国外源速度过慢，无法正常使用

**Comment by taoky** [comment]
看起来官方就是有 aarch64 支持的：https://mirrors.ustc.edu.cn/opensuse/distribution/leap/15.6/repo/oss/aarch64/
