### ISSUE TITLE
请求增加Void Linux源

### ISSUE THREAD

**Issue by Asternmerr642** [ustclug/mirrorrequest#256]
* 上游源（官方镜像）的地址
https://alpha.de.repo.voidlinux.org/
* 该项目的介绍
Void是基于Linux内核独立开发的通用操作系统。其特色在于一份二进制/源代码混合式包管理系统，这使得用户能快速安装、更新、移除软件，或者是借助XBPS源代码集合从源码直接生成软件。该发行的其他特性包括对Raspberry Pi单板计算机（armv6和armv7）的支持，每日更新的滚动式开发模式，对OpenBSD旗下LibreSSL软件的集成，以及名为runit的原生init系统。 
* 为什么希望添加该镜像
因为Void Linux源不是很多（亚洲的只有新加坡源），而且更没有国内源（阿里云和网易和其他的都不提供Void源），另一个原因就是提升国内下载和访问速度

**Comment by gloit042** [comment]
与#73 重复，请前往那里投票
