### ISSUE TITLE
 希望能够建立AdoptOpenJDK各个版本的镜像

### ISSUE THREAD

**Issue by RobberPhex** [ustclug/mirrorrequest#257]
请介绍新镜像
* 上游源（官方镜像）的地址
  官网：<https://adoptopenjdk.net/>
  二进制存储库：
  - [Java8](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/)
  - [Java9](https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/)
  - [Java10](https://github.com/AdoptOpenJDK/openjdk10-binaries/releases/)
  - [Java11](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/)
  - [Java12](https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/)
  - [Java13](https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/)

  每个仓库的最新release下，有附件，就是各个平台的二进制包。
  希望能够镜像最新的release下的附件；如果空间允许，也请保留历史版本。

* 该项目的介绍
AdoptOpenJdk是一个社区版的 OpenJDK 二进制包，Java11后，Oracle修改了Oracle Jdk的授权，商业用途免费使用jdk只能转向社区，目前AdoptOpenJDK是比较有影响力的发行版。

* 为什么希望添加该镜像

AdoptOpenJdk托管在GitHub release上，国内访问速度十分感人，并且因为链接重定向至S3，很难下载。

**Comment by wlnirvana** [comment]
See https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/ and www.injdk.cn

**Comment by taoky** [comment]
考虑到 #291 也有人发 issue 说希望添加 AdoptOpenJDK，这个 issue 先 reopen 了。

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/github-release/AdoptOpenJDK/
