### ISSUE TITLE
请求增加 Rufus 镜像

### ISSUE THREAD

**Issue by myl7** [ustclug/mirrorrequest#259]
请介绍新镜像
* 上游源（官方镜像）的地址
* 该项目的介绍
* 为什么希望添加该镜像

Please tell more about your request
* Upstream URL
* Introduction of the project
* Why do you hope we add this mirror

Rufus 官方网站位于 <https://rufus.ie/>，官方的介绍是：

> Rufus is a utility that helps format and create bootable USB flash drives, such as USB keys/pendrives, memory sticks, etc.

该介绍大致意思是，Rufus 是一个帮助创建可启动的 USB 设备（启动盘）、完成 ISO 等文件的烧录的软件。

Rufus 可以用于烧录操作系统 ISO 文件到 U 盘，从而进行系统的安装。相比与其他软件，Rufus 更加轻量和迅速，这在官方网站上有说明及数据来源。目前，Rufus 官方网站上的下载链接速度过慢，无法使用。为 Rufus 提供镜像，可以方便普通用户安装系统，吸引更多人尝试新系统，包括 Linux 各发行版等。

Rufus 是开源软件，使用 GPL3 or later 发布，其源码位于 <https://github.com/pbatard/rufus>。

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/github-release/pbatard/rufus/
