### ISSUE TITLE
增加 Emacs 源码镜像

### ISSUE THREAD

**Issue by jiacai2050** [ustclug/mirrorrequest#263]
请介绍新镜像
* 上游源（官方镜像）的地址
  - git://git.savannah.gnu.org/emacs.git
* 该项目的介绍
  - Emacs is an extensible, customizable, free text editor and computing environment.
  - https://savannah.gnu.org/git/?group=emacs
* 为什么希望添加该镜像
  - 方便国内用户从源码编译 Emacs

**Comment by jiacai2050** [comment]
@iBug 票数多少才可以？

**Comment by cxwx** [comment]
git 源码的话，建议直接使用 gitee 先clone至国内，这样可以减少服务器负担

**Comment by cxwx** [comment]
不如，https://gitee.com/chenxuihep/emacs，可以手动直接同步

**Comment by jiacai2050** [comment]
@cxwx gitee 这个我知道，我只是觉得中科大这边最好是也能有个，这样用户就多一个选择（而且也能消除单点瓶颈）。

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/emacs.git/
