### ISSUE TITLE
is gcr.mirrors.ustc.edu.cn still available ?

### ISSUE THREAD

**Issue by dfang** [ustclug/mirrorrequest#267]
docker pull gcr.mirrors.ustc.edu.cn/google_containers/echoserver:1.4
Error response from daemon: received unexpected HTTP status: 504 Gateway Time-out

is gcr.mirrors.ustc.edu.cn still available?

**Comment by iBug** [comment]
Already covered in ustclug/discussions#309.

Also inappropriate place for this kind of report.
