### ISSUE TITLE
【镜像请求】Celadon project

### ISSUE THREAD

**Issue by jingdlu** [ustclug/mirrorrequest#269]
请介绍新镜像
* 上游源（官方镜像）的地址
https://github.com/projectceladon

* 该项目的介绍
Celadon is an open source Android* distribution fully optimized for IntelⓇ platforms. It modifies the Android* stack by incorporating critical technologies that allow users to run Android* applications in virtual machines and in containers.

* 为什么希望添加该镜像
国内很多Android x86开发者反映github下载速度很慢且不稳定，希望能提供国内镜像。

Please tell more about your request
* Upstream URL
* Introduction of the project
* Why do you hope we add this mirror

**Comment by cxwx** [comment]
没必要什么github项目都做mirrors吧，可以先使用gitee同步
