### ISSUE TITLE
[modify]请求修改rubyGems同步源

### ISSUE THREAD

**Issue by bubbleatgit** [ustclug/mirrorrequest#27]
**上游:**https://gems.ruby-china.org/
**原因:**由于ruby.taobao.org已经停止维护,很多gems包已经下载不到了.现在gems源有ruby-china来维护,请求修改gems为ruby-china的.

**Comment by gaoyifan** [comment]
我们换成ruby官方源怎么样？同步走隧道

**Comment by gaoyifan** [comment]
已切换为官方源

**Comment by bubbleatgit** [comment]
不好意思刚看到,感谢 @gaoyifan
