### ISSUE TITLE
新镜像 centos-vault

### ISSUE THREAD

**Issue by yyxfei** [ustclug/mirrorrequest#271]
请介绍新镜像
* 上游源（官方镜像）的地址
http://vault.centos.org/
* 该项目的介绍
centos老版本系统
* 为什么希望添加该镜像
经常需要老版本系统。
Please tell more about your request
* Upstream URL
* Introduction of the project
* Why do you hope we add this mirror

**Comment by zhsj** [comment]
根据 https://mirrors.tuna.tsinghua.edu.cn/status/ 显示，这个镜像有 4.15T

**Comment by cxwx** [comment]
centos 维护周期很长，如果是老版本的话几乎都是15年前的吧？

**Comment by vowstar** [comment]
起码IC行业很多EDA软件需要使用古老的CentOS

**Comment by yangzhaofeng** [comment]
好多國有研究單位也在使用舊的 centos，然後萬年不更新。但給爲他們開發的產品做測試還是需要下載yum源中的軟件包的

**Comment by daichenglong** [comment]
还有很多大学教学用的就是旧版rpm包

**Comment by xuyang2** [comment]
> 
> 
> 根据 https://mirrors.tuna.tsinghua.edu.cn/status/ 显示，这个镜像有 4.15T

4.15T应该是从 centos 2.1 到 6.10 的所有内容。
能否先只提供 6 系列或者 6.10 的 vault 镜像？

**Comment by daichenglong** [comment]
谢谢，但是6系列的镜像我用的不多所以我不知道大家都需求，但是7系列用的挺多的。


我建议先提供6到7系列的镜像，6以前的放个旧版链接应该可以。












代小龙
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月11日(周五) 下午2:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ustclug/mirrorrequest] 新镜像 centos-vault (#271)




  
根据 https://mirrors.tuna.tsinghua.edu.cn/status/ 显示，这个镜像有 4.15T
  
4.15T应该是从 centos 2.1 到 6.10 的所有内容。
 能否先只提供 6 系列或者 6.10 的 vault 镜像？

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/centos-vault/
