### ISSUE TITLE
救救AI掉包侠吧! Nvidia ngc 国内镜像

### ISSUE THREAD

**Issue by vegetable09** [ustclug/mirrorrequest#272]
请介绍新镜像

    **上游源（官方镜像）的地址**
    nvcr.io
    **该项目的介绍**
    Nvidia 容器镜像，包括业界最最最常用的TensorRT docker镜像https://ngc.nvidia.com/catalog/containers/nvidia:tritonserver, 部署深度学习时必不可少
    **为什么希望添加该镜像**
    趁美国还没对中国AI领域实施全面禁止, 赶紧同步过来吧!

Please tell more about your request

    Upstream URL
    nvcr.io
    Introduction of the project
    Nvidia's dockerhub, including the most popluar deployment tool: TensorRT https://ngc.nvidia.com/catalog/containers/nvidia:tritonserver
    Why do you hope we add this mirror
    Before America deny any AI corporation with China, save a dockerhub will help a lot to address the problem

**Comment by cuihaoleo** [comment]
Docker registry 没法获取所有镜像的 index，所以没办法镜像的，最多是做反向代理。

**Comment by vegetable09** [comment]
> 
> 
> Docker registry 没法获取所有镜像的 index，所以没办法镜像的，最多是做反向代理。

好的吧
