### ISSUE TITLE
Quantum Mobile

### ISSUE THREAD

**Issue by ltalirz** [ustclug/mirrorrequest#273]
### Official repository
Official releases: https://github.com/marvel-nccr/quantum-mobile/releases

Object store container: https://object.cscs.ch/v1/AUTH_b1d80408b3d340db9f03d373bbde5c1e/marvel-vms/
Example link: https://object.cscs.ch/v1/AUTH_b1d80408b3d340db9f03d373bbde5c1e/marvel-vms/quantum_mobile_20.06.1.ova

Mirror request for: Any files with name "quantum_mobile_*.ova" in the object store container, starting with the latest release (and later).

### Introduction of the project
[Quantum Mobile](http://materialscloud.org/quantum-mobile) is a virtual machine for computational materials science (based on Ubuntu Linux) that comes with a collection of software packages for quantum mechanical calculations, all of which are set up and ready to be used on their own or through the AiiDA python framework for automated workflows and provenance tracking.

### Why do you want we to add this mirror
We run regular [tutorials](https://aiida-tutorials.readthedocs.io/en/latest/) on the AiiDA framework that use Quantum Mobile, including a [tutorial in China in 2019](https://aiida-tutorials.readthedocs.io/en/latest/pages/2019_Xiamen/index.html) and a [virtual tutorial with participants from China in 2020](https://aiida-tutorials.readthedocs.io/en/latest/pages/2020_Intro_Week/index.html).
Since the Quantum Mobile images are hosted in Switzerland, download for participants can be excruciatingly slow (~10 KByte/s).

Over the last two years, according to our bit.ly download tracker, Quantum Mobile has been downloaded over 10'000 times, with a large fraction of downloads coming from China.

**Comment by taoky** [comment]
Hello, as this request has gathered enough "like" votes, I would like to add Quantum Mobile images to USTC mirrors. However, when configuring the sync, I find that there's no client supporting anonymous read from OpenStack Swift object storage. I tried with `rclone`, but it requires auth methods to be configured.

I'm not familiar with object storage clients and Swift, so I would like to know whether there exists a reliable syncing client to get contents anonymous from a public Swift storage container. In the worst case, I have to write a program parsing XML in https://object.cscs.ch/v1/AUTH_b1d80408b3d340db9f03d373bbde5c1e/marvel-vms/ by hand.

**Comment by ltalirz** [comment]
Hi @taoky , thanks for looking into this!

I'm not aware of a reliable synchronization client either, sorry (I had a quick look but didn't find anything).

OpenStack Swift has an API [1] that may help with selecting the files you want, e.g.
https://object.cscs.ch/v1/AUTH_b1d80408b3d340db9f03d373bbde5c1e/marvel-vms?prefix=quantum_mobile&marker=quantum_mobile_19

You can also use the `format` parameter to get e.g. json, in case that's easier to work with for you
https://object.cscs.ch/v1/AUTH_b1d80408b3d340db9f03d373bbde5c1e/marvel-vms?prefix=quantum_mobile&marker=quantum_mobile_19&format=json

[1] https://docs.openstack.org/api-ref/object-store/?expanded=show-container-details-and-list-objects-detail

**Comment by taoky** [comment]
After reading the docs of OpenStack Swift API and `rclone`, I find out that I can simply set an invalid `auth_token` (`X-Auth-Token`). As the container allows everyone to read, it seems that Swift won't check whether the token is valid.

An example `rclone.conf`:

```ini
[swift1]
type=swift
auth_token=test
storage_url=https://object.cscs.ch/v1/AUTH_b1d80408b3d340db9f03d373bbde5c1e
```

And then the files can be listed by:

```
$ rclone --filter '+ */?*' --filter '- */' ls swift1:marvel-vms
```

(Well it seems that `rclone` cannot handle the "directory" in container, so I have to set a strange filter to handle that)

**Comment by ltalirz** [comment]
Great, thanks for looking into this!

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/quantum-mobile-images/

Synced all "quantum_mobile_2*.ova" files.

**Comment by taoky** [comment]
@ltalirz Hi, is this project still maintained? I noticed that https://object.cscs.ch is no longer accessible.

**Comment by ltalirz** [comment]
Hi @taoky , fair question - let me forward it to @giovannipizzi

**Comment by eimrek** [comment]
hi! We have migrated the old https://object.cscs.ch/ object store to S3 located at https://rgw.cscs.ch.

I just made all of the files of the old `marvel-vms` bucket public at 

https://rgw.cscs.ch/matcloud:public-marvel-vms/

so e.g. 

https://rgw.cscs.ch/matcloud:public-marvel-vms/quantum_mobile_24.04.0.ova

**Comment by taoky** [comment]
> hi! We have migrated the old https://object.cscs.ch/ object store to S3 located at https://rgw.cscs.ch.

It looks like it does not support listing anonymously:

```console
$ curl 'https://rgw.cscs.ch/matcloud:public-marvel-vms/?list-type=2'
<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message></Message><BucketName>public-marvel-vms</BucketName><RequestId>tx000006b670aac4640d020-0068c07699-dca7c7c-naret-zone</RequestId><HostId>dca7c7c-naret-zone-cscs-zonegroup</HostId></Error>
```

**Comment by Bud-Macaulay** [comment]
Hopefully you can now list files, ive made the readpolicy public.
`
curl 'https://rgw.cscs.ch/matcloud:public-marvel-vms/?list-type=2' ` returns the raw xml of bucket

`curl -s 'https://rgw.cscs.ch/matcloud:public-marvel-vms/?list-type=2'   | sed 's/xmlns="[^"]*"//g'   | xmllint --xpath '//Key/text()' -   | tr ' ' '\n' ` returns a formatted list by filename (if you have xmllint installed)

**Comment by taoky** [comment]
Success with rclone:

```ini
[test]
type = s3
provider = Other
endpoint = https://rgw.cscs.ch/
```

```sh
rclone ls test:matcloud:public-marvel-vms
```

I would deploy this later.

**Comment by iBug** [comment]
As of our recent checkup, the repository `quantum-mobile-images` generated only 178.1 GB outbound HTTP traffic during the entire year of 2025 while occupying 144.1 GB of our disk space. Among these traffic, over 140 GB came from crawlers or other mirroring tools (e.g. bearing a User-Agent of `Nexus/3.43.0-01 (...)`).

As we've been running short of disk space for a long time, we have removed `quantum-mobile-images` from our mirror site today. We may consider reinstating it conditional on sufficient interest from real users in the future.
