### ISSUE TITLE
gitlab-ce mirror request

### ISSUE THREAD

**Issue by sysdl132** [ustclug/mirrorrequest#274]
请介绍新镜像(if you agree,give a thumb)

* 上游源（官方镜像）的地址/offical URL   [https://packages.gitlab.com/gitlab/gitlab-ce]
* 该项目的介绍/introduction   [gitlab community edition]
* 为什么希望添加该镜像/why    [TUNA had this mirror,why you don't]

**Comment by iBug** [comment]
TUNA 和北京外国语大学都有，加上最近 USTC 镜像站空间紧张，这个的优先级不会很高

**Comment by sysdl132** [comment]
Ok...close in 5...

**Comment by cxwx** [comment]
其实国内大学镜像站要么一起整合一下，每种源双备份，省的浪费空间网络资源。
