### ISSUE TITLE
[New] chromium os鏡像

### ISSUE THREAD

**Issue by james3141** [ustclug/mirrorrequest#28]
希望能增加chromium os鏡像

**Comment by james3141** [comment]
http://getchrome.eu/download.php links are as above

**Comment by zhsj** [comment]
http://getchrome.eu 提供的并不是 Chromium OS，只是其衍生物。

Chromium OS 和 AOSP 一样只提供源代码，源代码获取方式 http://dev.chromium.org/chromium-os/developer-guide#TOC-Get-the-Source

**Comment by zhsj** [comment]
http://getchrome.eu 提供的下载方式要么需要注册，要么是一个限制多多的网盘，无法很自由的获取。

Give vote for -1

**Comment by gaoyifan** [comment]
非常抱歉，我们目前不支持对网盘类资源提供镜像。
