### ISSUE TITLE
mirror for postmarket os

### ISSUE THREAD

**Issue by mainline-linux** [ustclug/mirrorrequest#281]
Please tell us more about your request

* Upstream or official repository URL: [pmos mirror](http://mirror.postmarketos.org/) [postmarket os website](http://postmarketos.org/)
* Introduction of the project: A project to port linux mobile os to existing android phones based on alpine linux
* Why do you want we to add this mirror: porting mainline linux kernel and postmarket os to existing android phones is a great opportunity to learn, and contribute to the project, meanwhile, there is no Chinese mirror for it, which makes it hard to build and sync the source

**Comment by Hinokami-Kagura** [comment]
该项目的介绍：將純正alpine Linux適配至現有的安卓手機。
为什么希望添加该镜像：據目前所知很多國內地區的用戶均報告國外源碼下載速度太慢，可以的話還請幫忙添加鏡像！

**Comment by sunflower2333** [comment]
It usually need to spend nearly 4 hours to waitting for the downloading progress to be done ....
That is too bad.....Wish for a mirror.

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/postmarketos/ 同步完成。
https://mirrors.ustc.edu.cn/postmarketos-images/ 正在初次同步中。

**Comment by taoky** [comment]
> https://mirrors.ustc.edu.cn/postmarketos-images/ 正在初次同步中。

同步完成。（postmarketos-images 未同步 `old` 以及以 `.` 开头的文件夹）
