### ISSUE TITLE
增加Vyos 软件仓库和ISO镜像

### ISSUE THREAD

**Issue by jack9603301** [ustclug/mirrorrequest#284]
## 上游源（官方镜像）的地址
DEB: http://dev.packages.vyos.net/
ISO: https://downloads.vyos.io/?dir=rolling/current/amd64
## 该项目的介绍
VyOS是基于Debian GNU / Linux的开源网络操作系统。

VyOS提供了一个免费的路由平台，可以与知名网络提供商的其他商业解决方案直接竞争。由于VyOS在标准的amd64，i586和ARM系统上运行，因此可以用作云部署的路由器和防火墙平台。

## 为什么希望添加该镜像

Vyos是一个欧洲的开源专业级通用软路由系统，但是如果需要人工编译时，往往会发现官方的deb路径网络传输相对较慢，因此希望建立中国的镜像站点。同时从官方下载ISO可能会比较慢，因此从国内下载ISO也许是更好地选择

## 国内其他镜像源同步情况
中国大陆无镜像站

**Comment by gaoyifan** [comment]
note: https://wiki.vyos.net/wiki/Mirrors

**Comment by taoky** [comment]
note: https://github.com/tuna/issues/issues/1094#issuecomment-751184593

**Comment by jack9603301** [comment]
https://dev.packages.vyos.net/

是否可以从如下地址镜像？

![图片](https://user-images.githubusercontent.com/9047180/103123417-3eb9e480-46bf-11eb-90fa-2d1e8b1c891c.png)

**Comment by jack9603301** [comment]
而ISO，可以考虑镜像rolling即可

**Comment by taoky** [comment]
> https://dev.packages.vyos.net/
> 
> 是否可以从如下地址镜像？
> 
> ![图片](https://user-images.githubusercontent.com/9047180/103123417-3eb9e480-46bf-11eb-90fa-2d1e8b1c891c.png)

这里的问题是，网页的 URL 的格式是 `https://dev.packages.vyos.net/?dir=<文件夹>`，而不是 `https://dev.packages.vyos.net/<文件夹>`。现有的 HTTP 同步程序没有办法正确处理这样的 URL。

**Comment by jack9603301** [comment]
好吧，这确实是问题

**Comment by jack9603301** [comment]
@taoky  是否有其他的办法呢？

**Comment by ZenithalHourlyRate** [comment]
首先要确认 VyOS 在 1.3 版本后是否可以再分发，比如与上游沟通

之后如果可以而且需要镜像，需要提供一个同步脚本，可以参考 https://github.com/tuna/tunasync-scripts 中的脚本

**Comment by jack9603301** [comment]
我去了解下，但是需要一点时间

**Comment by jack9603301** [comment]
官方表示可以镜像滚动版本的预编译ISO和所有软件包，但是不能镜像LTS的预编译镜像文件

> You can distribute rolling release images and any packages anywhere.
> You cannot distribute prebuilt LTS images, since it disincentivizes business users from supporting the project.

**Comment by jack9603301** [comment]
ISO:

https://downloads.vyos.io/rolling/current/amd64/vyos-rolling-latest.iso
https://downloads.vyos.io/rolling/current/amd64/vyos-rolling-latest.iso.sha256

**Comment by jack9603301** [comment]
@taoky 我发现将https://raw.githubusercontent.com/tuna/tunasync-scripts/master/apt-sync.py稍作修改后可以用于镜像vyos

**Comment by jack9603301** [comment]
https://github.com/tuna/tunasync-scripts/pull/110

可以参考这个

**Comment by taoky** [comment]
https://github.com/tuna/tunasync-scripts/pull/110#issuecomment-753364003

经过测试，直接用 https://github.com/ustclug/ustcmirror-images#aptsync 同步软件仓库是可以的。关于 ISO，目前我们没有可以只同步单个文件的同步脚本。我有计划写一个通用的 HTTP 同步程序，但是这一段时间估计无法完成。

**Comment by taoky** [comment]
> [tuna/tunasync-scripts#110 (comment)](https://github.com/tuna/tunasync-scripts/pull/110#issuecomment-753364003)
> 
> 经过测试，直接用 https://github.com/ustclug/ustcmirror-images#aptsync 同步软件仓库看起来是可以的。关于 ISO，目前我们没有可以只同步单个文件的同步脚本。我有计划写一个通用的 HTTP 同步程序，但是这一段时间估计无法完成。

计划这周末添加 Vyos 的 APT 软件仓库镜像测试。

**Comment by taoky** [comment]
> 计划这周末添加 Vyos 的 APT 软件仓库镜像测试。

https://mirrors.ustc.edu.cn/vyos/

仅同步了 https://dev.packages.vyos.net/?dir=repositories/current 下的内容。

**Comment by jack9603301** [comment]
可否使用vyos-build测试编译？我正在进行编译。测试不会马上进行

编译文档：docs.vyos.io

另外，`crux`的repo同步其实可以用来手动编译

**Comment by jack9603301** [comment]
![图片](https://user-images.githubusercontent.com/9047180/104099544-d3cff680-52d7-11eb-9491-7547b4956d64.png)

证书验证失败？

**Comment by jack9603301** [comment]
我现在尝试对这个源进行测试

**Comment by jack9603301** [comment]
![图片](https://user-images.githubusercontent.com/9047180/104102655-d54dee80-52d8-11eb-8f3c-c4241595e855.png)
为什么会这样

**Comment by jack9603301** [comment]
@taoky 这个镜像站同步时间是多少？

**Comment by iBug** [comment]
> ![图片](https://user-images.githubusercontent.com/9047180/104102655-d54dee80-52d8-11eb-8f3c-c4241595e855.png)
> 为什么会这样

应该是因为 [Let's Encrypt 换了新的根证书 CA][1] 导致旧的客户端（没有提前信任这个新的 Root CA 的）不接受新的 LE 证书。暂时使用 HTTP 可以绕过问题，不过能更新客户端或系统里的 `ca-certificates` 软件包会更好。

  [1]: https://letsencrypt.org/2020/09/17/new-root-and-intermediates.html

**Comment by taoky** [comment]
> @taoky 这个镜像站同步时间是多少？

目前设置的是每天 5:25 开始同步。

> 另外，`crux`的repo同步其实可以用来手动编译

由于上游目录结构的原因，加除了 current 以外的不太方便。

> 应该是因为 [Let's Encrypt 换了新的根证书 CA](https://letsencrypt.org/2020/09/17/new-root-and-intermediates.html) 导致旧的客户端（没有提前信任这个新的 Root CA 的）不接受新的 LE 证书。暂时使用 HTTP 可以绕过问题，不过能更新客户端或系统里的 `ca-certificates` 软件包会更好。

<https://letsencrypt.org/2020/12/21/extending-android-compatibility.html> 这一项更改推迟了。出现证书问题可能只是单纯 `ca-certificates` 没有安装。

**Comment by jack9603301** [comment]
> 由于上游目录结构的原因，加除了 current 以外的不太方便。

好的

**Comment by jack9603301** [comment]
> 由于上游目录结构的原因，加除了 current 以外的不太方便。

实际上确实可能是，因为每一次发行版，都会多出一个新的分支，比如vyos 1.3是`equuleus`，只有`current`是固定不变的，对于手动编译滚动版本的，只同步`current`确实足够

**Comment by jack9603301** [comment]
@taoky 测试构建正常，但是有个问题，我怀疑是源拉取跳过了一些实际发生改动的目录，导致现在散列不对（之前正常）

![图片](https://user-images.githubusercontent.com/9047180/104411515-7c66aa80-55a5-11eb-9164-80b988edc1c1.png)

似乎存在被弃用的软件包，每次拉取时，没有对原始目录进行删除？

`current`目录是滚动目录，因此随时可能发生变动

**Comment by taoky** [comment]
> @taoky 测试构建正常，但是有个问题，我怀疑是源拉取跳过了一些实际发生改动的目录，导致现在散列不对（之前正常）
> 
> ![图片](https://user-images.githubusercontent.com/9047180/104411515-7c66aa80-55a5-11eb-9164-80b988edc1c1.png)
> 
> 似乎存在被弃用的软件包，每次拉取时，没有对原始目录进行删除？
> 
> `current`目录是滚动目录，因此随时可能发生变动

所以，vyos 存在一些在包的内容更新时，包的版本号不会发生变化的包？在镜像站上 `vyatta-cfg-quagga_0.19.1+vyos2+current9_all.deb` 是在 1 月 4 日创建（最后更新）的，但是上游这个包在 1 月 11 日更新的。

**Comment by jack9603301** [comment]
是的，滚动包都是在jenkins的作用下，自动完成的编译，通常版本号不会随机更新，因此，您需要考虑对滚动更新分支的源执行特殊处理设置，如清空镜像repo目录

**Comment by jack9603301** [comment]
感谢您增加这个源这让我完全编译时间从几个小时到十几个小时，减少到1小时内

**Comment by jack9603301** [comment]
@taoky 您能处理下这个问题么？

**Comment by taoky** [comment]
现在同步程序换用了包装了 tuna 的 apt-sync.py 的容器，相比于原先增加的功能是会检查每个包的**大小**与上游目录文件是否一致。但是这里的情况是 `vyatta-cfg-quagga_0.19.1+vyos2+current9_all.deb` 这个包上游原地更新后的大小与原先一致，所以仍然不会选择同步新的版本。

由于每次同步都把整个仓库的所有文件扫一遍一般认为是耗时且会给磁盘 IO 带来压力的，所以一般来说同步程序不会检查已有的 checksum 是否一致。由于我们使用了 tuna 的同步脚本，我将与对应的同学讨论如何进行处理。另外，每次都先清空镜像再同步的方式不会考虑。

临时的可能有效的解决方案是将官方源加在最后面，如果从镜像站下载失败的话就从官方源下载（未测试）

**Comment by jack9603301** [comment]
@taoky 最简单的办法是在每次同步前，删除目标目录

**Comment by iBug** [comment]
出于磁盘 I/O 负载的考虑，

> 每次都先清空镜像再同步的方式不会考虑。

**Comment by jack9603301** [comment]
> 出于磁盘 I/O 负载的考虑，
> 
> > 每次都先清空镜像再同步的方式不会考虑。

好吧

**Comment by jack9603301** [comment]
@iBug @taoky 另一个办法是解析散列文件，如果该文件内容发生改变，则解析散列不同的文件，但这意味着，需要保存上次同步的文件散列

**Comment by taoky** [comment]
> @iBug @taoky 另一个办法是解析散列文件，如果该文件内容发生改变，则解析散列不同的文件，但这意味着，需要保存上次同步的文件散列

这是一个可以考虑的方案，有时间的话看看怎么实现。不过在实现之前，用官方源作 fallback 的方法从[这条回答](https://askubuntu.com/questions/587479/how-does-the-fallback-mechanism-of-apt-update-work-in-case-of-connection-problem#answer-587529:~:text=If%20multiple%20repositories%20provide%20the%20exact,choice%20and%20the%20others%20for%20fallback.)来看应该是可行的。

**Comment by jack9603301** [comment]
@taoky 谢谢

**Comment by jack9603301** [comment]
@taoky 
![图片](https://user-images.githubusercontent.com/9047180/104995814-d235c980-5a61-11eb-8ffe-2fc81251e4c1.png)

为什么出错了

**Comment by taoky** [comment]
> 为什么出错了

错误原因是上游的 [arm64](https://dev.packages.vyos.net/repositories/current/dists/current/main/binary-arm64/Packages) 和 [armhf](https://dev.packages.vyos.net/repositories/current/dists/current/main/binary-armhf/Packages) 架构的 Packages 列表中包含了包 `vyatta-op-quagga`，但是实际上这个包已经被删除，导致这两个架构同步提示错误。其他包的同步都是正常的，所以正常使用不会有影响。

如果需要让同步显示正常，请联系上游修复此问题。

**Comment by jack9603301** [comment]
> > 为什么出错了
> 
> 错误原因是上游的 [arm64](https://dev.packages.vyos.net/repositories/current/dists/current/main/binary-arm64/Packages) 和 [armhf](https://dev.packages.vyos.net/repositories/current/dists/current/main/binary-armhf/Packages) 架构的 Packages 列表中包含了包 `vyatta-op-quagga`，但是实际上这个包已经被删除，导致这两个架构同步提示错误。其他包的同步都是正常的，所以正常使用不会有影响。
> 
> 如果需要让同步显示正常，请联系上游修复此问题。

也就是说，除了其中一个包同步失败外，其他包正常？

即便这样，对同步程序来说，报告错误也许并不合理把？容易产生误导

**Comment by iBug** [comment]
> 也就是说，除了其中一个包同步失败外，其他包正常？
> 
> 即便这样，对同步程序来说，报告错误也许并不合理把？容易产生误导
> 
> 这是可以忽略的错误

同步程序只知道有一个包同步失败了，但是并不知道这个包是不是可以忽略的，所以只要有错误就返回失败状态是更合理的做法。

**Comment by jack9603301** [comment]
> > 也就是说，除了其中一个包同步失败外，其他包正常？
> > 即便这样，对同步程序来说，报告错误也许并不合理把？容易产生误导
> > 这是可以忽略的错误
> 
> 同步程序只知道有一个包同步失败了，但是并不知道这个包是不是可以忽略的，所以只要有错误就返回失败状态是更合理的做法。

好的，其他包同步是否正常？不会有可以同步的包因为报错而跳过了把？

**Comment by taoky** [comment]
> 好的，其他包同步是否正常？不会有可以同步的包因为报错而跳过了把？

下载某个包出错不会导致跳过其他软件包的下载。

**Comment by jack9603301** [comment]
> > 好的，其他包同步是否正常？不会有可以同步的包因为报错而跳过了把？
> 
> 下载某个包出错不会导致跳过其他软件包的下载。

好的，顺便问下，之前说的那个跳过下载最新包的问题是否解决了？

**Comment by taoky** [comment]
> 好的，顺便问下，之前说的那个跳过下载最新包的问题是否解决了？

我最近没有时间来写和测试这一块的代码，最早也要到下周周末才可能有空。如果感兴趣的话可以修改 [tunasync/apt-sync.py](https://github.com/tuna/tunasync-scripts/blob/master/apt-sync.py) 并且为 TUNA [提交 PR](https://github.com/tuna/tunasync-scripts/pulls)。如果能通过的话 [ustcmirror-images/apt-sync](https://github.com/ustclug/ustcmirror-images/tree/master/apt-sync) 也会及时更新。

**Comment by jack9603301** [comment]
> > 好的，顺便问下，之前说的那个跳过下载最新包的问题是否解决了？
> 
> 我最近没有时间来写和测试这一块的代码，最早也要到下周周末才可能有空。如果感兴趣的话可以修改 [tunasync/apt-sync.py](https://github.com/tuna/tunasync-scripts/blob/master/apt-sync.py) 并且为 TUNA [提交 PR](https://github.com/tuna/tunasync-scripts/pulls)。如果能通过的话 [ustcmirror-images/apt-sync](https://github.com/ustclug/ustcmirror-images/tree/master/apt-sync) 也会及时更新。

好的

**Comment by jack9603301** [comment]
@taoky 您好，我想请问那个功能改进的如何了？

**Comment by iBug** [comment]
> taoky 您好，我想请问那个功能改进的如何了？

我们最近在忙一些别的事情，并没有时间去研究改进这个功能。如果你感兴趣的话可以自己向 [TUNA 的同步脚本](https://github.com/tuna/tunasync-scripts/blob/master/apt-sync.py?rgh-link-date=2021-01-20T08%3A05%3A30Z)提交 PR，我们会跟进 TUNA 那边的更新的。

**Comment by jack9603301** [comment]
@iBug 如果完成改进了，就告诉我一声

**Comment by jack9603301** [comment]
@iBug 抱歉,这段时间一直没有关注这个问题,上次说的现在实现的怎么样了?如果需要我的帮忙,我有机会可以看看.

**Comment by iBug** [comment]
您好，由于此项目没有优先级，这段时间我们完全没动。

> 如果你感兴趣的话可以自己向 [TUNA 的同步脚本](https://github.com/tuna/tunasync-scripts/blob/master/apt-sync.py)提交 PR，我们会跟进 TUNA 那边的更新的。

**Comment by jack9603301** [comment]
see https://github.com/tuna/tunasync-scripts/pull/129

**Comment by taoky** [comment]
vyos 现在使用了新的同步工具 (https://github.com/ustclug/ustcmirror-images#tsumugu) 做同步，直接解析 HTML 判断是否下载文件。我不知道怎么测试，但是我相信部分包没有被同步的问题应该已经解决了，如果有问题再 open 这个 issue。

Status 页显示的 25 号错误原因是多余的文件超过了一次性删除的限制（1000），等它多同步几次慢慢删就行。

**Comment by jack9603301** [comment]
为什么我浏览器可以访问它？

**Comment by taoky** [comment]
> 为什么我浏览器可以访问它？

列目录是可以的，请点到目录下面任何一个文件看看能不能访问。

**Comment by jack9603301** [comment]
好吧，看起来确实无法访问，我明白了。我会在社区问一问，但如果不得不移除镜像，请将镜像移除或者将其设置为不可用

**Comment by jack9603301** [comment]
@taoky https://blog.vyos.io/community-contributors-userbase-and-lts-builds


Please cancel the image of the LTS branch, which can retain the rolling branch. According to the official information, the APT dependency of the LTS branch is set to be private, which means that it is impossible to obtain the LTS dependency image from the external network. Unless you build everything from the source code

**Comment by taoky** [comment]
> 请取消LTS分支的镜像，可以保留滚动分支，根据官方发布的信息，LTS分支的apt依赖被设置为私有，这意味着从外部网络获取LTS依赖镜像是不可能的。除非从源代码构建所有东西

哪个是 rolling 呢？crux 还是 current？请注意镜像站维护者中没有 vyos 的用户，所以如果可能请尽量表述清晰。

**Comment by jack9603301** [comment]
> > 请取消LTS分支的镜像，可以保留滚动分支，根据官方发布的信息，LTS分支的apt依赖被设置为私有，这意味着从外部网络获取LTS依赖镜像是不可能的。除非从源代码构建所有东西
> 
> 哪个是 rolling 呢？crux 还是 current？请注意镜像站维护者中没有 vyos 的用户，所以如果可能请尽量表述清晰。

The branch that is currently failing to synchronize may be the repository for private access, and the rolling version should be valid. I want to see it.

**Comment by iBug** [comment]
P.S. 如果您转载了上游社区的英文内容，请**不要**翻译：我们都看得懂英文，而翻译有时候是不准确地，只会给我们增加理解困难。

**Comment by taoky** [comment]
排除了返回 403 的内容。

**Comment by jack9603301** [comment]
> P.S. 如果您转载了上游社区的英文内容，请**不要**翻译：我们都看得懂英文，而翻译有时候是不准确地，只会给我们增加理解困难。

翻译不准确是因为你们没有正确的使用翻译系统，我作为跨境自由职业者，知道如何正确使用翻译以降低翻译错误的可能性。。另外，上面那是我不小心把中文翻译成英文了，而不是把上游的英文翻译成中文——习惯了，因为天天用翻译软件，上github不自觉的就翻译成英文了
