### ISSUE TITLE
请求添加Chaotic-AUR（Garuda Linux）镜像

### ISSUE THREAD

**Issue by KsRyY** [ustclug/mirrorrequest#287]
请介绍新镜像

* 上游源（官方镜像）的地址 `https://builds.garudalinux.org/repos/chaotic-aur/`
* 该项目的介绍： Automated building repo for AUR packages
* 为什么希望添加该镜像
Garuda Linux使用了部分该软件源的软件包，并且该软件源中有大量archlinuxcn未包括的软件，且它的多个服务器在国内下载速度都十分慢。
* 镜像方法: [Script](https://gist.github.com/BangL/86c2700e169994bc147ebf076fcb1888) （rsync）
镜像大小未知, 目测10~20GB

我在TUNA那里发过一个mirror request，但是他们认为这个源可能产生License问题（本源是部分AUR的二进制编译包）（[issue](https://github.com/tuna/issues/issues/1009#issuecomment-714321826)）所以把这个请求reject掉了，请问USTC是否可以接纳这个源，或者搭建一个反向代理以规避可能的版权问题

**Comment by iBug** [comment]
版权问题应该是所有镜像站 / 反代共有的，因此若 TUNA 那边有版权相关考虑，包括科大在内的国内高校镜像站都会持相同或相似的态度。

**Comment by KsRyY** [comment]
> 版权问题应该是所有镜像站 / 反代共有的，因此若 TUNA 那边有版权相关考虑，包括科大在内的国内高校镜像站都会持相同或相似的态度。

If reverse proxy have the same redistribution problem, then I would consider building up a mirror myself. Thanks for your support (I'm on a machine without a working input method so I can't type Chinese, sorry)

**Comment by iBug** [comment]
既然上游对版权问题持校级态度，我们也和 TUNA 一样暂时关闭关于这个源的 issue 了。

> I'm on a machine without a working input method so I can't type Chinese, sorry

It doesn't matter. Both Chinese and English are OK here.

**Comment by xiaty-win11** [comment]
这个能用吗？
https://developer.aliyun.com/mirror/garuda/

**Comment by iBug** [comment]
> 这个能用吗？ https://developer.aliyun.com/mirror/garuda/

终端用户也许可以使用阿里云镜像，但我们无法使用阿里云作为同步上游。
