### ISSUE TITLE
关于添加Oracle linux镜像的建议

### ISSUE THREAD

**Issue by QianYuChan** [ustclug/mirrorrequest#289]
* 上游源（官方镜像）的地址
*https://www.oracle.com/cn/storage/technologies/linux/downloads/default.html
* 该项目的介绍
* Oracle linux使用RHEL源码构建，具有和RHEL相似的稳定性。
* 为什么希望添加该镜像
* 方便大陆内用户使用Oracle linux。
* Oracle linux的适合服务器使用，是CentOS被停止之后的替代选择。

**Comment by zhsj** [comment]
dup #258

**Comment by zhsj** [comment]
duplicate of #258
