### ISSUE TITLE
AdoptOpenJDK 软件仓库和预编译和源码镜像

### ISSUE THREAD

**Issue by carbon-lab** [ustclug/mirrorrequest#291]
请介绍新镜像

* 上游源（官方镜像）的地址：https://adoptopenjdk.net 或者 https://github.com/AdoptOpenJDK

* 该项目的介绍
AdoptOpenJDK 是 OpenJDK 项目的预编译项目版本，该项目免费地提供了多个版本的 JDK 以及 JRE 的预编译项目，而且可以自行选择 JVM 的类型（HotSpot 或 OpenJ9），是非常流行的开源 OpenJDK “发行版”。

* 为什么希望添加该镜像
1、因为用的比较多；
2、官方地址下的有点慢。

Please tell us more about your request

* Upstream or official repository URL
* Introduction of the project
* Why do you want we to add this mirror

**Comment by taoky** [comment]
Duplicate of #257.
