### ISSUE TITLE
增加eclipse pde依赖插件镜像地址

### ISSUE THREAD

**Issue by mozhuanzuojing** [ustclug/mirrorrequest#293]
* 上游源（官方镜像）的地址： https://ftp.jaist.ac.jp/pub/eclipse
* eclipse.jdt.ls语言服务协议实现所依赖的仓库之一
* eclipse.jdt.ls是lsp协议的开源实现，现在vscode、eclipse che等市面上流行的编辑器的java插件都依赖于它。eclipse.jdt.ls开发环境依赖的插件有很多都来源于上述的镜像地址，但是镜像的网速一般只有16KB，每次更新依赖都要半天时间，特别影响效率。所以希望可以添加一个镜像源！

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/eclipse/ 不能使用吗？

**Comment by mozhuanzuojing** [comment]
感谢 @taoky  刚明白过来，这个问题可以关闭了
