### ISSUE TITLE
openEuler镜像源申请加入科大开源镜像站

### ISSUE THREAD

**Issue by zhang-jian-jun** [ustclug/mirrorrequest#295]
镜像名:
openEuler官方镜像源

上游源（官方镜像）的地址
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
秘钥信息: root:openeuler@1234 (只读账户)

镜像简介
科大开源镜像站点，你们好！
我们是来自于openEuler[ https://openeuler.org/zh/ ]开源操作系统社区的基础设施团队, openEuler旨在通过社区合作，打造创新平台，构建支持多处理架构、统一和开放的操作系统，推动软硬件应用生态繁荣发展。当前openEuler社区有自己的发布仓库[ https://repo.openeuler.org/ ]，想咨询下能否在你们的镜像源上面支持openEuler社区的镜像呢？多谢！

我们提供openEuler镜像同步指令如下:
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
秘钥信息: root:openeuler@1234 (只读账户)

openEuler社区基础设施团队
[1]: https://openeuler.org/zh/
[2]: https://repo.openeuler.org/

**Comment by zhsj** [comment]
@njulug fyi

**Comment by taoky** [comment]
您好，

首先必须纠正的是，我们维护是中国科学技术大学的开源镜像站（科大镜像站），不是南京大学开源镜像站。南大开源镜像站目前已有 [openEuler 的相关镜像](https://mirrors.nju.edu.cn/openeuler/)。

另一点是，openEuler 总计大小共有多大？我印象里在 TUNA 下线镜像之前 openEuler 占据了好几个 TB 的空间，但是目前从 <https://mirrorz.org/list/openeuler> 中 NJU 的数据显示仅有约 0.6TB。如果镜像较大的话，在较长的一段时间内我们可能无法为下游提供其 rsync 同步方式。

**Comment by zhang-jian-jun** [comment]
您好！
针对名称错误，首先表示抱歉，可能在查询网址的时候混淆了，非常抱歉！openEuler镜像多个版本总计：600G，openEuler镜像源非常希望能加入贵站点为下游提供镜像源，非常感谢！

**Comment by njulug** [comment]
你好。要加入南大开源镜像帮助站的话，写一份帮助文档发送到dns@njuer.org 格式参考https://nju-mirror-help.njuer.org/

https://nju-mirror-help.njuer.org/


------------------ 原始邮件 ------------------
发件人: zhangjianjun <notifications@github.com&gt;
发送时间: 2021年2月27日 19:00
收件人: ustclug/mirrorrequest <mirrorrequest@noreply.github.com&gt;
抄送: njulug <dns@njuer.org&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[ustclug/mirrorrequest] openEuler镜像源申请加入科大开源镜像站 (#295)





 
您好！
 针对名称错误，首先表示抱歉，可能在查询网址的时候混淆了，非常抱歉！openEuler镜像多个版本总计：600G，openEuler镜像源非常希望能加入贵站点为下游提供镜像源，非常感谢！

**Comment by zhang-jian-jun** [comment]
你好，非常感谢，并认可，我们会晶块完成帮助文档的上传

**Comment by zhang-jian-jun** [comment]
@njulug ，openEuler帮助文档已发送到dns@njuer.org，请查收，谢谢！

**Comment by njulug** [comment]
收到。你留个网名，网名会被列入贡献者名单。

nju-mirror-help.njuer.org 管理组






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhangjianjun"<notifications@github.com&gt;; 
发送时间: 2021年3月2日(星期二) 上午10:45
收件人: "ustclug/mirrorrequest"<mirrorrequest@noreply.github.com&gt;; 
抄送: "明"<dns@njuer.org&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ustclug/mirrorrequest] openEuler镜像源申请加入科大开源镜像站 (#295)





 
@njulug ，openEuler帮助文档已发送到dns@njuer.org，请查收，谢谢！
 
&mdash;

**Comment by zhang-jian-jun** [comment]
zhang-jian-jun

**Comment by njulug** [comment]
收到


nju-mirror-help.njuer.org/ 维护组




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhangjianjun"<notifications@github.com&gt;; 
发送时间: 2021年3月2日(星期二) 中午11:01
收件人: "ustclug/mirrorrequest"<mirrorrequest@noreply.github.com&gt;; 
抄送: "明"<dns@njuer.org&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ustclug/mirrorrequest] openEuler镜像源申请加入科大开源镜像站 (#295)





 
zhang-jian-jun
 
&mdash;

**Comment by zhang-jian-jun** [comment]
@njulug ，麻烦帮忙更新一下openEuler源帮助文档，已发送至邮箱，谢谢！

**Comment by njulug** [comment]
已更新&nbsp;https://nju-mirror-help.njuer.org

nju-mirror-help.njuer.org&nbsp; 维护组




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhangjianjun"<notifications@github.com&gt;; 
发送时间: 2021年3月3日(星期三) 下午4:59
收件人: "ustclug/mirrorrequest"<mirrorrequest@noreply.github.com&gt;; 
抄送: "明"<dns@njuer.org&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ustclug/mirrorrequest] openEuler镜像源申请加入科大开源镜像站 (#295)





 
@njulug ，麻烦帮忙更新一下openEuler源帮助文档，已发送至邮箱，谢谢！
 
&mdash;

**Comment by zhang-jian-jun** [comment]
好的，谢谢！

**Comment by ZhaoZuohong** [comment]
坐等

**Comment by zhang-jian-jun** [comment]
@njulug 咨询openEuler镜像源限制的下载带宽是多少kb？我们这边做一个统计信息，谢谢哈

**Comment by myl7** [comment]
> @njulug 咨询openEuler镜像源限制的下载带宽是多少kb？我们这边做一个统计信息，谢谢哈

由于此 repo 的 issue 作用是为 USTC Mirror 提出新镜像及新功能申请，如需与 NJU Mirror 作后续交流可以前往 https://github.com/njulug 另开 issue。

**Comment by zhang-jian-jun** [comment]
@myl7 谢谢哈

**Comment by njulug** [comment]
万兆。没有限制。南大开源镜像的机器本身和上联到信息中心都是万兆。刚向yaoge123问的。


https://nju-mirror-help.njuer.org/




------------------ 原始邮件 ------------------
发件人: zhangjianjun ***@***.***&gt;
发送时间: 2021年5月17日 15:29
收件人: mirrorrequest ***@***.***&gt;, dns ***@***.***&gt;, mention ***@***.***&gt;
主题: 回复：[ustclug/mirrorrequest] openEuler镜像源申请加入科大开源镜像站 (#295)






@njulug 咨询openEuler镜像源限制的下载带宽是多少kb？我们这边做一个统计信息，谢谢哈

**Comment by zhang-jian-jun** [comment]
好的，谢谢哈

**Comment by taoky** [comment]
Hi,

我和 @iBug 近期讨论了一下，目前的信息是：

1. 如果科大校内有足够多的 openEuler 用户的话镜像站会加入 openEuler。
2. 由于 rsync 服务器空间紧张，并且目前 IO 压力已经很大，年内没有为新的镜像加入 rsync 访问的计划。

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/openeuler/

根据学校老师的需要，我们添加了 openEuler 镜像。由于下午测试时发现 rsync://root@121.36.97.194 遇到了最大用户数限制，因此目前设置从 TUNA 同步。

Rsync 访问目前尚未配置。

**Comment by taoky** [comment]
Rsync 访问已加入。

**Comment by njulug** [comment]
邮件已收到~
