### ISSUE TITLE
移除 cloveros 镜像

### ISSUE THREAD

**Issue by taoky** [ustclug/mirrorrequest#297]
原因：

CloverOS 似乎已经不再维护：
- 上游的 rsync 同步近日已无法连接，<https://github.com/ustclug/mirrorrequest/issues/189> 中「上游」的 https 访问也出现了证书错误。
- [官网](https://cloveros.ga/)显示为空白页。

**Comment by zhsj** [comment]
https://cloveros.org/

**Comment by taoky** [comment]
> https://cloveros.org/

```
~
❯ rsync rsync://nl.cloveros.ga
^Crsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/rsync.c(244) [receiver=2.6.9]

~ took 53s
❯ rsync rsync://nl.cloveros.org
cloveros       	cloveros package server
```

有点离谱，他们换域名了，但是 <https://nl.cloveros.org/> 写的 rsync 站点还是：

```
Rsync: rsync://nl.cloveros.ga/cloveros
```

然后它的首页的 News 链接的 Twitter「账号已被冻结」，所以也不知道他们最近有什么变化。从 [Git 更新历史](https://gitgud.io/cloveros/cloveros)来看这几天还在更新，所以应该是不太活跃，但是还没有完全停止维护的状态？

**Comment by taoky** [comment]
> > https://cloveros.org/
> 
> ```
> ~
> ❯ rsync rsync://nl.cloveros.ga
> ^Crsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/rsync.c(244) [receiver=2.6.9]
> 
> ~ took 53s
> ❯ rsync rsync://nl.cloveros.org
> cloveros       	cloveros package server
> ```
> 
> 有点离谱，他们换域名了，但是 https://nl.cloveros.org/ 写的 rsync 站点还是：
> 
> ```
> Rsync: rsync://nl.cloveros.ga/cloveros
> ```
> 
> 然后它的首页的 News 链接的 Twitter「账号已被冻结」，所以也不知道他们最近有什么变化。从 [Git 更新历史](https://gitgud.io/cloveros/cloveros)来看这几天还在更新，所以应该是不太活跃，但是还没有完全停止维护的状态？

今天看了一下，虽然 `rsync rsync://nl.cloveros.org` 可以列出目录，但是里面的内容无法访问。

**Comment by taoky** [comment]
> > > https://cloveros.org/
> > 
> > 
> > ```
> > ~
> > ❯ rsync rsync://nl.cloveros.ga
> > ^Crsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/rsync.c(244) [receiver=2.6.9]
> > 
> > ~ took 53s
> > ❯ rsync rsync://nl.cloveros.org
> > cloveros       	cloveros package server
> > ```
> > 
> > 
> > 有点离谱，他们换域名了，但是 https://nl.cloveros.org/ 写的 rsync 站点还是：
> > ```
> > Rsync: rsync://nl.cloveros.ga/cloveros
> > ```
> > 
> > 
> > 然后它的首页的 News 链接的 Twitter「账号已被冻结」，所以也不知道他们最近有什么变化。从 [Git 更新历史](https://gitgud.io/cloveros/cloveros)来看这几天还在更新，所以应该是不太活跃，但是还没有完全停止维护的状态？
> 
> 今天看了一下，虽然 `rsync rsync://nl.cloveros.org` 可以列出目录，但是里面的内容无法访问。

nl.cloveros.org 的 rsync 服务目前可以正常访问，虽然仓库中还是没有任何文件被更新。

**Comment by taoky** [comment]
由于已经超过一年无法正常同步，且上游官网等均无法访问，已移除 cloveros。
