### ISSUE TITLE
[New] ROS ( Robot Operating System ) 源添加请求

### ISSUE THREAD

**Issue by xuhao1** [ustclug/mirrorrequest#3]
## ROS Intro
The Robot Operating System (ROS) is a flexible framework for writing robot software. It is a collection of tools, libraries, and conventions that aim to simplify the task of creating complex and robust robot behavior across a wide variety of robotic platforms.

ROS 是一套松散的机器人软件组织结构，十分流行于机器人领域。ROS是一套通信协议和一堆用于机器人的基础包。

@GaoYiFan在我们实验室已经做了ROS的rsync源，我提议mirrors添加ROS源并且在ROS主页上作为中国的源之一给出。

**Comment by hosiet** [comment]
已经添加
