### ISSUE TITLE
现在可以添加Rocky Linux镜像了

### ISSUE THREAD

**Issue by berlin2123** [ustclug/mirrorrequest#301]
上游源（官方镜像）的地址    https://dl.rockylinux.org/pub/rocky/

官网  https://rockylinux.org/

已有镜像列表：
https://mirrors.rockylinux.org/mirrormanager/mirrors/Rocky
添加进官方列表：
If you’re interested in mirroring Rocky Linux, we’ve set up Mirror Manager, please email infrastructure@rockylinux.org or drop a line in the ~Infrastructure channel on Mattermost..

重复issue 于 #288 ，仅为提醒，期待回复。

**Comment by iBug** [comment]
谢谢提醒，不过请不要重复开 issue，直接在原 issue 下回复即可，我们的同学都及时看到的。

**Comment by zhsj** [comment]
Duplicate of #288 （让 Github 标记为 duplicate issue）
