### ISSUE TITLE
AdoptOpenJDK 增加 deb 和 rpm 仓库

### ISSUE THREAD

**Issue by ZhaoZuohong** [ustclug/mirrorrequest#302]
在 github-releases 下已经有了 AdoptOpenJDK 的二进制文件，希望能添加它的 deb 和 rpm 镜像。
* deb 镜像： [https://adoptopenjdk.jfrog.io/artifactory/deb/](https://adoptopenjdk.jfrog.io/artifactory/deb/)
* rpm 镜像： [https://adoptopenjdk.jfrog.io/artifactory/rpm/](https://adoptopenjdk.jfrog.io/artifactory/rpm/)

**Comment by ksqsf** [comment]
Someone has to ask...为什么不用 Linux 发行版提供的 OpenJDK build？

**Comment by ZhaoZuohong** [comment]
> Someone has to ask...为什么不用 Linux 发行版提供的 OpenJDK build？

因为有Openj9呀！
Openj9与Hotspot相比，占用内存更少，启动更快。我以前开发Minecraft服务器插件时，需要频繁重启服务器进程，使用Openj9加了`-Xquickstart `之后，与Hotspot相比，启动时间缩短了一半！
现在我在容器中使用Openj9，内存占用明显比Hotspot少，启动也快很多，同样的内存，我就能开更多的实例。
当然Openj9缺点也不是没有，一是缺少ZGC或者Shenandoah GC这种GC算法，二是吞吐率不如Hotspot。不过Hotspot达到最高吞吐率要好长时间……
从二进制安装也不是不行，但是用AdoptOpenJDK提供的deb或者rpm源，安装起来很方便。

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/AdoptOpenJDK/
