### ISSUE TITLE
Raspbian Addons

### ISSUE THREAD

**Issue by hmsjy2017** [ustclug/mirrorrequest#307]
### 项目介绍 / Project Introduction
项目地址：https://github.com/raspbian-addons/raspbian-addons
Raspbian Addons 是 Raspbian 非官方软件源，含有许多来自 GitHub 的开源软件，可作为对 Raspbian（Debian） 官方仓库的一个补充。

### 上游地址及镜像方式 / Upstream location & mirror method
托管于 OSDN：https://osdn.net/projects/raspbian-addons/
镜像方式：https://osdn.net/projects/docs-en/wiki/DownloadMirrorsWanted
也可以在 tuna 或 bfsu 的基础上建立二级镜像

### 为什么希望添加该镜像 / Why do you want we to add this mirror

Raspbian Addons 是树莓派非官方 APT 仓库，含有许多来自 GitHub 的开源软件，兼容 armhf 和 arm64 架构，可作为对 Raspbian 官方仓库的一个补充（除树莓派外，其他 ARM 设备也可使用）。
### 其他信息 / Extra information

- 镜像容量（Mirror size）：< 10 GB
- 该镜像需求是否曾在之前的 issue 中提出过：没有

**Comment by taoky** [comment]
不会考虑镜像整个 OSDN，所以如果同步的话，可能和 manjaro-cd 一样，从 `rsync://ftp.iij.ad.jp/pub/osdn.jp/` 同步。

**Comment by hmsjy2017** [comment]
@taoky 请问是否考虑同步？

**Comment by taoky** [comment]
> @taoky 请问是否考虑同步？

正在初始同步中，需要一些时间。

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/raspbian-addons/

也欢迎 PR 提交相应的帮助到 <https://github.com/ustclug/mirrorhelp/>。
