### ISSUE TITLE
Chocolatey 镜像申请

### ISSUE THREAD

**Issue by carolyn-sun** [ustclug/mirrorrequest#308]
希望能够同步Chocolatey的镜像。目前，Chocolatey在国内似乎没有面向公众的完整镜像站点，大多为私人建立，不稳定也不够全面，而Chocolatey在Windows上又是相对比较重要的包管理体系。谢谢。

**Comment by skyzh** [comment]
参见 SJTUG 的讨论 https://github.com/sjtug/mirror-requests/issues/57

主要有两个问题：没有成熟的镜像方案，即便镜像也无法提升用户体验。

**Comment by hmsjy2017** [comment]
Chocolatey 的包并不是集中存储的，比如说用 Chocolatey 下载 Firefox 本质上还是从 Mozilla 官网下载，要镜像似乎只能反代。

**Comment by carolyn-sun** [comment]
原来如此。感谢回复。

**Comment by hmsjy2017** [comment]
![41679812-556F-4FB4-B062-8F72831494CF](https://user-images.githubusercontent.com/42692274/135849629-1875512f-0f2a-45e6-953e-2c30f7359f70.jpeg)
