### ISSUE TITLE
申请镜像 GHCup 及 Haskell 工具链

### ISSUE THREAD

**Issue by ksqsf** [ustclug/mirrorrequest#309]
虽然具体细节还没敲定，但是先记下来。

### 项目介绍 / Project Introduction

项目主页：https://www.haskell.org/ghcup/

GHCup 是目前 [Haskell](https://www.haskell.org) 社区推荐的安装方式。其工作方式类似于 [rustup](http://rustup.rs)（我们似乎曾经有过镜像），可以一站式管理整个 Haskell 的工具链，包括不同版本的 GHC（编译器）、HLS（语言服务器）、Cabal（构建工具）、Stack（另一个构建工具）。

### 上游地址及镜像方式 / Upstream location & mirror method

可能容易镜像的：

- GHCup：https://downloads.haskell.org/~ghcup/
- GHC：https://downloads.haskell.org/~ghc/
- Cabal：https://downloads.haskell.org/~cabal/

以下两个项目托管在 GitHub 上：

- HLS：https://github.com/haskell/haskell-language-server/releases/
- Stack：https://github.com/commercialhaskell/stack/releases/

具体镜像方式可能需要与上游协调。

### 为什么希望添加该镜像 / Why do you want we to add this mirror

加速！另外，我们已经有 [Hackage](http://mirrors.ustc.edu.cn/help/hackage.html) 和 [Stackage](http://mirrors.ustc.edu.cn/help/stackage.html) 镜像，从完整性角度考虑，没有工具链本体也有点奇怪。

### 其他信息 / Extra information

- 镜像容量（Mirror size）：尚未估计。
- 该镜像需求是否曾在之前的 issue 中提出过：无。

**Comment by ksqsf** [comment]
刚刚才发现 sjtug 已经有镜像了（https://github.com/sjtug/mirror-clone/tree/master/src/ghcup

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/ghcup/
