### ISSUE TITLE
请求加入ghcr.io的docker源

### ISSUE THREAD

**Issue by Luoxin** [ustclug/mirrorrequest#313]
### 项目介绍 / Project Introduction
GitHub Packages 是一种包托管服务，与 GitHub 完全集成。 GitHub Packages 将您的源代码和软件包组合在一起，以提供集成的权限管理和计费，使您能够在 GitHub 上专注于软件开发。

您可以将 GitHub Packages 与 GitHub API、GitHub Actions 以及 web 挂钩集成在一起，以创建端到端的 DevOps 工作流程，其中包括您的代码、CI 和部署解决方案。

GitHub Packages 为常用的包管理器提供不同的包注册表，例如 npm、RubyGems、Apache Maven、Gradle、Docker 和 Nuget。 GitHub 的 Container registry 针对容器进行了优化，支持 Docker 和 OCI 映像。

### 上游地址及镜像方式 / Upstream location & mirror method
> 预期希望加入docker部分的镜像
- 上游：ghcr.io
- 镜像方式：同docker的镜像方式

### 为什么希望添加该镜像 / Why do you want we to add this mirror
随着docker hub的价格政策的调整，有众多原本位于docker hub的image迁移至GitHub Packages，由于众所周知的原因，ghcr.io在国内是无法访问的

### 其他信息 / Extra information

- 镜像容量（Mirror size）：未知
- 该镜像需求是否曾在之前的 issue 中提出过：无

**Comment by taoky** [comment]
> 由于众所周知的原因，ghcr.io在国内是无法访问的

我印象里 ghcr.io 国内访问还蛮快的（不管是家宽还是教育网），不过这个是 homebrew 从 bintray 换到 ghcr 的时候我自己测试感觉的，现在情况如何没有测试。

**Comment by iBug** [comment]
我记得 Docker Hub 及类似的 container registry 由于技术原因无法全量镜像，只能反代，因此本 Issue 先关闭，讨论合并至 #276。
