### ISSUE TITLE
申请添加 intel oneapi 镜像

### ISSUE THREAD

**Issue by pentyum** [ustclug/mirrorrequest#314]
### 项目介绍 / Project Introduction
https://www.intel.cn/content/www/cn/zh/developer/tools/oneapi/overview.html#gs.hmvhui

### 上游地址及镜像方式 / Upstream location & mirror method
https://apt.repos.intel.com/oneapi
https://yum.repos.intel.com/oneapi
通过APT和YUM包管理器发布。

### 为什么希望添加该镜像 / Why do you want we to add this mirror
包含许多科学计算软件编译和运行的依赖，而intel官方源下载速度较慢。

### 其他信息 / Extra information

- 镜像容量（Mirror size）：大概几个G
- 该镜像需求是否曾在之前的 issue 中提出过：未提出过

**Comment by taoky** [comment]
1. Intel oneAPI 的 license 允许镜像站重分发吗？
2. <https://www.intel.cn/content/www/cn/zh/developer/tools/oneapi/overview.html#gs.hmvhui> 里面我没有找到 apt & yum 的相关配置，有更详细的文档吗？所给的 apt 和 yum 的链接都无法打开。

**Comment by pentyum** [comment]
> 1. Intel oneAPI 的 license 允许镜像站重分发吗？
> 2. https://www.intel.cn/content/www/cn/zh/developer/tools/oneapi/overview.html#gs.hmvhui 里面我没有找到 apt & yum 的相关配置，有更详细的文档吗？所给的 apt 和 yum 的链接都无法打开。

oneAPI的许可地址为https://cdrdv2.intel.com/v1/dl/getContent/686502?explicitVersion=true&wapkw=oneapi%20license
其中不同的软件许可不同，有一些软件基于Intel End User License Agreement for Developer Tools发布，该许可证只允许reproduce internally a reasonable number of copies of the Materials for Your personal or business use。关于分发的描述为：

> D. distribute (directly and through Your distributors, resellers, and other channel partners, if applicable),  the Redistributables, including any modifications to or Derivative Works of the Redistributables or any portions made pursuant to Section 2.1.C subject to the following conditions:
(1) Any distribution of the Redistributables must only be as part of Your Product which must add  significant primary functionality different than that of the Redistributables themselves;
(2) You must only distribute the Redistributables originally provided to You by Intel only in Executable Code subject to a license agreement that prohibits reverse engineering, decompiling or disassembling  the Redistributables;
(3) This distribution right includes a limited right to sublicense only the Intel copyrights in the  Redistributables and only to the extent necessary to perform, display, and distribute the  Redistributables (including Your modifications and Derivative Works of the Redistributables provided in Source Code) solely as incorporated in Your Product; and
(4) You: (i) will be solely responsible to Your customers for any update, support obligation or other obligation or liability which may arise from the distribution of Your Product, (ii) will not make any statement that Your Product is "certified" or that its performance is guaranteed by Intel or its suppliers, (iii) will not use Intel's or its suppliers' names or trademarks to market Your Product, (iv) will comply with any additional restrictions which are included in the text files with the Redistributables and in Section 3 below, (v) will indemnify, hold harmless, and defend Intel and its suppliers from and against any claims or lawsuits, costs, damages, and expenses, including attorney's fees, that arise or result from (a) Your modifications or Derivative Works of the Materials or (b) Your distribution of Your Product.

应该是不能做镜像的了。
