### ISSUE TITLE
gentoo-portage.git

### ISSUE THREAD

**Issue by taoky** [ustclug/mirrorrequest#316]
### 项目介绍 / Project Introduction

gentoo-portage 的 git 同步方式

### 上游地址及镜像方式 / Upstream location & mirror method

https://github.com/gentoo-mirror/gentoo.git

### 为什么希望添加该镜像 / Why do you want we to add this mirror

昨日同学反馈 gentoo-portage 的 rsync 同步速度较慢。短期内可以考虑加上 gentoo-portage git 方式的同步来缓解这个问题。

### 其他信息 / Extra information

- 镜像容量（Mirror size）：5.92 GB
- 该镜像需求是否曾在之前的 issue 中提出过：否

**Comment by WhenMelancholy** [comment]
已添加：https://mirrors.ustc.edu.cn/gentoo.git/
