### ISSUE TITLE
[Modify] rust-static: 更新toml 里的url指向本地

### ISSUE THREAD

**Issue by crlf0710** [ustclug/mirrorrequest#32]
hi, 经过配置rustup 更新rust时会从科大镜像上下载
https://mirrors.ustc.edu.cn/rust-static/channel-rust-*.toml.sha256
https://mirrors.ustc.edu.cn/rust-static/channel-rust-*.toml
并且根据里面的url从原始地址下载
可以修改相应的文件使他们从科大镜像下载么？谢谢！

**Comment by gaoyifan** [comment]
请参考[wiki](https://wiki.rust-china.org/multirust) 中“更新”一节：

> 更新时可以指定环境变量 RUSTUP_DIST_ROOT 从镜像下载，例如 export RUSTUP_DIST_ROOT=https://mirrors.ustc.edu.cn/rust-static 使用中科大镜像

**Comment by crlf0710** [comment]
Hi，请看下描述，我说的就是设置了RUSTUP_DIST_ROOT之后的情况。

**Comment by zhsj** [comment]
Anyone know about rustup?

**Comment by gaoyifan** [comment]
[这里](https://github.com/rust-lang/rustup/issues/53)似乎遇到了同样的问题

**Comment by zhsj** [comment]
Maybe we need upstream to fix.

**Comment by knight42** [comment]
给他们提了个 [PR](https://github.com/rust-lang-nursery/rustup.rs/pull/521).

另外现在 http://mirrors.ustc.edu.cn/rust-static 改为对 http://static.rust-lang.org 的反代

**Comment by knight42** [comment]
上游已经 merge 了。以后可以通过设置环境变量 RUSTUP_DIST_SERVER 为 https://mirrors.ustc.edu.cn/rust-static 来使用我们的反代
