### ISSUE TITLE
sifive的freedom-e-sdk镜像

### ISSUE THREAD

**Issue by ritian032** [ustclug/mirrorrequest#320]
### 项目介绍 / Project Introduction
sifive的riscvsdk
### 上游地址及镜像方式 / Upstream location & mirror method
https://github.com/sifive/freedom-e-sdk.git
### 为什么希望添加该镜像 / Why do you want we to add this mirror
想研究一下sifive的sdk，这个子太多仓库一直弄不下来
### 其他信息 / Extra information

- 镜像容量（Mirror size）：
- 该镜像需求是否曾在之前的 issue 中提出过：

**Comment by iBug** [comment]
仓库有较多的 git submodules，而镜像站的基础设施无法处理 git submodule，因此暂不考虑。

参考：<https://github.com/tuna/issues/issues/1140#issuecomment-913034750>
