### ISSUE TITLE
请求增加centos过期源

### ISSUE THREAD

**Issue by blue123123123** [ustclug/mirrorrequest#322]
请求增加centos过期源
参考地址：
https://mirrors.aliyun.com/centos-vault/
https://mirrors.tuna.tsinghua.edu.cn/centos-vault/

某些已经停止支持的centos系统可以在这里找到合适的软件包，，例如centos6

**Comment by iBug** [comment]
Duplicate of #271

**Comment by blue123123123** [comment]
centos过期源 是历史版本，停止支持版本的留存信息源。。。
在正常版本上源已经都删除了，，大家看下centos 6版本的正常源是不是都空了。。而valut全都保留着呢！！！

**Comment by taoky** [comment]
> centos过期源 是历史版本，停止支持版本的留存信息源。。。 在正常版本上源已经都删除了，，大家看下centos 6版本的正常源是不是都空了。。而valut全都保留着呢！！！

"Duplicate" 是「重复」的意思。
