### ISSUE TITLE
请求添加墨干编辑器源代码和安装包的镜像

### ISSUE THREAD

**Issue by darcy-shen** [ustclug/mirrorrequest#328]
### 项目介绍 / Project Introduction
墨干编辑器是[墨者实验室](https://gitee.com/XmacsLabs)旗下的结构化编辑器。目标是
> 让所有人畅快地学习既有的科学与技术，创造全新的科学与技术。

### 上游地址及镜像方式 / Upstream location & mirror method
https://github.com/XmacsLabs/mogan/releases

镜像方式：对github上正式版本的安装包和源代码做镜像。

### 为什么希望添加该镜像 / Why do you want we to add this mirror
在浙江余姚，尝试从Gitee/Github下载墨干编辑器安装包，均失败。正尝试从Github下载macOS安装包，预计需要一个小时（目前也已经失败）。

另外，Gitee提供的源代码下载也并不可靠：https://gitee.com/XmacsLabs/mogan/issues/I5D81Z

### 其他信息 / Extra information

- 镜像容量（Mirror size）：每次发布安装包大概200MB，源代码压缩包在50M以内。（目前有四次发布）
- 该镜像需求是否曾在之前的 issue 中提出过：否

**Comment by taoky** [comment]
> 刚刚发现这个mirrors失效了

很奇怪，脚本没搜索到 release:

```
syncing XmacsLabs/mogan to /data/XmacsLabs/mogan
Error: No release version found for XmacsLabs/mogan
deleting XmacsLabs/mogan/v1.1.6/mogan-v1.1.6-uos.deb
deleting XmacsLabs/mogan/v1.1.6/Mogan-v1.1.6-64bit-installer.exe
deleting XmacsLabs/mogan/v1.1.6/repo-snapshot.tar.gz
deleting XmacsLabs/mogan/v1.1.6/mogan-v1.1.6-ubuntu22.04.deb
deleting XmacsLabs/mogan/v1.1.6/Mogan_arm_v1.1.6.dmg
deleting XmacsLabs/mogan/v1.1.6/mogan-v1.1.6-ubuntu20.04.deb
deleting XmacsLabs/mogan/v1.1.6/mogan-v1.1.6-uos-loongarch64.deb
deleting XmacsLabs/mogan/v1.1.6/Mogan_v1.1.6.dmg
```

**Comment by taoky** [comment]
原因为 https://api.github.com/repos/XmacsLabs/mogan/releases 默认只会列出前 30 个 repo，但是 XmacsLabs/mogan 的前 30 个 release 都是 prerelease，因此脚本判断为没有非 release 可以下载。

**Comment by darcy-shen** [comment]
我删掉一些release吧，确实发preview版本太勤快了

**Comment by darcy-shen** [comment]
昨天删了很多release，但是tag没有删除。今天再删一波tag吧。

**Comment by taoky** [comment]
> 我删掉一些release吧，确实发preview版本太勤快了

看起来加 `?per_page=100` 在某些仓库会出问题，比如说 https://api.github.com/repos/adoptium/temurin11-binaries/releases?per_page=100:

```json
{
  "message": "Server Error"
}
```

只能暂时先退回了。

**Comment by da-liii** [comment]
https://api.github.com/repos/XmacsLabs/mogan/releases?per_page=100
这个接口没问题，但是 https://github.com/XmacsLabs/mogan/releases/tag/v1.2.8 没有被同步过去

**Comment by taoky** [comment]
> https://api.github.com/repos/XmacsLabs/mogan/releases?per_page=100 这个接口没问题，但是 https://github.com/XmacsLabs/mogan/releases/tag/v1.2.8 没有被同步过去

已修复。
