### ISSUE TITLE
[New] 希望能添加 Dash 托管的 docset 文档

### ISSUE THREAD

**Issue by wicast** [ustclug/mirrorrequest#33]
项目主页：https://kapeli.com/docset_links

Docset 是由 [Dash](https://kapeli.com/dash) 开发的离线API文档格式，docset 本身是开放格式，能被许多第三方软件兼容比如 [Zeal](https://zealdocs.org/)

**Comment by zhsj** [comment]
Sorry, I can't find a proper way to mirror and use the mirror in Zeal.
