### ISSUE TITLE
MinIO 镜像

### ISSUE THREAD

**Issue by heihei180** [ustclug/mirrorrequest#330]
### 项目介绍 / Project Introduction
Minio 是一个开源的分布式文件系统

### 上游地址及镜像方式 / Upstream location & mirror method
https://dl.min.io/server/minio/release/
### 为什么希望添加该镜像 / Why do you want we to add this mirror
直接访问MinIO官网下载速度特别慢.. 并且，再学习过程中，有存储大量文件的需要，hdfs不能很好的扩容，并不能满足需求。
### 其他信息 / Extra information

- 镜像容量（Mirror size）：
 实际大小 98MB
- 该镜像需求是否曾在之前的 issue 中提出过：
 搜索过issue，没有出现关键词 `minio`

**Comment by iBug** [comment]
镜像容量显然不止 98M，光[这一个文件夹][1]里的东西就几百 MB 了，并且一共 9 个文件夹加 archive 不知道总容量有多少，可能在几十到几百 GB 之间。

同时该网站没有看到 rsync 等良好的同步方式。


  [1]: https://dl.min.io/server/minio/release/linux-amd64/

**Comment by zhsj** [comment]
minio官方推荐的部署方式是用容器，镜像是quay.io/minio/minio。

**Comment by heihei180** [comment]
> 
   好的、谢谢、那我去用容器试试. : )
