### ISSUE TITLE
添加 Ubuntu Unity 镜像源

### ISSUE THREAD

**Issue by peasoft** [ustclug/mirrorrequest#331]
### 项目介绍 / Project Introduction
Ubuntu Unity is a remix of Ubuntu featuring the Unity7 desktop environment (the default desktop environment used by Ubuntu from 2010-2017).
Ubuntu Unity 是 Ubuntu 的混合版，具有 Unity7 桌面环境（Ubuntu 在 2010-2017 年使用的默认桌面环境）。

简而言之：Ubuntu Unity 能够让你在20.04甚至更高版本中继续以 Unity 桌面作为默认桌面环境。

### 上游地址及镜像方式 / Upstream location & mirror method
ISO (Http)：http://linux.darkpenguin.net/distros/ubuntu-unity/
torrent（Https）：https://fosstorrents.com/files/ISO文件名.torrent
（ISO文件名就是ISO源中的ISO文件名。如 http://linux.darkpenguin.net/distros/ubuntu-unity/20.04.4/ 中有文件 `ubuntu-unity-20.04.4.iso`，这个文件对应的种子就是 https://fosstorrents.com/files/ubuntu-unity-20.04.4.iso.torrent ，md5sum文件没有种子。）

### 为什么希望添加该镜像 / Why do you want we to add this mirror
Ubuntu Unity 作为一个**维持传统**的衍生版（尽管其没有在官网被展示，但是其已经被多数人所认可），其依然使用 Unity 桌面，对于老用户而言使用起来**更加方便，更容易上手**。另外，Unity桌面设计之初就是为了打造一个**简洁但不简单**，使用方便，**充分利用有限的屏幕尺寸**的桌面环境，使用起来效率比现在的Gnome桌面高得多。此项目对于**Ubuntu用户**和**Linux生态**依然有非常重要的意义。再加上，现在依然有许多用户在使用 Unity 桌面，甚至有些人（没错，我也在内）为此停留在了 Ubuntu 16.04，在这种情况下，Ubuntu Unity 对于我们来说依然非常重要。中科大镜像源作为国内较大的镜像源，加入 Ubuntu Unity 是有必要的。

简而言之：Ubuntu Unity 可以提高工作效率，并且其确实可以视作 Ubuntu 衍生版，应当加入。

### 其他信息 / Extra information

- 镜像容量（Mirror size）：
    - PC版（文件夹名为版本号）：20.5G
    - 树莓派版（raspberry-pi）：6G
    - Web版（ubuntu-web）：24.1G（纯浏览器的Live CD？真的有人用吗？这有必要同步吗？）
- 该镜像需求是否曾在之前的 issue 中提出过：是

**Comment by taoky** [comment]
Duplicate of https://github.com/ustclug/mirrorrequest/issues/315
