### ISSUE TITLE
请求新增homebrew/services

### ISSUE THREAD

**Issue by ttc0419** [ustclug/mirrorrequest#332]
### 项目介绍 / Project Introduction
一个homebrew管理后台软件启动/关闭的官方tap

### 上游地址及镜像方式 / Upstream location & mirror method
https://github.com/Homebrew/homebrew-services

### 为什么希望添加该镜像 / Why do you want we to add this mirror
当前该仓库在github，`brew update`更新相当缓慢，有时还会失败

### 其他信息 / Extra information
- 镜像容量（Mirror size）：724K (.git文件夹大小)
- 该镜像需求是否曾在之前的 issue 中提出过：未搜索到相关issue

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/help/homebrew-services.git.html

https://mirrors.ustc.edu.cn/homebrew-services.git
