### ISSUE TITLE
AlmaLinux

### ISSUE THREAD

**Issue by growuptime** [ustclug/mirrorrequest#334]
### 项目介绍 / Project Introduction

AlmaLinux：基于 Red Hat Enterprise Linux

### 上游地址及镜像方式 / Upstream location & mirror method

https://almalinux.org/

### 其他信息 / Extra information

- 镜像容量（Mirror size）：
- 该镜像需求是否曾在之前的 issue 中提出过：

**Comment by taoky** [comment]
Duplicate of https://github.com/ustclug/mirrorrequest/issues/333
