### ISSUE TITLE
openssl镜像请求

### ISSUE THREAD

**Issue by fengzhao** [ustclug/mirrorrequest#336]
### 项目介绍 / Project Introduction

OpenSSL 是一个开源项目，其组成主要包括一下三个组件：

- openssl：多用途的命令行工具
- libcrypto：加密算法库
- libssl：加密模块应用库，实现了ssl及tls

openssl可以实现秘钥证书管理、对称加密和非对称加密等，更多简介见官网。

### 上游地址及镜像方式 / Upstream location & mirror method

`
https://www.openssl.org/source/mirror.html

### 为什么希望添加该镜像 / Why do you want we to add this mirror

openssl做为linux操作系统必备的基础类库，国内访问下载较慢，且无高质量镜像，希望贵站加入镜像

### 其他信息 / Extra information

- 镜像容量（Mirror size）：
- 该镜像需求是否曾在之前的 issue 中提出过：

**Comment by iBug** [comment]
> openssl做为linux操作系统必备的基础类库，

因此各发行版均提供了 OpenSSL 库（`libssl`），且通过操作系统提供的包管理器可以获得对应软件包的源代码（如 [Ubuntu](https://packages.ubuntu.com/source/jammy/openssl) 和 [CentOS](https://git.centos.org/rpms/openssl/blob/c8/f/SOURCES)），额外添加此镜像的必要性暂不明确。

**Comment by fengzhao** [comment]
> > openssl做为linux操作系统必备的基础类库，
> 
> 因此各发行版均提供了 OpenSSL 库（`libssl`），且通过操作系统提供的包管理器可以获得对应软件包的源代码（如 [Ubuntu](https://packages.ubuntu.com/source/jammy/openssl) 和 [CentOS](https://git.centos.org/rpms/openssl/blob/c8/f/SOURCES)），额外添加此镜像的必要性暂不明确。

实际生产中，因为等保和信息安全，经常出现openssl漏洞问题，需要源码下载编译安装啊

**Comment by zhsj** [comment]
你这个自己编译安装的方式不管科不科学，

openssl源码一个版本也就14M，这个没啥镜像意义吧。。。另外github上也有源码。你可以用很多公开的git镜像服务来镜像github上的仓库。

**Comment by fengzhao** [comment]
> 你这个自己编译安装的方式不管科不科学

其实我认为是不科学的，但是现在国内各种政务云中，它们使用的也是国内外的各种Linux发行版，它们需要用国内的绿盟等安全公司扫描，探测到对应版本号，就去各种CVE漏洞库匹配，认为其有漏洞，发红头文件要求必须解决。包括MySQL等软件也是类似逻辑。其必要性和科学性都不是懂的人决策的。         而国内很多政务环境中，服务器既无互联网访问，也无内网镜像源。所以才希望ustc添加这个源的.  @iBug @zhsj

**Comment by iBug** [comment]
不管你自己编译安装的方式科不科学，重点是一个源码包才 10 MB 出头，又不是 apt/yum 软件包之类可以自动下载自动更新的东西，需要编译的时候就自己下载一份传到服务器上去编译就行了，没有镜像的意义。

而且，

> 服务器既无互联网访问

既然都这样了，有了公网镜像站也没用，还是得自己下载自己上传。

**Comment by billchenchina** [comment]
> 服务器既无互联网访问

是防火墙开了 ustc 镜像站的白名单吗？

**Comment by fengzhao** [comment]
> > 服务器既无互联网访问
> 
> 是防火墙开了 ustc 镜像站的白名单吗？

是的
