### ISSUE TITLE
Google APIs Fonts 反代

### ISSUE THREAD

**Issue by david-ajax** [ustclug/mirrorrequest#337]
### 项目介绍 / Project Introduction
Google APIs 提供的字体服务
### 上游地址及镜像方式 / Upstream location & mirror method
希望对 fonts.googleapis.com 采取反向代理
### 为什么希望添加该镜像 / Why do you want we to add this mirror
希望通过对 fonts.googleapis.com 的代理提升站点访问速度, 方便使用字体服务
### 其他信息 / Extra information
无
- 镜像容量（Mirror size）：不明(反向代理)
- 该镜像需求是否曾在之前的 issue 中提出过：未发现

**Comment by taoky** [comment]
参见 https://github.com/ustclug/discussions/issues/325#issuecomment-637319675
