### ISSUE TITLE
[New]希望添加Maven镜像

### ISSUE THREAD

**Issue by samuelts** [ustclug/mirrorrequest#34]
+ 上游URL: [https://repo1.maven.org/maven2/](https://repo1.maven.org/maven2/)
+ 介绍

> Apache Maven，是一个软件（特别是Java软件）项目管理及自动构建工具，由Apache软件基金会所提供。基于项目对象模型（缩写：POM）概念，Maven利用一个中央信息片断能管理一个项目的构建、报告和文档等步骤。
> Maven也可被用于构建和管理各种项目，例如C#，Ruby，Scala和其他语言编写的项目。Maven曾是Jakarta项目的子项目，现为由Apache软件基金会主持的独立Apache项目。
> Apache Maven Repo是Maven构建工具的包中央数据库。Maven Repo之于Java，如pypi之于python。

+ 申请理由

> 国内目前还没有一个稳定可用的Maven源，[oschina](http://www.oschina.net)曾提供过Maven源镜像，但目前镜像已不可访问。

**Comment by zhsj** [comment]
For reference,
Mirroring the entire Maven central repository is not allowed[1].

Should use a repository manager as a proxy. For example, Apache Archiva[2], JFrog Artifactory[3]. Both are written in Java.

[1] https://maven.apache.org/guides/mini/guide-mirror-settings.html
[2] https://archiva.apache.org/docs/2.2.0/quick-start.html
[3] https://www.jfrog.com/open-source/#os-arti

**Comment by zhsj** [comment]
Besides, we may can't mirror such a big repository since our bandwidth already reaches the [limitation](https://status.ustclug.org/graph_all_periods.php?hreg[]=mirrors&mreg[]=tx_bytes_%28vlan.%2A%7Ceth0%29&z=medium&gtype=line&vl=&title=Traffic+&glegend=show&aggregate=1&r=hour).

**Comment by samuelts** [comment]
@zhsj That's a pity but thanks anyway for your help.

**Comment by sadhen** [comment]
@zeng-xs maven的仓库用aliyun的就可以

**Comment by zhsj** [comment]
Another choice.

https://www.yidianzixun.com/article/0IcHQ9oG
https://mirrors.huaweicloud.com/repository/maven/
