### ISSUE TITLE
[镜像站] 请求新增 Eclipse Temurin (Adoptium) 的镜像

### ISSUE THREAD

**Issue by MSDNicrosoft** [ustclug/mirrorrequest#341]
## 理由：
- AdoptOpenJDK 已在 2021 年 7 月就过渡到 Adoptium [相关信息](https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/)
- AdoptOpenJDK 不提供 OpenJDK 17、18、19 的下载
- USTC 镜像站下 AdoptOpenJDK（<https://mirrors.ustc.edu.cn/AdoptOpenJDK/binary-adoptium/>）仅提供 Adoptium 17 版本的下载，无 8、11、16、18、19 版本
- ~如果转换到 Adoptium 还能少同步 3 个版本~（逃

## 建议
- 删除 AdoptOpenJDK 并转换到 Adoptium

## 其他信息
- Adoptium 官网 <https://adoptium.net>
- Adoptium API 文档 <https://api.adoptium.net/q/swagger-ui>
- 可同步的 Adoptium 版本：
 	- 8（非常建议同步，此版本很常用）
 	- 11（非常建议同步，此版本很常用）
 	- 16
 	- 17（非常建议同步，此版本很常用）
 	- 18（非常建议同步，此版本很常用）
 	- 19

**Comment by taoky** [comment]
在 https://mirrors.ustc.edu.cn/AdoptOpenJDK/binary-adoptium/ 同步了版本 8, 11, 17, 19（LTS 和目前最新的非 LTS）。目前还需要修改 apt 和 yum 的有关同步设置。

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/adoptium/

https://mirrors.ustc.edu.cn/AdoptOpenJDK 将择期删除。

**Comment by MSDNicrosoft** [comment]
> [mirrors.ustc.edu.cn/adoptium](https://mirrors.ustc.edu.cn/adoptium/)
> 
> [mirrors.ustc.edu.cn/AdoptOpenJDK](https://mirrors.ustc.edu.cn/AdoptOpenJDK) 将择期删除。

好的，感谢。
