### ISSUE TITLE
关于 FreeBSD-pkg 源转正的问题

### ISSUE THREAD

**Issue by njlyf2011** [ustclug/mirrorrequest#343]
几年前我建了一个镜像新增请求（[Issue 68](https://github.com/ustclug/mirrorrequest/issues/68)），就是希望贵校和 FreeBSD 那边能够有合作，建一个中国的官方镜像源。然后 2018 年的时候贵校 LUG 人士写了一个同步脚本，建立了非官方的 FreeBSD-pkg 源。

我觉得可能将这个源转正是会更好的，所以我发了一个邮件问了一下他们官方源的事情，他们的答复如下：

> Hi. An official FreeBSD mirror requires a (number of) physical machines under the control of the FreeBSD cluster administrators. Moreover, for the mirror to be useful, we require a lot of external bandwidth to keep it synchronised.
> We have not met any organisation that can satisfy both of these requirements.
> If you have a contact at a Mainland university, or another organisation, who can offer machines and external connectivity, please put us in touch.
> Many thanks.
> 
> Philip
> Philip Paeps
> Senior Reality Engineer
> Alternative Enterprises

大概就是提供一个物理空间，然后联系他们。
希望贵校可以考虑一下将 FreeBSD-pkg 源转正的事情？

**Comment by iBug** [comment]
FreeBSD 官方镜像要求他们有物理机的完全管理权限，这对我们来说是不可能的，因此在上游修改相关标准之前我们不会考虑加入官方镜像列表。
