### ISSUE TITLE
建议科大开源大神们建立MX Linux发行版APT源

### ISSUE THREAD

**Issue by maichaide** [ustclug/mirrorrequest#344]
https://mxlinux.org/
MX　Ｌｉｎｕｘ是目前全球排名第一的Ｌｉｎｕｘ发行版，基于Ｄｅｂｉａｎ但不像Ubuntu那样激进的修改，MX Linux增加了很多自有的提高用户使用体验的应用和桌面应用，省去了安装Debian后一大堆必须的设定和应用安装。MX Linux的安装程序和Live运行是最为灵活并且稳定的，这点之前只有Slackware才能做到。
### 上游地址及镜像方式 / Upstream location & mirror method
软件安装源在 /etc/apt/sources.list.d/文件夹中，而MX Linux独有的软件应用安装源则设置在mx.list文件中

# MX Community Main and Test Repos
deb http://mxrepo.com/mx/repo/ bullseye main non-free
#deb http://mxrepo.com/mx/testrepo/ bullseye test
#deb http://mxrepo.com/mx/repo/ bullseye ahs
debian-stable-updates.list
# Debian Stable Updates
deb http://deb.debian.org/debian/ bullseye-updates main contrib non-free
debian.list
# Debian Stable
deb http://deb.debian.org/debian bullseye main contrib non-free
deb http://security.debian.org/debian-security bullseye-security main contrib non-free
#deb-src http://deb.debian.org/debian bullseye main contrib non-free
#Stable backports
#deb http://deb.debian.org/debian bullseye-backports main contrib non-free
### 为什么希望添加该镜像 / Why do you want we to add this mirror
因为可以省去大量折腾时间，是普通桌面用户和专业用户都兼得的发行版
### 其他信息 / Extra information

- 镜像容量（Mirror size）：
- http://mxrepo.com/

- 该镜像需求是否曾在之前的 issue 中提出过：
无，首次提出

**Comment by zhsj** [comment]
Duplicate of #208
