### ISSUE TITLE
申请增加Circle Linux的镜像

### ISSUE THREAD

**Issue by euroford** [ustclug/mirrorrequest#347]
### 项目介绍 / Project Introduction
Circle Linux是由国人维护的红帽RHEL严格克隆版本，完全开源，完全免费，与上游版本bug级兼容，并保持全面的升级维护，完全可以替代原CentOS。
### 上游地址及镜像方式 / Upstream location & mirror method
https://mirror.cclinux.org/pub/circle/
rsync
### 为什么希望添加该镜像 / Why do you want we to add this mirror
Circle Linux可以完美解决CentOS停服之后，给原CentOS用户带来的各种困扰，继续提供上游的各种升级。
### 其他信息 / Extra information
Circle Linux目前的镜像服务器，包括国内各大互联网企业，北大、南大等教育机构，以及德国，比利时和新加坡等国家合作伙伴，在此诚挚邀请中国科学技术大学成为Circle Linux的镜像服务器。
https://koji.cclinux.org/ Circle Linux的构造服务器，完全开放；
https://git.cclinux.org/ Circle Linux的源代码配置服务器，也是完全开发的。

- 镜像容量（Mirror size）：
1.4T（截至到目前，包含8.3-8.7 and 9.0-9.1的每一个升级版本和升级包，建议预留更多，以保持持续性升级的存储空间）
- 该镜像需求是否曾在之前的 issue 中提出过：

**Comment by iBug** [comment]
由于类 RHEL 发行版数目众多、同质化严重，目前对于类 RHEL 发行版的镜像申请，除非校内用户有明确需要，否则不会考虑。

**Comment by euroford** [comment]
CentOS已经彻底停服，虽然RHEL的克隆众多，但建议首选由国人维护的Circle Linux，全球唯一一个由非美团队维护的RHEL克隆版本，建议增加。

**Comment by xiechangan123** [comment]
永远不要吝啬最大的恶意揣测国人的所谓开源系统。。。哈哈，我选rocky linux
