### ISSUE TITLE
请求新增TrueNAS！

### ISSUE THREAD

**Issue by AkarinLiu** [ustclug/mirrorrequest#349]
TrueNAS
### 项目介绍 / Project Introduction
TrueNAS is the World’s #1 Open Source Storage. Based on OpenZFS, it is trusted by millions and deployed worldwide.
### 上游地址及镜像方式 / Upstream location & mirror method
http://download.truenas.com/
### 为什么希望添加该镜像 / Why do you want we to add this mirror
它是一个存在了将近20年的项目，前身是FreeNAS，基于FreeBSD
### 其他信息 / Extra information

- 镜像容量（Mirror size）：<100G
- 该镜像需求是否曾在之前的 issue 中提出过：

**Comment by zhsj** [comment]
Duplicate of #319
