### ISSUE TITLE
[New]希望添加 VirtualBox 镜像源

### ISSUE THREAD

**Issue by wbsdty331** [ustclug/mirrorrequest#35]
老牌虚拟化软件，就不多说了
上游是`http://download.virtualbox.org/virtualbox/`

北理工的这个镜像(`http://mirror.bit.edu.cn/virtualbox/`)已经很长时间都没有进行同步了，已经向他们反馈过 但没有收到答复。

希望添加

**Comment by zhsj** [comment]
duplicated with #22
