### ISSUE TITLE
请求新增Jellyfin镜像！！

### ISSUE THREAD

**Issue by AkarinLiu** [ustclug/mirrorrequest#351]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/ustclug/mirrorrequest/issues) 中讨论过。  
I have checked that this repository has not been discussed in [other issues](https://github.com/ustclug/mirrorrequest/issues).

- [X] 我已仔细阅读 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/350)。  
I have CAREFULLY read the [mirroring rules](https://github.com/ustclug/mirrorrequest/issues/350).

### 项目介绍 (Project introduction)

Jellyfin是志愿者构建的媒体解决方案，可让您控制媒体。从您自己的服务器流式传输到任何设备，没有任何附加条件。您的媒体，您的服务器，您的方式。

## 上游地址
https://repo.jellyfin.org
## 镜像方法
HTTP

**Comment by taoky** [comment]
> ## 镜像方法
> 
> Rsync

哪里来的 rsync 呢？`rsync rsync://repo.jellyfin.org` 看起来不通。

**Comment by iBug** [comment]
根据 tuna/issues#909 的讨论和网上搜到的信息，Jellyfin 仓库没有 rsync，只有 HTTP 访问方式

**Comment by AkarinLiu** [comment]
这issue已经是两年半前了

**Comment by iBug** [comment]
@AkarinLiu 如果你确认该仓库可以 rsync 的话，能不能提供一下 rsync 地址？我们无法从你给出的 http 地址中获取 rsync 信息

**Comment by AkarinLiu** [comment]
仓库无法rsync
