### ISSUE TITLE
新增Zerotier镜像

### ISSUE THREAD

**Issue by AkarinLiu** [ustclug/mirrorrequest#352]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/ustclug/mirrorrequest/issues) 中讨论过。  
I have checked that this repository has not been discussed in [other issues](https://github.com/ustclug/mirrorrequest/issues).

- [X] 我已仔细阅读 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/350)。  
I have CAREFULLY read the [mirroring rules](https://github.com/ustclug/mirrorrequest/issues/350).

### 项目介绍 (Project introduction)

Zerotier是一个虚拟局域网组网软件

### 上游地址与镜像方法 (Upstream & mirroring method)

https://download.zerotier.com/
http拉取或rsync拉取

**Comment by iBug** [comment]
> http拉取或rsync拉取

你确定有 rsync 吗？

**Comment by AkarinLiu** [comment]
不敢确定，大概率没有

发自我的小米
在 iBug ***@***.***>，2023年1月28日 14:14写道：

http拉取或rsync拉取

你确定有 rsync 吗？

**Comment by iBug** [comment]
> sustech/nju 已有镜像，基本能满足日常使用与冗余需求

<https://github.com/tuna/issues/issues/1235#issuecomment-1193135895>

**Comment by iBug** [comment]
SUSTech 的镜像和文档都在：

- <https://mirrors.sustech.edu.cn/zerotier/>
- <https://mirrors.sustech.edu.cn/help/zerotier.html>

**Comment by iBug** [comment]
考虑到 TUNA 拒绝了镜像请求，目前稳定的镜像只有 NJU 一个，校内有同学使用，并且仓库容量不大（目前 37 GiB），我们已经加上了。

<https://mirrors.ustc.edu.cn/zerotier/>

**Comment by iBug** [comment]
如果有人愿意的话可以向 <https://github.com/ustclug/mirrorhelp> 贡献帮助。
