### ISSUE TITLE
Suggest increase the homebrew-cask-fonts image source,This library is relatively common.Thanks.

### ISSUE THREAD

**Issue by ljq** [ustclug/mirrorrequest#355]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/ustclug/mirrorrequest/issues) 中讨论过。  
I have checked that this repository has not been discussed in [other issues](https://github.com/ustclug/mirrorrequest/issues).

- [X] 我已仔细阅读 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/350)。  
I have CAREFULLY read the [mirroring rules](https://github.com/ustclug/mirrorrequest/issues/350).

### 项目介绍 (Project introduction)

Suggest increase the homebrew-cask-fonts image source, the source address: https://github.com/Homebrew/homebrew-cask-fonts.git.
This source code library is more commonly used for development and users.
Thanks.

### 上游地址与镜像方法 (Upstream & mirroring method)

https://github.com/Homebrew/homebrew-cask-fonts.git

### 镜像大小 (Mirror size)

40M

**Comment by taoky** [comment]
看了一下，仓库的 cask 总共有 2031 个，排除掉 url 来自 github.com 的还剩 308 个，不过思源黑体和思源宋体也在里面，虽然托管在 storage.googleapis.com 上但是似乎可以直连。

**Comment by taoky** [comment]
`These have mostly been migrated to [Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask)`
