### ISSUE TITLE
请求增加 netboot.xyz 镜像

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [ustclug/mirrorrequest#358]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/ustclug/mirrorrequest/issues) 中讨论过。  
I have checked that this repository has not been discussed in [other issues](https://github.com/ustclug/mirrorrequest/issues).

- [X] 我已仔细阅读 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/350)。  
I have CAREFULLY read the [mirroring rules](https://github.com/ustclug/mirrorrequest/issues/350).

### 项目介绍 (Project introduction)

netboot是一个用于网络启动在线操作系统的工具，但是它自身指向的地址几乎全部都未为中国做优化，导致体验极差。

### 上游地址与镜像方法 (Upstream & mirroring method)

用不着的上游地址：http://boot.netboot.xyz/ipxe/

镜像方法：

首先使用 github action 对源代码 fork 进行签出和自动同步，然后自动替换掉里面需要镜像的地址并编译，最后用 action 部署到 ustc mirror 服务器。

### 镜像大小 (Mirror size)

预估50MB左右

### 备注 (Note)

需要一点时间开发，但绝对值得，因为这个东西大大降低了装机成本，甚至可以换掉ustc校内的PXE。

**Comment by Mr-Ao-Dragon** [comment]
> 这完全不是镜像了啊，相当于整个重新部署一遍

没办法，官方没提供方便更换的方法，只能这样子。

**Comment by Mr-Ao-Dragon** [comment]
> > 这完全不是镜像了啊，相当于整个重新部署一遍
> 
> 没办法，官方没提供方便更换的方法，只能这样子。

我去给netboot提Issue吧

**Comment by zhsj** [comment]
pxe.ustc 更好啊，新版本是基于 grub 的，我认为更高级啊，而且支持 secure boot。

不过看了下 netboot 的文档，感觉 pxe.ustc 的文档确实有点年久失修了。

**Comment by taoky** [comment]
从目前的情况来看，即使 pxe.ustc 切换到 netboot.xyz 方案，也不会在镜像站上部署文件。

https://lug.ustc.edu.cn/wiki/lug/services/pxe/ 等文档做了一轮翻修，如果对我们提供的 PXE 服务有故障报告或是建议，欢迎在 https://github.com/ustclug/discussions/ 提出。
