### ISSUE TITLE
请求新增Docker Registry镜像！

### ISSUE THREAD

**Issue by AkarinLiu** [ustclug/mirrorrequest#361]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/ustclug/mirrorrequest/issues) 中讨论过。  
I have checked that this repository has not been discussed in [other issues](https://github.com/ustclug/mirrorrequest/issues).

- [X] 我已仔细阅读 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/350)。  
I have CAREFULLY read the [mirroring rules](https://github.com/ustclug/mirrorrequest/issues/350).

### 项目介绍 (Project introduction)

Docker Registry是在Docker Hub中的一个注册表

### 上游地址与镜像方法 (Upstream & mirroring method)

使用反向代理
目标地址：https://index.docker.io/v1

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/help/dockerhub.html

没有恢复的计划。

**Comment by Arnie97** [comment]
FYI：[南大今年设立了 Docker Registry 等镜像，可能是目前教育网内唯一对外开放的 OCI 容器镜像](https://sci.nju.edu.cn/9e/05/c30384a564741/page.htm)。

为了减小该站的压力，建议优先使用公有云厂商对内网开放的容器镜像。
