### ISSUE TITLE
请求添加 ImmortalWrt 镜像

### ISSUE THREAD

**Issue by 1715173329** [ustclug/mirrorrequest#365]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/ustclug/mirrorrequest/issues) 中讨论过。  
I have checked that this repository has not been discussed in [other issues](https://github.com/ustclug/mirrorrequest/issues).

- [X] 我已仔细阅读 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/350)。  
I have CAREFULLY read the [mirroring rules](https://github.com/ustclug/mirrorrequest/issues/350).

### 项目介绍 (Project introduction)

ImmortalWrt 是 OpenWrt 的一个第三方分支，主要针对国人用户开发，提供更多的本地化软件包和设备支持。

项目地址： https://github.com/immortalwrt

### 上游地址与镜像方法 (Upstream & mirroring method)

下载地址： https://downloads.immortalwrt.org

镜像方法：
```
env RSYNC_PASSWORD="immortalwrt-org" rsync -4ahv --delete-delay "rsync://firmwarepublic@rsync-mirror.infra.immortalwrt.org/firmware-public/" "immortalwrt/"
```

### 镜像大小 (Mirror size)

~930 GB

**Comment by nicholas-opensource** [comment]
强烈支持

**Comment by SuLingGG** [comment]
> 强烈支持

我也强烈支持！

**Comment by Accelerator6666** [comment]
很难不支持

**Comment by ksong008** [comment]
跟楼上各位大佬支持

**Comment by Kurokosama** [comment]
我啥也不懂，我就随声附和也支持吧！

**Comment by hecheng337** [comment]
**帮顶！**

**Comment by Louis-ui** [comment]
很难不支持

**Comment by Kasugano-Soraa** [comment]
> > 强烈支持
> 
> 
> 
> 我也强烈支持！
+1

**Comment by troubadour-hell** [comment]
+1

**Comment by bradfordzhang** [comment]
支持

**Comment by taoky** [comment]
**请不要再发送类似于「支持」「+1」这样没有实际内容的评论，否则这个 issue 可能会考虑锁定。**

**Comment by Fddh2012** [comment]
请支持的各位点亮issue主贴中的大拇指表情，谢谢。

**Comment by iBug** [comment]
<https://mirrors.ustc.edu.cn/immortalwrt/>

目前设置为每天 23:00 后同步一次，有后续问题可以继续回复。

特别感谢 @jlulug 和 @TechCiel 的帮助。

**Comment by 1715173329** [comment]
非常感谢！

**Comment by iBug** [comment]
> 我们目前不支持匿名登录，用户名与密码如上述分别为 `firmwarepublic` 和 `immortalwrt-org`。

您好，我们的配置文件中是指定了用户名和密码的，但是一些上游选择将用户名和密码保密，因此我们在公开的状态页面上是不显示任何仓库的密码或其他凭据的。

> 最近同步出现问题。

从[服务器状态页面](https://mirrors.ustc.edu.cn/status/)来看，同步失败的原因是 rsync 遇到了删除文件数量的限制。为了避免（我们或上游的）误操作导致整个删库的情况，我们默认配置一次同步最多删除 10,000 个文件。因此此类错误原因无需处理，等它多同步几次后即可自行解决。

**Comment by 1715173329** [comment]
好的，感谢您的快速回复。

**Comment by iBug** [comment]
从容量上考虑，我打算排除所有 rc 版本重定向到其他镜像站

```text
ncdu 1.18 ~ Use the arrow keys to navigate, press ? for help
--- /srv/repo/immortalwrt/releases -------------------------
   94.9 GiB [##################] /24.10.0-rc1
   91.7 GiB [################# ] /24.10.0-rc4
   91.6 GiB [################# ] /24.10.0-rc2
   91.6 GiB [################# ] /24.10.0-rc3
.  91.1 GiB [################# ] /packages-24.10
   80.0 GiB [###############   ] /23.05.4
   79.6 GiB [###############   ] /23.05.3
   78.7 GiB [##############    ] /23.05.2
   77.7 GiB [##############    ] /23.05.1
   77.7 GiB [##############    ] /23.05.0
   76.0 GiB [##############    ] /23.05.0-rc4
   74.0 GiB [##############    ] /packages-23.05
   67.4 GiB [############      ] /packages-21.02
   47.7 GiB [#########         ] /21.02.7
   47.6 GiB [#########         ] /21.02.6
   47.2 GiB [########          ] /21.02.5
   47.1 GiB [########          ] /21.02.0
   46.8 GiB [########          ] /21.02.4
   46.0 GiB [########          ] /21.02.3
   45.6 GiB [########          ] /21.02.1
    8.2 MiB [                  ] /faillogs-24.10
.   3.7 MiB [                  ] /24.10.0
    1.7 MiB [                  ] /faillogs-23.05
  636.0 KiB [                  ] /faillogs-21.02
```

**Comment by 1715173329** [comment]
我们会在 stable release 发布一段时间（通常为一月）后主动将 rc 版本移动到 archive.immortalwrt.org，应该不需要主动干预，也可以在同步的时候直接排除掉 rc 版本。
（23.05.0-rc4 的发布时间比较特别所以仍然保留在主库中）

**Comment by iBug** [comment]
> 主动将 rc 版本移动到 archive\[...\]

这个很好，那我就不着急了，非常感谢

**Comment by iBug** [comment]
@1715173329 请问 ImmortalWrt 是否考虑[像 OpenWrt 一样](https://openwrt.org/mirrors#space_requirements)划分 current 和 archived releases？考虑到旧的 release 用户量很少，镜像站希望排除旧版本以提高磁盘空间利用率。

**Comment by 1715173329** [comment]
> 划分 current 和 archived releases

我确实有这个想法，但是很抱歉目前没有时间去做这件事（已成为打工人）。
如果有进展的话，会在这个 issue 下回复。

**Comment by 1715173329** [comment]
`rsync://firmwarepublic@rsync-mirror.infra.immortalwrt.org/releases-mirror-default/`

目前 ImmortalWrt 已经添加新的 `releases-mirror-default` 模块，只包含 active releases。密码依然为 `immortalwrt-org`。

**Comment by iBug** [comment]
感谢，我们已经把 rsync 上游模块切换至 `releases-mirror-default`。
