### ISSUE TITLE
petalinux

### ISSUE THREAD

**Issue by Freed-Wu** [ustclug/mirrorrequest#367]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/ustclug/mirrorrequest/issues) 中讨论过。  
I have checked that this repository has not been discussed in [other issues](https://github.com/ustclug/mirrorrequest/issues).

- [X] 我已仔细阅读 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/350)。  
I have CAREFULLY read the [mirroring rules](https://github.com/ustclug/mirrorrequest/issues/350).

### 项目介绍 (Project introduction)

petalinux is a linux distribution developed by AMD Xilinx which used for embedded development on their board. It supports three CPU archs: arm, aarch64 and microblaze.

### 上游地址与镜像方法 (Upstream & mirroring method)

<https://petalinux.xilinx.com/>

**Comment by iBug** [comment]
`Petalinux_EULA.txt` from the installer indicates that:

> "Distributable Component(s)" means those files supplied by Xilinx that are contained within the Software and that are identified by Xilinx in such tool or its associated documentation as **either (a) an IP core (or a LogiCORE product)**, which is designed for use in programming functionality onto a Xilinx Device (hereafter a "Core"), **or (b) a software driver (or a device driver)**, which is designed for use in enabling a Xilinx Device to interoperate with other independent software programs such as an operating system as well as middleware, board support package (BSP) or other application software (collectively hereafter a "Driver").

> Except only to the extent otherwise expressly allowed under Section 3 (License Grants) above (or under applicable laws notwithstanding these restrictions), Licensee is not licensed to, and agrees not to:
>
> (iv) make any copies of the Software, except to make one (1) copy of the Software in machine-readable form solely for backup purposes

I'm drawing the conclusion that this software cannot be mirrored.

**Comment by Freed-Wu** [comment]
Petalinux_EULA.txt should be the LICENSE of `petalinux-build`, `petalinux-config`, ... and all programs to create an embedded linux distribution on AMD Xilinx board. The files of <https://petalinux.xilinx.com> are just rpm package files for users to `dnf install` in their created embedded linux distribution. It should be different from `petalinux-XXX`. I [ask this problem in their forum](https://support.xilinx.com/s/question/0D54U00006wE0IPSA0/can-httpspetalinuxxilinxcom-be-allowed-to-mirror-by-some-chinese-universities-software-mirror-website-to-fasten-chinese-users-access) but get no response.
