### ISSUE TITLE
移除 julia 镜像

### ISSUE THREAD

**Issue by iBug** [ustclug/mirrorrequest#368]
julia 仓库在 5 月份请求数 66k，总流量 117 GB，其中科大校内 3.1k / 5.3 GB（47 个独立来源 IP），但是占用硬盘容量 4.50 TB，是目前容量最大的仓库。

考虑到总硬盘占用量已超过 93%，我们计划在有需要的时候移除 julia 镜像，并重定向至南京大学或北京大学。

Related: tuna/issues#1677

**Comment by taoky** [comment]
在四月底的时候我看了一下镜像大小的统计，Julia 目前大致以每 2 个月 0.5T 的速度增大。之后即使不移除，或者移除后再恢复，也不会再去做完整的镜像，有可能也会采取类似于缓存的方式。在这种情况下，作为 [juliacn Pkgserver 的后端](https://discourse.juliacn.com/t/topic/2969)可能就不合适。

说到底原因还是，镜像站的存储不是 scalable 的。

**Comment by johnnychen94** [comment]
非常能够理解；实际上我在同元内部做的 Julia 镜像也是以 反代+缓存 形式做的，Julia 社区的观点是存储不要钱可以无限 scale，所以和镜像站的模式相冲突。
如果能够接受反代形式的镜像，我也可以准备一套比较易用和可靠的工具。

**Comment by iBug** [comment]
@johnnychen94 非常感谢您的理解，如果有现成的、方便易用的反代+缓存模式的工具的话，我们以后也许会考虑部署一套。

结合 julia 镜像的用户量，我们会在近期移除目前的全量镜像，毕竟镜像站的一个目标是通过有限的资源服务尽可能多的用户。

**Comment by RTXUX** [comment]
由于磁盘空间紧张，Julia 镜像已移除。
