### ISSUE TITLE
[New] Android SDK

### ISSUE THREAD

**Issue by nopyhe** [ustclug/mirrorrequest#37]
* 上游URL： https://dl.google.com/android
* 介绍： Android SDK
* 申请理由： Android SDK 是  Android 开发必备的，难以下载给 Android 新手带来非常大的困扰，虽然国内有几个镜像，但是速度、稳定性都不理想。

希望能够提供 Android SDK 的镜像或反代。

**Comment by hosiet** [comment]
tuna/tunasync#4

**Comment by gaoyifan** [comment]
我们做一个反代怎么样？

**Comment by zhsj** [comment]
$ dig dl.google.com @114.114.114.114 +short
dl.l.google.com.
203.208.43.72
203.208.43.64
203.208.43.78
203.208.43.67
203.208.43.70
203.208.43.73
203.208.43.66
203.208.43.68
203.208.43.65
203.208.43.71
203.208.43.69

dl.google.com 有国内 ip
