### ISSUE TITLE
添加openwrt-archive

### ISSUE THREAD

**Issue by Spz2022** [ustclug/mirrorrequest#371]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/ustclug/mirrorrequest/issues) 中讨论过。  
I have checked that this repository has not been discussed in [other issues](https://github.com/ustclug/mirrorrequest/issues).

- [X] 我已仔细阅读 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/350)。  
I have CAREFULLY read the [mirroring rules](https://github.com/ustclug/mirrorrequest/issues/350).

### 项目介绍 (Project introduction)

应该与openwrt一样

### 上游地址与镜像方法 (Upstream & mirroring method)

https://archive.openwrt.org/

**Comment by Spz2022** [comment]
不清楚该不该关掉。

**Comment by iBug** [comment]
archive 类仓库通常容量巨大且只增不减，在镜像站上利用率低下，目前我们不打算新增此类仓库（已有 ubuntu old releases 和 centos vault）
