### ISSUE TITLE
mirror Devuan packages

### ISSUE THREAD

**Issue by yjqg6666** [ustclug/mirrorrequest#373]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/ustclug/mirrorrequest/issues) 中讨论过。  
I have checked that this repository has not been discussed in [other issues](https://github.com/ustclug/mirrorrequest/issues).

- [X] 我已仔细阅读 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/350)。  
I have CAREFULLY read the [mirroring rules](https://github.com/ustclug/mirrorrequest/issues/350).

### 项目介绍 (Project introduction)

Devuan GNU+Linux is a [fork of Debian without systemd](https://www.devuan.org/os/announce/) that allows users to reclaim control over their system by avoiding unnecessary entanglements and ensuring [Init Freedom](https://www.devuan.org/os/init-freedom).

Homepage: [https://www.devuan.org/](https://www.devuan.org/)

### 上游地址与镜像方法 (Upstream & mirroring method)

https://www.devuan.org/os/packages
镜像方法应该跟Debian类似

**Comment by taoky** [comment]
Duplicated with https://github.com/ustclug/mirrorrequest/issues/93.
