### ISSUE TITLE
请求增加TuraBlockchain镜像

### ISSUE THREAD

**Issue by nybbs2003** [ustclug/mirrorrequest#379]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/ustclug/mirrorrequest/issues) 中讨论过。  
I have checked that this repository has not been discussed in [other issues](https://github.com/ustclug/mirrorrequest/issues).

- [X] 我已仔细阅读 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/350)。  
I have CAREFULLY read the [mirroring rules](https://github.com/ustclug/mirrorrequest/issues/350).

### 项目介绍 (Project introduction)

香港，2023年10月30日，Chainwire

经过一年多的秘密开发，Tura区块链在新加坡的Token 2049大会上震惊了整个区块链社区。这标志着Tura的公开首次亮相，其创新的方法解决了区块链生态系统中的可扩展性挑战，使与会者充满了期待。

区块链技术在追求可扩展性的过程中一直遇到持续的障碍，像比特币和以太坊这样的平台随着其网络的扩张而难以跟上。这个问题违背了通过资源增强来实现可扩展性的现实逻辑，例如扩建高速公路或电力网。然而，Tura区块链作为一种先驱性的解决方案，能够实现外扩（scaling out）而不是第一代区块链采用的传统的内扩（scale-up）方法。

Tura大胆的声明的核心是其能够线性扩展的独特能力，没有每秒交易数量的上限。这得益于其分布式EVM的实现，该EVM不仅支持大规模的去中心化应用程序（dApps）而且还具有人工智能功能。此外，Tura的SQL开发框架起到了桥梁的作用，促使传统开发者融入Web 3生态系统。

Tura的挖矿机制因其独特性而受到了显著关注。用户只需分配50GB的笔记本电脑存储空间，并抵押10,000个Tura代币（约合40美元，按照Hotcoin Global的估值），就可以参与挖矿。这种机制似乎受到了Proof of Capacity模型的启发，并结合了抵押原则。

对挖矿的强调源于一种信念，即去中心化的共识机制在被允许自然发展时效果最好。Tura的独特挖矿方法旨在提供推动健壮生态系统所需的有机动力，而不是一开始就创建所有代币并可能通过激励措施影响其采用。观察者们急切地等待Tura实现其路线图中概述的里程碑。

Token 2049上围绕Tura区块链的激动人心的气氛突显出对创新解决方案的期待，这些解决方案可以解决区块链行业面临的紧迫挑战。凭借其对可扩展和增强人工智能的dApps的承诺，Tura有望对区块链技术的未来产生重大影响。

### 关于Tura区块链

Tura区块链利用Layer 0的并行计算来实现前所未有的线性可扩展性，而不牺牲安全性或去中心化。Tura旨在彻底改变区块链生态系统。

更多信息，请访问 https://tura.world/

### 关于Token 2049

Token 2049是全球领先的加密货币活动之一，汇聚了行业专家、区块链爱好者和思想领袖，探讨区块链和加密货币领域的最新趋势和创新。

更多信息，请访问 https://www.token2049.com

### 上游地址与镜像方法 (Upstream & mirroring method)

[click here](https://packagecloud.io/nybbs2003/tura/mirror#apt)

### 备注 (Note)
[软件源码](https://github.com/TuraBlockchain/pearletj)
[软件源码](https://github.com/TuraBlockchain/tura-miner-daemon)
_No response_

**Comment by nybbs2003** [comment]
[软件源码](https://github.com/TuraBlockchain/pearletj)

**Comment by taoky** [comment]
这里不是打广告的地方。从代码仓库的观察看，也不存在广泛的使用群体。
