### ISSUE TITLE
[New] yum.dockerproject.org

### ISSUE THREAD

**Issue by fenglc** [ustclug/mirrorrequest#38]
- 官方镜像地址：
  https://yum.dockerproject.org/
- 该项目的介绍：
  [Docker](http://www.docker.com/) 是一个开源的容器管理器。
  项目官方网站：https://dockerproject.org/
  CentOS 官方安装示例：https://docs.docker.com/engine/installation/linux/centos/#install-with-yum
  _注意：_ 该镜像仅适用于 RPM / DNF 包管理工具，适用于 APT 的镜像 USTC [已提供](http://mirrors.ustc.edu.cn/apt.dockerproject.org/)。
- 为什么希望添加该镜像：
  国内访问缓慢。

**Comment by gaoyifan** [comment]
http://mirrors.ustc.edu.cn/docker/yum/
