### ISSUE TITLE
mirrors上的adoptium镜像没有binary-i386架构

### ISSUE THREAD

**Issue by TurnOffNOD** [ustclug/mirrorrequest#384]
### 问题描述 / Bug description

mirrors上的adoptium仓库，`apt update`的时候有404的提示，经过检查`https://mirrors.ustc.edu.cn/adoptium/deb/dists/bookworm/main/`，并且与官方源`https://packages.adoptium.net/ui/native/deb/dists/bookworm/main/`对比，发现其缺少binary-i386和其它一些架构的仓库。

既然上游官方源还没有取消i386的支持，最好还是一起镜像下来吧。还有个binary-all也是类似。

**Comment by iBug** [comment]
翻了一遍 issue，并不清楚一开始为什么在同步配置里限制了 arch = `amd64 armhf arm64`。

**Comment by taoky** [comment]
> 翻了一遍 issue，并不清楚一开始为什么在同步配置里限制了 arch = `amd64 armhf arm64`。

可能只是写配置的时候单纯没写，或者是把 i386 当成 deprecated 的架构来看了。

**Comment by TurnOffNOD** [comment]
现在还是没有 :grey_question:

**Comment by taoky** [comment]
> 现在还是没有 ❔

看了一下几个 dist，i386 没有实际意义的二进制包，只有两个看起来没啥用的 all 架构的包。因为看起来很小所以顺便加上了。

**Comment by taoky** [comment]
> 翻了一遍 issue，并不清楚一开始为什么在同步配置里限制了 arch = `amd64 armhf arm64`。

大概是因为是从 https://github.com/tuna/tunasync-scripts/blob/master/adoptium.py 拿的配置

**Comment by taoky** [comment]
同步已完成。
