### ISSUE TITLE
nixpkgs.git

### ISSUE THREAD

**Issue by Freed-Wu** [ustclug/mirrorrequest#385]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/ustclug/mirrorrequest/issues) 中讨论过。  
I have checked that this repository has not been discussed in [other issues](https://github.com/ustclug/mirrorrequest/issues).

- [X] 我已仔细阅读 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/350)。  
I have CAREFULLY read the [mirroring rules](https://github.com/ustclug/mirrorrequest/issues/350).

### 项目介绍 (Project introduction)

> Nixpkgs is a collection of over 60,000 software packages that can be installed with the Nix package manager. It also implements NixOS, a purely-functional Linux distribution.

### 上游地址与镜像方法 (Upstream & mirroring method)

https://github.com/NixOS/nixpkgs.git

### 备注 (Note)

Related issues:

- https://github.com/tuna/issues/issues/1265

**Comment by iBug** [comment]
能否介绍一下这个仓库对终端用户有什么用途？

**Comment by Freed-Wu** [comment]
when user package new software to NixOS, they need `git clone` this package then `git commit`, `gh pr create`. If a mirror is available, it can speed up `git clone`.

**Comment by taoky** [comment]
从我个人的理解来看，用镜像站的 git 版本做开发，然后给上游提交 PR 是非常怪异的事情，并且存在因为同步延迟导致 PR 出问题的可能。如果实际需求是包含所有历史的仓库太大，需要减小 clone 下来的仓库的大小，可以参考 https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/ 来做，或者使用 GitHub Codespaces。

**Comment by iBug** [comment]
This has no real use for end users. Developers are supposed to handle GitHub connectivity themselves, particularly when the goal is to submit PRs on GitHub.

**Comment by taoky** [comment]
考虑到 git 带来的额外 IO 与 CPU 压力，在 nix 实现了 blobless git clone 之后会考虑同步，相关 issue 参见：https://github.com/NixOS/nix/issues/6111
