### ISSUE TITLE
添加 libnvidia-container APT 镜像

### ISSUE THREAD

**Issue by wxhbts** [ustclug/mirrorrequest#394]
### 预期行为
https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH)

**Comment by knight42** [comment]
补充一下，根据 https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/arch-overview.html#package-repository 这里说的，这个仓库实际上是托管在 https://github.com/NVIDIA/libnvidia-container/tree/gh-pages

**Comment by taoky** [comment]
对应仓库的 LICENSE 是 Apache-2.0，所以看起来也不会有版权上的额外风险。

**Comment by iBug** [comment]
git clone 一份 4G，其中 `.git` 2G，checkout 出来的东西 2G。如果要同步的话，最好能每次更新后都把本地的仓库 shallow 一下

**Comment by taoky** [comment]
由于校内相关实验室需求，我们添加了此仓库：https://mirrors.ustc.edu.cn/libnvidia-container/

**Comment by wxhbts** [comment]
> 由于校内相关实验室需求，我们添加了此仓库：https://mirrors.ustc.edu.cn/libnvidia-container/

能否修改https://mirrors.ustc.edu.cn/libnvidia-container/stable/deb/nvidia-container-toolkit.list 中的地址为本地址

**Comment by taoky** [comment]
> > 由于校内相关实验室需求，我们添加了此仓库：https://mirrors.ustc.edu.cn/libnvidia-container/
> 
> 能否修改https://mirrors.ustc.edu.cn/libnvidia-container/stable/deb/nvidia-container-toolkit.list 中的地址为本地址

同步时一般不修改上游的文件，目前的设施也不方便这么做。我们会考虑类似于 [rosdistro](https://mirrors.ustc.edu.cn/help/rosdistro.html) 这样添加相关的帮助信息。
