### ISSUE TITLE
申请KeyarchOS操作系统软件仓库和ISO镜像

### ISSUE THREAD

**Issue by e-wanerer** [ustclug/mirrorrequest#395]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/ustclug/mirrorrequest/issues) 中讨论过。  
I have checked that this repository has not been discussed in [other issues](https://github.com/ustclug/mirrorrequest/issues).

- [X] 我已仔细阅读 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/350)。  
I have CAREFULLY read the [mirroring rules](https://github.com/ustclug/mirrorrequest/issues/350).

### 项目介绍 (Project introduction)

**KeyarchOS操作系统简介**：KeyarchOS是浪潮信息基于Linux Kernel、OpenAnolis等开源技术自主研发的一款服务器操作系统，支持x86、ARM等主流架构处理器，具备成熟的 CentOS 迁移和替换能力，可满足云计算、大数据、分布式存储、人工智能、边缘计算等应用场景需求。

**申请添加KeyarchOS原因**：当前CentOS已经全面停止更新，国产操作系统迁移已经迫在眉睫，在高校使用方面，KeyarchOS已经多所高校进行了项目落地，包括上海交通大学、武汉科技大学、厦门大学等，后续会有更多的高校项目，为了方便校内人员使用，因此申请增加KeyarchOS镜像源。

### 上游地址与镜像方法 (Upstream & mirroring method)

**同步方式** ：rsync
**rsync地址**：kos.ieisystem.com::keyarchos   ，同步方法如：rsync -avz --progress --delete root@kos.ieisystem.com::keyarchos   /data
  **密码**       ：Keyarchos_yum

### 镜像大小 (Mirror size)

200G

**Comment by iBug** [comment]
根据 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/319)，由 RHEL 衍生的发行版我们仅接受由校内团体提出的镜像申请。关于 CentOS 的迁移，我们已镜像 Rocky Linux，可以满足绝大部分用户的需求。其他考虑请参考[吉林大学镜像站的回复](https://github.com/JLULUG/issues/issues/13#issuecomment-2253235749)。
