### ISSUE TITLE
[NEW]arch-deepin添加请求

### ISSUE THREAD

**Issue by dongfengweixiao** [ustclug/mirrorrequest#4]
此源是Deepin的DDE在arch下的实现，但是当前使用的打包系统为OBS，国内访问速度极其缓慢，所以请求添加镜像。
此源的wiki页面：https://wiki.archlinux.org/index.php/Deepin_Desktop_Environment
此源的OBS下载页面：http://download.opensuse.org/repositories/home:/metakcahura:/arch-deepin/Arch_Extra/

**Comment by axlrose** [comment]
支持一把, deepin的桌面做得挺不错的，试过archlinux跑它的桌面，很漂亮
