### ISSUE TITLE
[New] AUR (Arch User Repository) 软件包源

### ISSUE THREAD

**Issue by CatMe0w** [ustclug/mirrorrequest#41]
官方源地址：https://aur.archlinux.org/

介绍：Arch用户软件仓库（Arch User Repository，AUR）是为用户而建、由用户主导的Arch软件仓库。
详见 ArchWiki https://wiki.archlinux.org/index.php/Arch_User_Repository

为什么希望添加该镜像：同目前已有的 archlinux，archlinuxcn 源一样，aur对于arch用户的重要性不亚于官方仓库，希望添加此镜像。

ps：清华大学 TUNA 源已经有aur镜像了噢 https://mirror.tuna.tsinghua.edu.cn/help/AUR/

**Comment by xinyifly** [comment]
感觉PKGBUILD里面的source指定的放在github和google的文件才是这个瓶颈。

**Comment by hosiet** [comment]
经询问，清华大学 TUNA 的 AUR 源不是镜像，只是做了反向代理。

**Comment by CatMe0w** [comment]
貌似清华源也没有解决这个问题。。。Git Clone URL 也是从原始上游地址获取的
2016年6月9日 上午10:57，Zeyu Chen <notifications@github.com>写道：感觉PKGBUILD里面的source指定的放在github和google的文件才是这个瓶颈。

**Comment by CatMe0w** [comment]
这代表什么？
2016年6月9日 上午11:02，Boyuan Yang <notifications@github.com>写道：经询问，清华大学 TUNA 的 AUR 源不是镜像，只是做了反向代理。

**Comment by zhsj** [comment]
AUR 只是存放 PKGBUILD 文件的地方，官方源没有被墙，速度还可以。而且下载 PKGBUILD 文件，即使速度慢也因为文件小而很快就下好了，所以镜像的意义不大。

**Comment by knight42** [comment]
@CatMe0w 
反向代理即我们代替你去下载 AUR 上的 PKGBUILD 等文件, 然后返回给你. 然而真正的软件包并不是存放在 AUR 上的, 所以在你获得软件包的 URL 后还要自行下载, 这个我们就无能为力了.

我自己也是 Arch 用户(见头像), 我明白 AUR 对于 Arch 用户的重要性. 但是 AUR 其实可以看作只存放软件包的下载地址以及构建脚本的一个平台, 做镜像或反代的实用性都不是很大, 因为影响下载速度的关键因素——软件包并不是放在 AUR 上的. 所以这个请求我们暂时不考虑, 望谅解.

**Comment by xinyifly** [comment]
我现在用proxychains

**Comment by Aitkots** [comment]
原来如此，我还是用官方镜像好了

**Comment by Aitkots** [comment]
不过最近很多高校的镜像都不能访问了，各位大神知道是什么原因吗？

**Comment by zhsj** [comment]
@Aitkots 请不要随意在issue里跑题，继续跑题我会关闭这个issue的回复
