### ISSUE TITLE
[New] 能否镜像 ppa 仓库里的软件？

### ISSUE THREAD

**Issue by GitFuture** [ustclug/mirrorrequest#43]
使用 apt 软件的时候，需要一些额外的软件，但是这些软件在科大的镜像站上没有，需要添加 ppa 源，但是直接下载 ppa 的软件特别慢，能否将 ppa 仓库里的软件做个镜像？

**Comment by zhsj** [comment]
每个 PPA 都是个独立的仓库，无法统一的镜像，过于零散，也不好操作。

**Comment by GitFuture** [comment]
好吧=。= 
但是我看添加的 ppa，最后访问的都是 https://launchpad.net 这个网址，要是能镜像就好了。虽
然有时候有 100 多 K/s，但是慢的时候就几 K/s。

**Comment by abcfy2** [comment]
也可以考虑通过反向代理的形式？

**Comment by gaoyifan** [comment]
可以考虑反向代理

**Comment by knight42** [comment]
http://launchpad.proxy.ustclug.org

**Comment by abcfy2** [comment]
这个反向代理的后端不对，应该是`ppa.launchpad.net`，而不是`launchpad.net`，否则就是404.

给一个测试路径(git-core): `deb http://ppa.launchpad.net/git-core/ppa/ubuntu trusty main`

**Comment by gaoyifan** [comment]
问题可以复现

**Comment by knight42** [comment]
@abcfy2 感谢您的反馈 :smile: 

@gaoyifan 现在问题应该已经修复了.

**Comment by FrankFang** [comment]
http://launchpad.proxy.ustclug.org  这个要如何使用呢？

**Comment by abcfy2** [comment]
把ppa仓库中的ppa.launchpad.net换成那个就行了

**Comment by FrankFang** [comment]
@abcfy2  请问在哪呢，我看 /etc/apt/sources.list 里没有

**Comment by FrankFang** [comment]
找到了 /etc/apt/sources.list.d

**Comment by ihipop** [comment]
```bash
find /etc/apt/sources.list.d/ -type f -name "*.list" -exec  sed  -i.bak -r  's#deb(-src)?\s*http(s)?://ppa.launchpad.net#deb\1 http\2://launchpad.proxy.ustclug.org#ig' {} \;
```
现在虽然ppa官方仓库没有https（但是USTC有）以后PPA官方支持了HTTPS以后上面的替换正则依然适用
如果想USTC的Proxy强制走https，把那个\2改成s即可

另外赞一下USTC

**Comment by ihipop** [comment]
另外 这个文档没更新 https://lug.ustc.edu.cn/wiki/mirrors/help/revproxy
@knight42 @gaoyifan

**Comment by knight42** [comment]
@ihipop 已更新

**Comment by tigerneil** [comment]
多谢！

**Comment by icerhe** [comment]
使用ustc镜像后apt-get update正常执行，然后通过apt-get安装nvidia驱动失败
错误:1 https://launchpad.proxy.ustclug.org/graphics-drivers/ppa/ubuntu xenial/main amd64 nvidia-381 amd64 381.22-0ubuntu0~gpu16.04.2
  Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds
获取:2 https://launchpad.proxy.ustclug.org/graphics-drivers/ppa/ubuntu xenial/main amd64 libcuda1-381 amd64 381.22-0ubuntu0~gpu16.04.2 [2,838 kB]

速度还不如launchpad.net本身,so sad.
我不是教育网用户,有人能测试下教育网外的连接速度吗?

**Comment by wck963** [comment]
dig命令显示ppa.launchpad.net是解析到英国，可以考虑看一下LUG在DO新加坡服务器的是不是绕路了。建议 迁移/新增 到AMS2区，回国ping 200ms左右。

**Comment by dearsatan** [comment]
最近是不是挂掉了？修改后apt-get update会Ign掉

**Comment by GuoweiJiangGitHub** [comment]
@ihipop brilliant

**Comment by echohenry2006** [comment]
great!

**Comment by sharljimhtsin** [comment]
好人呐～～～～内流满面。。。

**Comment by riokaa** [comment]
http已被墙，请换用https，解决connection failed问题。
```shell
find /etc/apt/sources.list.d/ -type f -name "*.list" -exec  sed  -i.bak -r  's#deb(-src)?\s*http(s)?://ppa.launchpad.net#deb\1 https\2://launchpad.proxy.ustclug.org#ig' {} \;
```
已经修改的，手动到`/etc/apt/sources.list.d`修改文件`graphics-drivers-ubuntu-ppa-bionic.list`和`zarquon42-ubuntu-meshlab-bionic.list`。

**Comment by danielhu19** [comment]
Mirror **http://launchpad.proxy.ustclug.org/** is not working!!! (Feb 17 2023)

**Comment by taoky** [comment]
> Mirror **http://launchpad.proxy.ustclug.org/** is not working!!! (Feb 17 2023)

@danielhu19 See https://github.com/ustclug/discussions/issues/325#issuecomment-1434153439
