### ISSUE TITLE
[New] 希望增加LEDE反代

### ISSUE THREAD

**Issue by wongsyrone** [ustclug/mirrorrequest#44]
上游地址： https://www.lede-project.org/index.html

简介： OpenWrt原有开发者的重新fork，致力于开放性，稳定性等，将来和OpenWrt可能合并也可能不合并，目前类似于FFmpeg/Libav，不过目前OpenWrt基本没有新提交，而LEDE发展迅速。

原因：鉴于OpenWrt也是在USTC提供反代，所以这个request主要是请求添加反向代理，不过根据官方说明

> The data volume of the snapshots is roughly 35GB, we expect it to grow by 30-40GB with each release.

如果能够[添加镜像](https://www.lede-project.org/downloads.html)就更好了

**Comment by wongsyrone** [comment]
反代地址：https://downloads.lede-project.org/
目前只有每日构建snapshot

**Comment by yousong** [comment]
昨天写了一封邮件到ustc_lug的列表\[1]，貌似跟这个issue重了。老实讲snapshot每天40GB是不是压力有点大~

另外，有时候网络环境不稳定，编译的时候有些源码下载不到，所以如果能够给 http://sources.lede-project.org/ 做个反代也是很不错的~

\[1] https://groups.google.com/forum/#!topic/ustc_lug/XFPsyGf72c4

**Comment by wongsyrone** [comment]
所以主要想反代啊，镜像什么的算是后话

**Comment by knight42** [comment]
http://mirrors.ustc.edu.cn/lede/

**Comment by yousong** [comment]
所以这是单纯的proxy_pass，还是有proxy_cache的proxy_pass，还是rsync类型？

proxy_cache的配置稍微tricky一些，不过应该会是一种比较好的方法~

**Comment by knight42** [comment]
@yousong 带 cache 的 proxy pass
