### ISSUE TITLE
[New] Manjaro Linux ISO镜像 

### ISSUE THREAD

**Issue by ilofter** [ustclug/mirrorrequest#45]
我们是[Manjaro中国](http://www.manjaro.cn)Manjaro Linux是国际上一支关注度非常高的Linux发行版，2016年2月关注度排名第6。长期以来下载镜像只能通过 [sourceforge](https://sourceforge.net/projects/manjarolinux/files/?source=navbar)进行下载，DNS污染严重，且速度较慢。，因此希望添加Manjaro的下载镜像。
附
1 Mint 3342 
2 Debian 2051 
3 openSUSE 1553 
4 Ubuntu 1527 
5 Fedora 1174 
6 Manjaro 1026 
7 Mageia 942 
8 CentOS 923 
9 Android-x86 840 
10 Arch 838 
　　Manjaro Linux（或简称Manjaro）是基于Arch Linux的Linux发行版，使用Xfce和KDE Plasma作为默认桌面环境，和Arch一样，采用滚动更新。其目标是为PC提供易于使用的自由的操作系统。Manjaro Linux基于Arch Linux，但拥有自己独立的软件仓库。Manjaro的目标是让强大的Arch更方便用户使用，Manjaro使用著名的Pacman且可以直接利用AUR上的资源。

**Comment by Artoria2e5** [comment]
我记得一些 sourceforge 镜像站提供可以直接浏览的文件列表来着？

**Comment by zhsj** [comment]
@Artoria2e5 以前msys2放在sf上就尝试过rsync同步一些sf的镜像站，比如heanet。但这些镜像站对sf上的文件同步并不一定全，sf似乎有自己的控制策略。所以不是可行之计。

@ilofter sf上的文件我们很难同步，如果你是manjaro组织的，建议给我们一个rsync上游

**Comment by ilofter** [comment]
@zhsj Manjaro的下载镜像更新频率低，而且时效性要求并不高。对SF镜像站同步应该没有什么问题吧。

**Comment by zhsj** [comment]
鉴于我们已经收录 Manjaro，如果有合适的同步方式的话我们会收录 ISO 源。

**Comment by ilofter** [comment]
@zhsj Our original server is located in Germany. I can give you the rsync link if needed. However I've to whitelist your IP. Regarding ISOs, wget should be used directly from your mirror. Seems sourceforge doesn't support using rsync for downloading. I can only upload to these servers.
可否提供科大同步服务器的ip地址

**Comment by hosiet** [comment]
教育网：202.38.95.110
移动：202.141.176.110
电信：202.141.160.110
CERNET2：2001:da8:d800:95:110

如只能添加一个 IP，绑定移动 IP 一般情况会好一点？ @zhsj

**Comment by ilofter** [comment]
@zhsj @hosiet  已经添加白名单，同步脚本如下[manjaroreposync](https://raw.githubusercontent.com/manjaro/boxit/master/manjaroreposync)
谢谢USTC LUG对manjaro的支持！

**Comment by hosiet** [comment]
@ilofter
脚本里的同步内容不是 iso，仍然是 repo 的内容。请问脚本是否正确？

**Comment by hosiet** [comment]
看起来上游暂时不提供 ISO 文件的 rsync 的方式。对于 repo 的同步，我们会进行测试，入果速度与延迟有所改进，我们会将上游切换至官方。

**Comment by ilofter** [comment]
@hosiet 一开始的回复是Ok, I've whitelisted IPs. You can modify this script to your needs.已经详细询问

**Comment by ilofter** [comment]
@zhsj

**Comment by ilofter** [comment]
@hosiet 清华大学已经添加镜像源了，希望也能收录。
https://mirrors.tuna.tsinghua.edu.cn/manjaro-cd/

**Comment by hosiet** [comment]
经查，TUNA 是从 mirrorservice.org 的 source forge 镜像内容中使用 rsync 进行了同步。

**Comment by ilofter** [comment]
@hosiet mirror对时效性要求不高的，主要为了加速release仓库里的镜像，至于其它的重要性不高。

**Comment by ilofter** [comment]
直接同步清华源吧

**Comment by zhsj** [comment]
既然TUNA已经同步，那我们还有同步的必要性吗？

**Comment by ilofter** [comment]
不同步就不同步吧

**Comment by gaoyifan** [comment]
TUNA同步了，不代表解决了所有的访问速度问题嘛。。。。

**Comment by ZouBoyu** [comment]
TUNA的iso镜像已经没了，希望能收录。

**Comment by taoky** [comment]
> TUNA的iso镜像已经没了，希望能收录。

参见 <https://github.com/ustclug/discussions/issues/383>，目前没有能够同步的方式。
