### ISSUE TITLE
[New] GMT软件镜像

### ISSUE THREAD

**Issue by seisman** [ustclug/mirrorrequest#48]
- 官方镜像地址：[ftp://ftp.soest.hawaii.edu/gmt]()
- 官方主页：[http://gmt.soest.hawaii.edu/]()
- 项目介绍：GMT是一个开源（LGPLv3协议）的绘图软件，也是地球科学界最常用的制图软件。该软件首个正式版本发布于1988年，并一直维护至今。
- 希望添加该镜像的理由：
  1. 官方镜像国内下载速度慢
   2. [镜像列表](http://gmt.soest.hawaii.edu/projects/gmt/wiki/Download) 中最近的镜像在日本，但似乎已经没有在同步了
   3. 官方镜像中所有包的内容大概只有10G左右，应该不会对LUG服务器造成太大负担

- 其他说明：
  1. 官方镜像是FTP，不确定这样是否会给rsync同步带来麻烦
  2. GMT一般是几个月发布一个新版本，一次新版本大概会更新500M左右的内容，所以如果一天或几天同步一次，也不会有太大的负担。
  3. 如果LUG同意同步的话，我会帮忙联系GMT官方将USTC镜像加进去

**Comment by zhsj** [comment]
可以通过 rsync://ftp.soest.hawaii.edu/gmt 同步。

**Comment by seisman** [comment]
好快的速度。。。我得召集小伙伴们来投票了

**Comment by wqqpp007** [comment]
已投

**Comment by zhsj** [comment]
@wqqpp007 请避免这些无用的comment

**Comment by MilkaLorentz** [comment]
支持

**Comment by knight42** [comment]
http://mirrors.ustc.edu.cn/gmt/

**Comment by taoky** [comment]
@seisman 打扰了。注意到 rsync://gmt.mirror.ac.za/gmt/ 已经 down 了半个多月，同时我注意到国内其他高校镜像站的同步也是失败的：<https://mirrors.cernet.edu.cn/list/gmt>。请问是否了解最新有效的同步方式？

**Comment by seisman** [comment]
https://gmt.mirror.ac.za/ 已经停止服务了，能否试一下下面这个

https://www.earthbyte.org/webdav/gmt_mirror/gmt

**Comment by taoky** [comment]
> https://gmt.mirror.ac.za/ 已经停止服务了，能否试一下下面这个
> 
> https://www.earthbyte.org/webdav/gmt_mirror/gmt

OK，这个可以使用。
