### ISSUE TITLE
添加elixir镜像

### ISSUE THREAD

**Issue by liuhuancom** [ustclug/mirrorrequest#50]
elixir势头有望超过ruby 希望添加elixir镜像

**Comment by gaoyifan** [comment]
elixir官方并没有提供一个二进制软件仓库，目前仍然依赖发行版的软件仓库。
而elixir与erlang共享代码包仓库，elixir没有自己独立的仓库。
要镜像只能是源代码的git仓库了，没有太大必要性。 
如果以上有错误，或者elixir的软件发布策略有变化，请回复这个issue。
