### ISSUE TITLE
求mysql镜像

### ISSUE THREAD

**Issue by lj2007331** [ustclug/mirrorrequest#51]
如题 ，求mysql镜像

**Comment by zhsj** [comment]
Mirror info:
https://dev.mysql.com/downloads/how-to-mirror.html

About 400GB

**Comment by lj2007331** [comment]
求加上，国内只有一家sohu（mirrors.sohu.com），最近老是挂，求加上！

**Comment by gaoyifan** [comment]
地址：http://mirrors.ustc.edu.cn/mysql-ftp/
上游：rsync://mysql.he.net/mysql/
同步方式：rsync
