### ISSUE TITLE
[Modify] 希望修改 rubygems 镜像为反向代理模式

### ISSUE THREAD

**Issue by bianjp** [ustclug/mirrorrequest#52]
目前 https://mirrors.ustc.edu.cn/rubygems/ 是挂的，很久没有同步了，也不能响应 api 请求。

[ruby-china](https://ruby-china.org/) 社区维护着一个 [gems.ruby-china.org](https://gems.ruby-china.org/) 镜像，但一直[不太稳定](https://ruby-china.org/topics/30734)。

如果 ustclug 还愿意维护一个 rubygems 镜像的话，建议采用 反向代理 + 缓存 的架构，可参考 [ruby-china 源](https://github.com/ruby-china/rubygems-mirror)。

**Comment by gaoyifan** [comment]
已修复同步失效的问题。

**Comment by gaoyifan** [comment]
由于镜像站本身网络环境的问题，如果改为反代，首次访问失败率会很高。个人倾向于完整镜像。
