### ISSUE TITLE
[New]Termux源镜像申请

### ISSUE THREAD

**Issue by yunfan** [ustclug/mirrorrequest#53]
# 上游源地址

http://termux.net/
# 该项目介绍

termux是个在android手机上提供的命令行环境

自带debian系的apt包管理。

并且默认不要求root权限

更多介绍见 http://termux.com
# 为什么希望添加该镜像

因为这个应用的特性 使得其可以将任意的android手机(5.0+)转换成一个开发环境 所以我觉得这个是个非常大众的项目 应该很有推广价值 只不过目前官网软件仓链接速度有限 影响了体验

**Comment by hosiet** [comment]
termux/termux-packages#67

**Comment by gaoyifan** [comment]
直接从清华同步？rsync://mirrors.tuna.tsinghua.edu.cn/termux

**Comment by yunfan** [comment]
你们只能rsync么 我还以为是http镜像的

**Comment by hosiet** [comment]
http/https 不是不行，但不适合做镜像，是最后的选择，能不用就不用

**Comment by gaoyifan** [comment]
http://mirrors.ustc.edu.cn/termux/
