### ISSUE TITLE
希望添加CDH镜像

### ISSUE THREAD

**Issue by abcfy2** [ustclug/mirrorrequest#56]
CDH是hadoop一个重要的分支，在社区有非常高的威望。具有部署简单，商业化支持，性能稳定等优秀的特点。但是官方仓库在国内访问的速度奇慢无比，造成国内用户在产品环境批量部署十分困难。

官方仓库地址(CDH5版本): http://archive.cloudera.com/cdh5/

官方提供的镜像方法(只有yum的，ubuntu的可能只能通过镜像http网站了): http://www.cloudera.com/documentation/enterprise/latest/topics/cdh_ig_yumrepo_local_create.html

**Comment by mcsrainbow** [comment]
CDH目前的Cloudera Manager支持更低耦合的Parcels包管理，上面的镜像URL(http://archive.cloudera.com/cdh5/)中包含了Parcels的软件包，很实用。

**Comment by knight42** [comment]
我暂时加了一个反代 http://mirrors.ustc.edu.cn/cdh5/ .
如果日后发现下载量比较大的话, 再考虑改成静态文件.

**Comment by abcfy2** [comment]
反向代理有缓存吗？如果有的话其实也为部署安装提速不少，毕竟批量部署的时候部署同一个软件包的可能性更高。如果反代有缓存的话就太好了。

**Comment by knight42** [comment]
会对 200 的响应缓存 10 小时

**Comment by abcfy2** [comment]
试着wget一个文件，很容易`504：Gateway Time-out`:
```
wget http://cloudera.proxy.ustclug.org/cdh5/parcels/5.8.0/CDH-5.8.0-1.cdh5.8.0.p0.42-trusty.parcel
```

貌似reverse proxy的机制是等资源缓冲完再下载么？

**Comment by abcfy2** [comment]
没事了，刚才不知道为啥总是报504，现在随便试了几个又都没问题了。

**Comment by knight42** [comment]
@abcfy2 

> 貌似reverse proxy的机制是等资源缓冲完再下载么？

我们现在是用 nginx 做反代, 现在的设置是先把首先收到的响应 buffer 住, 随后再发给 client.

> 试着wget一个文件，很容易504：Gateway Time-out:

刚才看了下日志, 发现是连上游的时候 connection timed out, 现在试着把超时从原来的 60s 提高到 90s, 希望能解决问题.

**Comment by gaoyifan** [comment]
能否设置成从上游取数据的同时，也给client发送数据？ @knight42

**Comment by knight42** [comment]
nginx 的 proxy_buffering 只能控制 nginx 要么把首先收到的响应塞进 buffer
后再发给 client, 要么收到响应立即传给 client, 不涉及 buffer.

我觉得如果 cache miss 不是很频繁而且又不是经常下载大文件的话的话,
不用太在意这个. 等过一段时间后我统计一下 hit/miss 的次数.

**Comment by abcfy2** [comment]
CDH的依赖有些重，会带有一个管理界面CM，以及消息队列kafka。但是这玩意设计的是仓库分开的。
比如cm5在`http://archive.cloudera.com/cm5/`, kafka在`http://archive.cloudera.com/kafka/`。

是否方便将这两个地址一并做反向代理呢？

**Comment by knight42** [comment]
@abcfy2 cloudera.proxy.ustclug.org/{kafka,cm5}

**Comment by abcfy2** [comment]
哦，原来是通过一个子域名全部反代了，多谢了

**Comment by stduolc** [comment]
额.你们的proxy速度怎么也怎么慢.

**Comment by gaoyifan** [comment]
尝试了一下完整镜像。下载了2TB，还没同步完。目测总尺寸超过4TB。
已放弃。

**Comment by abcfy2** [comment]
反向代理就挺好，我这边部署pacels速度也有1.5MB/s。比以前从官方仓库部署只有10KB/s好太多了。主要就是这玩意容量大，每个版本一个多GB，全量同步仓库觉得没必要

**Comment by mattshma** [comment]
貌似现在代理地址已打不开了，503？

**Comment by zhsj** [comment]
> 貌似现在代理地址已打不开了，503？

https://news.ustclug.org/2018/06/server-down/

**Comment by mattshma** [comment]
@zhsj 原来如此，谢谢！

**Comment by francis0407** [comment]
反向代理的大文件总是下载失败，有解决方案吗？开头下了100M左右就断开失败了

**Comment by anjia0532** [comment]
cdh5:反代 https://cloudera.proxy.ustclug.org/cdh5
cdh6:反代 https://cloudera.proxy.ustclug.org/cdh6

**Comment by yssnet** [comment]
还能用吗？有没有其他的代理地址？

**Comment by ziya05** [comment]
请问这个是不是只有 hadoop等组件的地址了？ 没有找到 cloudera-manager-server、agent、daemons的地址了

**Comment by abcfy2** [comment]
@ziya05 你说的那几个组件在cm这个子目录中，比如https://cloudera.proxy.ustclug.org/cm6/6.3.1/ubuntu1804/apt/pool/contrib/e/enterprise/
