### ISSUE TITLE
Could you please add the percona server mirror?

### ISSUE THREAD

**Issue by kaneawk** [ustclug/mirrorrequest#58]
Percona Server for MySQL:
Is a free, fully compatible, enhanced, open source drop-in replacement for MySQL® that provides superior performance, scalability and instrumentation. With over 2,700,000 downloads, Percona Server’s self-tuning algorithms and support for extremely high-performance hardware delivers excellent performance and reliability.

official link:
https://www.percona.com/

download link:
https://www.percona.com/downloads/

The official download link is download too slowly. I hope USTC team can add this.
thanks.

**Comment by gaoyifan** [comment]
P.S.  rsync://rsync.percona.com/rsync/

**Comment by kaneawk** [comment]
Bad news, this website does not support rsync. :(

**Comment by gaoyifan** [comment]
http://mirrors.ustc.edu.cn/percona/
