### ISSUE TITLE
望能使用非 WoSgin / StartCom 颁发的证书

### ISSUE THREAD

**Issue by lilydjwg** [ustclug/mirrorrequest#60]
RT. WoSgin 最近爆出了[一大堆问题](https://wiki.mozilla.org/CA:WoSign_Issues)。有人能通过它拿到 GitHub 的证书，能拿到阿里 CDN（alicdn.com）的证书。虽然没有证据表明这些滥发的证书已经被用来作恶，但我担心也许明天，就会有人拿着 ustc.edu.cn 的证书传播病毒木马了（虽然我在使用的部分基本都有签名）。

贵站是目前唯一一个我不能取消信任 WoSgin / StartCom 的理由了。

**Comment by zhsj** [comment]
镜像站使用 https 的意义在于防止运营商缓存接触，造成诸如 apt 更新时 hashsum mismatch 等错误。不使用 https 不代表不安全，这点请理解。

镜像站有使用 letsencrypt 签发证书的域名 ftp.cn.debian.org，请考虑暂时使用。

ustclug 域名迁移到 letsencrypt 的事情我们正在讨论，请参考 https://github.com/ustclug/discussions/issues/22

**Comment by lilydjwg** [comment]
好的。

镜像源不使用 WoSign 证书的意义在于方便用户禁用系统级的 WoSign 证书，这点也请你们理解。

**Comment by gaoyifan** [comment]
已更换为AlphaSSL @lilydjwg
