### ISSUE TITLE
希望新增Ubuntu Cloud镜像

### ISSUE THREAD

**Issue by abcfy2** [ustclug/mirrorrequest#63]
Ubuntu Cloud是Ubuntu专为云平台部署定制的镜像(如Openstack, LXD/LXC，AWS等等)

主页: https://cloud-images.ubuntu.com/
镜像方法: Via rsync: rsync://cloud-images.ubuntu.com/cloud-images (from [here](https://jujucharms.com/u/tribaal/ubuntu-mirror#charm-config-cloudimage-sync-location))
或反向代理也可

**Comment by gaoyifan** [comment]
added
