### ISSUE TITLE
申请建立 FreeBSD 的镜像

### ISSUE THREAD

**Issue by njlyf2011** [ustclug/mirrorrequest#64]
官方地址: pkg.freebsd.org
FreeBSD 是一个类Unix操作系统

FreeBSD是一款类Unix系统，但是最近国内都没有镜像，导致安装软件很麻烦，故申请之。

望批准，谢谢。

**Comment by zhsj** [comment]
我们有 freebsd 源，http://mirrors.ustc.edu.cn/freebsd/ 最近磁盘整列在维护，暂时访问不了。

**Comment by hosiet** [comment]
@njlyf2011 恕无能为力。FreeBSD 项目不接受新的镜像站点，且不提供 pkg 源的同步方式，我们也很难做镜像。
https://lug.ustc.edu.cn/wiki/mirrors/help/freebsd

**Comment by hosiet** [comment]
@njlyf2011 duplicate with #2
