### ISSUE TITLE
添加 FreeBSD pkg 软件源

### ISSUE THREAD

**Issue by njlyf2011** [ustclug/mirrorrequest#68]
官方给的答复是，因为需要保证软件包的质量，所以不向第三方开放。

不过他提到，建立一个中国镜像也是可行的，只需要国内的公司或高校提供一个空间即可。

鄙人认为您可以提供一个空间，这样FreeBSD在中国的用户可以更加方便，且中科大镜像源同时也能得到很好的发展。
联系方式：info@freebsdfoundation.org
freebsd-pkg@freebsd.org

**Comment by zhsj** [comment]
个人不使用 FreeBSD，不知道现在 FreeBSD 现在是什么状态。有一个问题，既然 FreeBSD 对镜像不持开发态度，我们为什么还要镜像它呢？

**Comment by zhsj** [comment]
另外 FreeBSD 有中国的官方站点 ，http://ftp.cn.freebsd.org/
不知道为何现在无法访问，我建议你先尝试联系原有的维护者问下是什么状态。

**Comment by njlyf2011** [comment]
@zhsj 如果有镜像的话更方便一些啊（国外的镜像经常404），另外 FreeBSD 也不是说完全不持开放态度。

**Comment by wbsdty331** [comment]
这个http://ftp.cn.freebsd.org/，指向的IP是222.73.165.29
然后根据 IP反查找到了一个 www.freebsdchina.org
他们提供了一个镜像仓库列表：https://www.freebsdchina.org/mirrors.php，然而都不能访问了
可以给上面的几个管理员联系：

<alu@FreeBSD.org.cn>
<wjf@FreeBSD.org.cn>
<ld@FreeBSD.org.cn>
<hostmaster@cn.FreeBSD.org>

另外，他们的论坛也还在：https://www.freebsdchina.org/forum/
可以试试去反馈

**Comment by zhsj** [comment]
@wbsdty331 我们这边没有freebsd用户哎😂
和freebsd中文社区联系貌似freebsd用户去做更合适呐

**Comment by ykla** [comment]
参考https://www.chinafreebsd.cn 
已经进行了镜像同步，使用lftp。不过压力比较大，贵部能否也同步一下…
同步脚本在网页左侧。

**Comment by ykla** [comment]
另外http://ftp.cn.freebsd.org/已经好几年没反应了…

**Comment by bobby285271** [comment]
赞同... 目前整个亚洲已知的就一个 chinafreebsd... 😂
台湾的官方 pkg 源又挂了... 
其实需求量还是很大的...

**Comment by gaoyifan** [comment]
@knight42  rsync-huai进度如何？
如果负载降下来了，我觉得可以考虑增加freebsd源。

**Comment by zhsj** [comment]
@gaoyifan 并不觉得拿lftp同步这么大的源是个好的选择

**Comment by gaoyifan** [comment]
@zhsj @ykla 那就让chinafreebsd.cn给我们开rsync吧

**Comment by ykla** [comment]
@gaoyifan 群号是317764984，是不是可以联系一下

**Comment by ykla** [comment]
@gaoyifan 看起来是不太可能给镜像…

**Comment by gaoyifan** [comment]
同步完成~ 欢迎使用~
http://mirrors.ustc.edu.cn/freebsd-pkg/

**Comment by gaoyifan** [comment]
BTW,  同步脚本：https://github.com/ustclug/ustcmirror-images/blob/master/freebsd-pkg/sync.sh
