### ISSUE TITLE
grails maven仓库镜像

### ISSUE THREAD

**Issue by abcfy2** [ustclug/mirrorrequest#69]
grails官方仓库`repo.grails.org`由于走了AWS CDN，导致国内被block，以前可以下载的插件依赖统统歇菜了，希望能镜像这个仓库。

而官方的issue讨论也希望国内有镜像可以镜像这个仓库: https://github.com/grails/grails-core/issues/9766

镜像方式: 反向代理`repo.grails.org`即可

**Comment by zhsj** [comment]
merge with #34
