### ISSUE TITLE
[New]funtoo

### ISSUE THREAD

**Issue by zhsj** [ustclug/mirrorrequest#7]
> From: n***
> Date: 2015-02-18 12:40 GMT+08:00
> Subject: funtoo源 镜像
> To: lug@ustc.edu.cn
> 
> 您好，请问下你们的镜像站点能不能提供funtoo的镜像？

**Comment by fenglc** [comment]
> Funtoo Linux是一个基于Gentoo Linux的Linux发行版，在2008年由Gentoo Linux项目的前任领导者Daniel Robbins启动。

—— 转自[维基百科](https://zh.wikipedia.org/wiki/Funtoo_Linux)

**Comment by skyzh** [comment]
为啥不能直接 git clone?

**Comment by damon-kwok** [comment]
@taoky we  need sync all repo, from: github.com/funtoo/

**Comment by iBug** [comment]
27 个 git 仓库的数量和容量也不小，不是很方便处理

**Comment by damon-kwok** [comment]
同步这些meta就是最大的体验提升，里面外链的地址几乎不是事儿

**Comment by damon-kwok** [comment]
我在#305看到了类似的问题 gentio-zh是gentoo系的中国ports仓库，可以同时被gentoo funtoo bentoo pentoo sabayon calculate等发型版使用，里面有微信 钉钉 wps等软件，但是想从github下载这些小碎文件经常需要数天之久，经常不到一半就断掉了 其实只要能把ports本身镜像过来就好了，体验感瞬间提升

**Comment by taoky** [comment]
https://lwn.net/Articles/983977
