### ISSUE TITLE
golang镜像

### ISSUE THREAD

**Issue by abcfy2** [ustclug/mirrorrequest#70]
go-lang在国内被墙了，根本无法下载go-lang的安装包和源码包，以及类库，希望可以镜像。

镜像方式: 暂时未知，我没找到go-lang的文档中哪有镜像的方案，可以考虑做反向代理`https://storage.googleapis.com/golang/`

go-lang官方下载地址: https://golang.org/dl/

**Comment by zhsj** [comment]
源码包可以从 Github 获取，安装包 Mac OS 可以用我们的 Homebrew 源，Linux 各个发行版都有镜像。

Golang 的库哪怕镜像了，你如何配置 golang 从镜像获取？

**Comment by abcfy2** [comment]
Linux发行版的版本都是固定的，而且轻易也不会更新，如果有多版本需求的话并不方便。`gvm`可以管理多版本，我正在写pull request，可以支持从镜像站下载官方编译好的二进制包，但是我还没找到合适的镜像站。golang中国倒是有一个下载，但是存储路径和go-lang官方不一样，没法用gvm管理。

库的镜像我也没想好，希望google以后支持，或者其他工具可以支持，目前只能用go install repo/package这种方式手工从镜像站安装依赖库

**Comment by medicalwei** [comment]
如果可以裝 gsutil (Google Cloud Storage 工具) 的話，看來可以用 gs://golang/ 去下載

**Comment by zhsj** [comment]
https://github.com/ustclug/ustcmirror-images/issues/11

**Comment by knight42** [comment]
http://mirrors.ustc.edu.cn/golang/
