### ISSUE TITLE
申请建立 Linux-libre 镜像

### ISSUE THREAD

**Issue by njlyf2011** [ustclug/mirrorrequest#71]
官方源地址：http://linux-libre.fsfla.org/pub/linux-libre

原因：
国内没有 Linux-libre 的源。

**Comment by 210hcl** [comment]
可以看下gnu里面的linux-libre是否能符合要求。

**Comment by njlyf2011** [comment]
好吧。。。那我觉得这个 ISSUE 应该没有必要存在了。。。
