### ISSUE TITLE
salt镜像挂了

### ISSUE THREAD

**Issue by abcfy2** [ustclug/mirrorrequest#72]
apt update的时候报404，下面没什么deb文件了

**Comment by knight42** [comment]
能不能列一下你 source.list 里相关的配置?

另外我觉得 salt 镜像里的 deb 包还是有不少的, 比方说 http://mirrors.ustc.edu.cn/salt-debian/pool/main/s/salt/. 不知道你指的是哪里没有 deb 包了?

**Comment by abcfy2** [comment]
@knight42 我记得salt-debian已经废弃了吧？官方自从有了`repo.saltstack.com`这个软件仓库之后，支持了`rsync`同步，之后ustc的salt仓库改到`salt/`了，不再使用`salt-debian/`了。

仓库配置:
```
deb https://mirrors.ustc.edu.cn/salt/apt/ubuntu/14.04/amd64/latest trusty main
```

apt update报错:
```
W: 无法下载 https://mirrors.ustc.edu.cn/salt/apt/ubuntu/14.04/amd64/latest/dists/trusty/main/binary-amd64/Packages  HttpError404

W: 无法下载 https://mirrors.ustc.edu.cn/salt/apt/ubuntu/14.04/amd64/latest/dists/trusty/main/binary-i386/Packages  HttpError404
```

官方仓库支持rsync同步，参见: https://mirrors.ustc.edu.cn/salt/#mirror

**Comment by knight42** [comment]
@abcfy2 
原来如此... 现在应该已经重新同步过了. 你再试试看?

**Comment by abcfy2** [comment]
fixed

**Comment by gaoyifan** [comment]
salt-debian/仓库中包含全架构的二进制包。salt/中只包含amd64和armhf架构。因此salt-debian一直没有取消同步。
