### ISSUE TITLE
添加linux-stable

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [ustclug/mirrorrequest#74]
来自微信群
做项目常用到的
linux-stable.git不能从linux.git中checkout出来
[submodule "qemu"]
        path = qemu
        url = http://git.qemu.org/git/qemu.git
[submodule "buildroot"]
        path = buildroot
        url = https://git.busybox.net/buildroot
[submodule "linux-stable"]
        path = linux-stable
        url = https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
[submodule "u-boot"]
        path = u-boot
        url = http://git.denx.de/u-boot.git

**Comment by gaoyifan** [comment]
已将linux.git替换为linux-stable.git
