### ISSUE TITLE
OpenStreetMap API反向代理/缓存

### ISSUE THREAD

**Issue by nicholascw** [ustclug/mirrorrequest#75]
OpenStreetMap作为众多开源地理软件的依赖却没有办法在中国地区较为快速的打开，考虑到地图数据不需要频繁更新，能否在源内提供缓存或反向代理？谢谢

**Comment by zhsj** [comment]
@wck963 能否给出具体的镜像方法？

**Comment by wck963** [comment]
由于镜像体积问题没有具体实践过，但官方Wiki有操作方法
详参：
http://wiki.openstreetmap.org/wiki/Planet.osm#Processing_the_File
http://planet.osm.org/

**Comment by zhsj** [comment]
@wck963 我们可以从 ftp.heanet.ie/mirrors/openstreetmap.org/ 镜像数据，但我们不会对数据进行处理。我不知道这样的镜像是否有实用性。
