### ISSUE TITLE
rust-static镜像的问题

### ISSUE THREAD

**Issue by redtankd** [ustclug/mirrorrequest#78]
我用rustup升级nightly rust，升级rustc和rust-std都正常使用了ustc镜像，但是cargo任然通过境外网站下载，日志如下：

```
info: downloading component 'cargo'
verbose: downloading file from: 'https://s3.amazonaws.com/rust-lang-ci/cargo-builds/ddb5c328d67f046c929928f161d50eef1cbc3e81/cargo-nightly-x86_64-apple-darwin.tar.gz'
verbose: downloading with curl
```

amazonaws很难连上，导致nightly rust更新一直不成功。请问需要如何解决这个问题呢？

**Comment by knight42** [comment]
@redtankd https://lug.ustc.edu.cn/wiki/mirrors/help/rust-crates

我们有设置反代, 可按照上面的帮助进行配置
