### ISSUE TITLE
可以添加sabayon linux的镜像么

### ISSUE THREAD

**Issue by jamesarch** [ustclug/mirrorrequest#79]
sabayon linux在国内很少有人用 是一个基于gentoo的发行版，呃呃  这些wikipedia上都有的，但是国内源目前我所知道的就交大的一个

http://mirror.bjtu.edu.cn/sabayon/
如果各位管理员大大有时间，有资源的话麻烦同步下这个源，谢啦。

PS：作为一个mirrors.ustc.edu.cn的长期用户，非常非常非常感谢你们为开源做出的努力~ 辛苦啦

**Comment by bobby285271** [comment]
其实阿里云是有sabayonlinux源的...
