### ISSUE TITLE
求Nuget镜像

### ISSUE THREAD

**Issue by PMExtra** [ustclug/mirrorrequest#80]
求.NET包管理器Nuget的镜像或者反代orz

### 官方地址
官方网站：[https://www.nuget.org/](https://www.nuget.org/)
APIv3：[https://api.nuget.org/v3/index.json](https://api.nuget.org/v3/index.json)

### 说点废话

可能linux爱好者对.NET不了解，稍微安利一下……
.NET已经于2015年发布.NET Core开源产品并原生支持Linux/macOS

并且Redhat也已经与微软宣布合作关系，上线了 [https://developers.redhat.com/dotnet](https://developers.redhat.com/dotnet) 专题页面，并注册了 [redhatloves.net](http://redhatloves.net/) 域名（手动滑稽

就在近期 connect(); //2016 大会上，谷歌也宣布了加入.NET基金会。

所以，不论.NET过去是什么样的，但现在，它是一个免费的，开源的，跨平台的一个不断完善的敏捷开发框架。

### 最后
貌似Nuget官方并没有提供mirror工具，因此，如果需要的话我很愿意参与Nuget-Mirror的开发。

**Comment by gaoyifan** [comment]
@PMExtra  如果能开发一套nuget镜像工具就太好了。效果会比反代好很多。

**Comment by PMExtra** [comment]
善，手上事情忙完就开工

**Comment by PMExtra** [comment]
遭遇一点问题，NuGet.Server包（官方用于搭建NuGet服务器的库）目前只支持Framework框架，也就是说，要么得用Windows服务器，要么得用Linux+mono（暂时还不确定mono环境下会不会有坑）。

所以我就想先问一下我们是否能使用Windows服务器，如果不行，那我开发时就直接在Linux环境下测试，如果有Windows服务器，那我就省的踩这个坑了。

**Comment by gaoyifan** [comment]
这边只有Linux环境，所有镜像同步代码都是运行在docker中的。
如果您对docker熟悉，可以直接接住docker构建、测试。如果不熟悉也没关系，最后交给我来打包就好。

**Comment by PMExtra** [comment]
OK，docker稍微知道一点，正好这次把docker也实践一下好了。

**Comment by PMExtra** [comment]
近期工作比较忙，镜像工具的计划得推迟到春节期间了，暂且说明一下情况表示没有弃坑hh

**Comment by ggqq** [comment]
非常好的一个提议，如果有需要我也可以尽一点微力 👍

**Comment by PMExtra** [comment]
@ggqq 非常感谢，之前没有及时回复表示抱歉，前段时间太忙了。这几天趁着春节空隙打算推进以下NuGet镜像的进度。如果可以麻烦留一个即时通讯方式方便交流，或者直接加我[QQ](http://wpa.qq.com/msgrd?v=3&uin=1304445713)

**Comment by PMExtra** [comment]
目前主要还是在折腾mono和docker的环境问题，真可惜[NuGet.Server](https://www.nuget.org/packages/NuGet.Server/)包至今不支持NetCoreApp

**Comment by PMExtra** [comment]
踩了个大坑，NuGet.Server的mono兼容貌似都难以实现。所以目前想要在Linux环境中搭建NuGet服务器还是比较困难，只有一个第三方的Java解决方案[jnuget](https://bitbucket.org/aristar/jnuget)。
因此决定暂且放下这个项目，等官方移植NuGet.Server到Core平台之后再继续吧。

**Comment by PMExtra** [comment]
@gaoyifan 不知道你们的Docker能否运行[Windows Server 2016 nano server](https://hub.docker.com/r/microsoft/nanoserver/)呢？据我所知这个镜像似乎只能运行在Windows Container上，也就是要求宿主机也得是Windows，不知道有没有理解错。

**Comment by gaoyifan** [comment]
@PMExtra 似乎是这样的，只能运行在windows下

**Comment by PMExtra** [comment]
嗯，那就比较尴尬了，先等官方的Core支持吧。。。

**Comment by 1354092549** [comment]
似乎NuGet.Server是开源的，有可能通过一些小修改来解决吗？

**Comment by PMExtra** [comment]
@1354092549 是开源的，但是是Framework平台的，打包docker容器会比较麻烦。至于移植Core，那是个非常庞大的工作，还有很多坑估计1.1根本填不上，等Core2.0出来再看看吧。

**Comment by gaoyifan** [comment]
也可以考虑wine+.Net的方案

**Comment by 1354092549** [comment]
@PMExtra 主要是哪方面问题？

**Comment by PMExtra** [comment]
@1354092549 NuGet.Server 中使用了大量Core尚未支持的API。

**Comment by PMExtra** [comment]
无意中点开了这个issue。虽然有点晚了回复一下。

1. 今年以来Nuget官方服务器稳定性似乎好了很多，在国内直连似乎问题也不大，因此我们需要重新评估一下是否有镜像Nuget的需求。

2. Core2.0+对Framework代码的兼容确实好了很多，理论上移植可行了，如果确认了仍然有镜像Nuget的需求，我们可以尝试着手移植 Nuget.Server 。

@cmpute @1354092549

**Comment by 1354092549** [comment]
确实直连nuget官方服务器的稳定性和速度都好了很多
~倒是访问github慢了不少~

**Comment by NepPure** [comment]
建议用https://github.com/loic-sharma/BaGet
代替Nuget.Server，基于net.core

**Comment by PMExtra** [comment]
NuGet 目前官方已经有亚太地区CDN，速度都还不错，没有遇到被墙的现象了，所以暂时不需要镜像了。
