### ISSUE TITLE
求Cocoapods镜像

### ISSUE THREAD

**Issue by PMExtra** [ustclug/mirrorrequest#81]
CocoaPods 是 Cocoa / Cocoa Touch (macOS/iOS) 的开发包管理器，求git镜像

https://github.com/CocoaPods/Specs.git

**Comment by gaoyifan** [comment]
总大小不到400M, 感觉镜像的意义不大啊

**Comment by PMExtra** [comment]
镜像一个git仓库并不复杂，主要是江苏等地区近期访问github实在是太不稳定了orz
镜像站除了阿里我只服ustc，虽然cocoapods目前国内已经有私人镜像到coding或者oschina了，但还是希望能有个更加权威的镜像源，第一保障不会篡改，第二保障及时同步……

**Comment by gaoyifan** [comment]
待[GitLab](https://git.ustclug.org)服务器完成升级，我将目前的git仓库镜像统一放置到GitLab上吧。

**Comment by PMExtra** [comment]
嗯，刚发现 [https://mirrors.tuna.tsinghua.edu.cn/](https://mirrors.tuna.tsinghua.edu.cn/) 清华也有 CocoaPods 镜像，可惜页面是404不知道他们git仓库的地址到底是啥 orz

**Comment by diguage** [comment]
这个可以有，现在已经1G多了，网速不好的话，特别容易断开，一断就得重头开始。
