### ISSUE TITLE
建议增加Solus发行版镜像！

### ISSUE THREAD

**Issue by Chao-zhi** [ustclug/mirrorrequest#83]
Solus是一个新兴的Linux发行版，总有些诸多优良的特性，它整洁、优雅、漂亮、快速。它拥有一套独立的软件包管理系统，是一个滚动发行版本，十分建议中科大开源镜像站能够加入solus的镜像源。

**Comment by LER0ever** [comment]
Solus +1, 急需国内源!

**Comment by gaoyifan** [comment]
未找到具体的镜像方案

@LER0ever  @Chao-zhi  请问要如何镜像呢？是否有rsync上游？

**Comment by Chao-zhi** [comment]
@gaoyifan 我也没找到镜像的方法，以为你们有办法……

**Comment by LER0ever** [comment]
@gaoyifan 不知道solus官方源可否rsync，wiki里也没有说什么第三方镜像 
https://packages.solus-project.com

**Comment by gaoyifan** [comment]
HTTP方式比较难以镜像，尤其是上游更新文件时，HTTP无法判断文件是否被修改过，导致镜像不一致。

**Comment by 7sDream** [comment]
清华镜像站已经有这个源的镜像了，貌似一开始也比较困难但是最后和官方人员联系以后解决了。

见： tuna/issues#184

是否考虑和他们那边联系下加上这个镜像呢？

**Comment by GZGavinZhao** [comment]
这个镜像还打算增加吗？现在的rsync源应该是rsync://mirrors.rit.edu/solus
