### ISSUE TITLE
Google reCAPTCHA反向代理

### ISSUE THREAD

**Issue by wck963** [ustclug/mirrorrequest#85]
目前国内没有可以媲美的验证码服务,所以如果能把reCAPTCHA服务反向代理进来那是极好的.
实现不难,水表可能性也基本为零.同时方便了上国外网站,也方便国内广大站长提高自身的姿势水平,否则too young too simple的滑动拼图验证码,腾讯点汉字验证码甚至在收费道路上跑得比西方G家还要快就不好了.

需要提醒的是新版验证码貌似有基于IP地址判断身份的权重,所以最好跟科大学生出口IP分开否则时间长了可能会各种block/验证码,并且使用的站长应该适当降低验证码难度.(验证码控制面板中高级设置可以修改.)

**Comment by wck963** [comment]
配置可以尝试参考 https://xiaopc.org/2016/07/18/nginx-%E5%8F%8D%E4%BB%A3-google-analytics-%E5%92%8C-recaptcha-%E5%AE%9E%E8%B7%B5/

**Comment by zhsj** [comment]
Not a open source software

**Comment by ShadowRZ** [comment]
不然我自己做一个够好的验证码系统？
@zhsj @wck963
