### ISSUE TITLE
希望添加 docker armhf 源

### ISSUE THREAD

**Issue by yangxuan8282** [ustclug/mirrorrequest#86]
- 官方镜像地址：
https://apt.dockerproject.org/
- 项目介绍：
Docker 是一个开源的容器管理器。
项目官方网站：https://dockerproject.org/
- 添加原因：
虽然 docker-engine 不大，但有时候没速度下起来真挺慢的，看 ustclug 的镜像里有其它架构的，希望能加一下 armhf 的

https://apt.dockerproject.org/repo raspbian-jessie

**Comment by gaoyifan** [comment]
目前docker是从TUNA同步的。方便增加armhf架构吗？@bigeagle

**Comment by knight42** [comment]
这个我们可以直接用 apt-mirror 同步的吧

**Comment by gaoyifan** [comment]
我看apt.dockerproject.org没人修，就换成rsync了。目前apt.dockerproject.org是301跳转。

**Comment by knight42** [comment]
已加. 试试 `deb http://mirrors.ustc.edu.cn/docker/apt/repo raspbian-jessie main`

**Comment by yangxuan8282** [comment]
这么晚还没睡
刚试了一下没问题，多谢

**Comment by gaoyifan** [comment]
@knight42  apt-mirror是否会与rsyncsync冲突呢？
如当rsyncsync更新时，删掉了上游（TUNA）不存在的文件。

**Comment by knight42** [comment]
@gaoyifan 我现在暂停了. 计划只向 tuna 同步 yum/ 下的内容

**Comment by gaoyifan** [comment]
@knight42 要不原改成apt.dockerproject.org和yum.dockerproject.org两个仓库吧

**Comment by knight42** [comment]
@gaoyifan 我觉得合起来也不坏嘛..

**Comment by gaoyifan** [comment]
@knight42 好不容易将fedora仓库强行展平了....  这是又要合起来的节奏啊.....

**Comment by bigeagle** [comment]
TUNA 可以加 armhf，我之前一直不知道有

**Comment by bigeagle** [comment]
可以尝试我写的 apt-download 脚本 https://github.com/tuna/tunasync-scripts/blob/master/helpers/apt-download

**Comment by gaoyifan** [comment]
@bigeagle 赞！我来集成到ustcsync中🙈

**Comment by hawkinchina** [comment]
arm64 的是否支持？

**Comment by zhsj** [comment]
> arm64 的是否支持？

http://mirrors.ustc.edu.cn/docker-ce/linux/static/stable/aarch64/

**Comment by hawkinchina** [comment]
上面发的链接是docker程序本身 for arm64， 我说的是，docker里面的镜像images for arm64，是否支持同步下拉。。：）

**Comment by hawkinchina** [comment]
就是/etc/docker/daemon.json里面的  registery-mirrors:  镜像加速for arm64 是否支持。?

**Comment by iBug** [comment]
Docker 镜像源可以考虑 `dockerhub.azk8s.cn` 和 `hub-mirror.c.163.com`。

**Comment by hawkinchina** [comment]
X86的163没有问题。 arm的单板， 上面163的不行。
