### ISSUE TITLE
考虑添加 debian 每周构建安装镜像

### ISSUE THREAD

**Issue by hosiet** [ustclug/mirrorrequest#87]
如题，每周镜像

* 可以每隔一周或两周同步一次，减轻镜像压力
* 可以选择性同步某些镜像（例如仅 amd64）

具体地址：

* http://cdimage.debian.org/mirror/cdimage/weekly-builds/
* http://cdimage.debian.org/mirror/cdimage/weekly-live-builds/ （低优先级）

具体操作，类似 `rsync cdimage.debian.org::cdimage/weekly-builds/`。但是我们已经有了账户名和密码，所以可以在当前 `debian-cd` 镜像配置的基础上使用用户名和密码，在路径前加上 `private/` 进行尝试。

添加后可以考虑在 mirrors 主页 ISO 下载脚本中挂上每周构建的安装镜像下载，方便 `Debian testing` 用户。

* [X] 添加镜像
* [x] 添加 non-free 镜像
* [x] 更新主页 iso 安装脚本

**Comment by hosiet** [comment]
mirrors.ustc.edu.cn/debian-cdimage

**Comment by zhsj** [comment]
把openstack镜像也加上吧。

**Comment by hosiet** [comment]
完成。
