### ISSUE TITLE
Pypi仓库丢包

### ISSUE THREAD

**Issue by abcfy2** [ustclug/mirrorrequest#88]
比如安装`requests`这个包:

```
pip install -U requests --index-url=https://pypi.mirrors.ustc.edu.cn/simple
Collecting requests
  Could not find a version that satisfies the requirement requests (from versions: )
No matching distribution found for requests
```

但是从官方镜像站或清华大学的镜像站安装就是OK的:
```
 pip install -U requests --index-url=https://pypi.tuna.tsinghua.edu.cn/simple  
Collecting requests
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ed/9e/60cc074968c095f728f0d8d28370e8d396fa60afb7582735563cccf223dd/requests-2.12.4-py2.py3-none-any.whl (576kB)
Installing collected packages: requests
Successfully installed requests-2.12.4
```

**Comment by gaoyifan** [comment]
从日志来看，的确已经同步成功了。是不是配置有问题呢？
https://github.com/ustclug/pypi-mirror/blob/master/.docker/rootfs/etc/bandersnatch.conf
https://github.com/ustclug/pypi-mirror/blob/master/.docker/run

@zhsj  @knight42  表示不太懂python，求帮助~

**Comment by abcfy2** [comment]
和清华大学的pypi镜像站相比，的确少了很多包: https://pypi.tuna.tsinghua.edu.cn/simple/
对比下清华大学的同步脚本看看，是不是少同步了什么？

**Comment by knight42** [comment]
问题原因不明... 看日志也没发现什么错误. 目前已经强制 bandersnatch 进行一次全量同步, 需要花点时间.

**Comment by knight42** [comment]
问题原因可能是 bandersnatch 的配置里设置了 `stop-on-error = true`, 而同步的时候超时其实挺常见的, 所以同步一直没完成.

**Comment by zhsj** [comment]
@knight42 和这个参数基本上没关系，同步没完成会在pypi目录下有一个todo文件，而上次我检查的时候这个文件并没有，说明同步成功结束了。。。

**Comment by knight42** [comment]
@zhsj 那就不太清楚了. 但是很多文件没有下载也确实是事实.

@abcfy2 现在全量同步已经完成了, 你可以试试看有没有问题.

**Comment by zhsj** [comment]
@knight42 是的，所以并没有找到root cause

**Comment by abcfy2** [comment]
这次OK了
