### ISSUE TITLE
[New] Infinality-bundle相关仓库

### ISSUE THREAD

**Issue by inkn** [ustclug/mirrorrequest#9]
Infinality-bundle 是一套ARCH LINUX专用的加强字体渲染的软件包. 与ARCH有着极高的相溶性. 

主要包含:
freetype2-infinality-ultimate
        -- freetype2 built with Infinality and additional patches.

fontconfig-infinality-ultimate
        -- fontconfig optimized for use with freetype2-infinality-ultimate,including separate configuration    presets for free (default), MS and custom font collections.

cairo-infinality-ultimate
        -- cairo built with Ubuntu and additional patches.

还有一些FONTS
由于源速度慢，而且国内也很少有他的镜像源，故提交申请。
源如下：

[infinality-bundle]
Server = http://bohoomil.com/repo/$arch

[infinality-bundle-multilib]
Server = http://bohoomil.com/repo/multilib/$arch

[infinality-bundle-fonts]
Server = http://bohoomil.com/repo/fonts

**Comment by knight42** [comment]
您好，该源已添加，可以通过如下地址访问。
```
[infinality-bundle]
Server = http://mirrors.ustc.edu.cn/infinality-bundle/$arch

[infinality-bundle-multilib]
Server = http://mirrors.ustc.edu.cn/infinality-bundle/multilib/$arch

[infinality-bundle-fonts]
Server = http://mirrors.ustc.edu.cn/infinality-bundle/fonts
```

如有其他问题，欢迎联系我们。祝好 :-)

**Comment by Firef0x** [comment]
@knight42 十分感谢 USTC LUG 的贡献 :rose: ，冒昧请求下 [Repo CK 镜像](https://github.com/ustclug/mirrorrequest/issues/11)也可以有！！ :heart_eyes:
