### ISSUE TITLE
Any interest about the mirror or build server for Lineage OS

### ISSUE THREAD

**Issue by Bambooin** [ustclug/mirrorrequest#90]
Lineage OS is the fork of the dead CyanogenMod project, an open source third ROM of many Android smart phones. Now she needs some [**help**](http://lineageos.org/Infrastructure-Status-and-Official-Builds/).

- If the work of providing the build server is difficult or can't approved, at least setting mirror of it.
- The need of disk and network resource is low comparing with other Linux distribution, except CPU resource.
- The old CM ROM is [very popular](https://www.reddit.com/r/LineageOS/) among people.
- As our mirror server upgrades hardware to an higher level and the usage of CPU is low[(about 5%)](https://servers.ustclug.org/2016/12/mirrors-new-server-online/#div-comment-22769).
- The other mirror sites can help each other to speed the download over the world.
- It will be a good trip and our mirror site will be marked as bookmark by more geeks. 

PS: I can provide some help if someone needs.

**Comment by zhsj** [comment]
@Bambooin We can't provide build server, but it will be fine to mirror if it's easy to sync with upstream. On the lineageos website, it says currentl there is no official build yet, we will take a look when they start offering contents.

**Comment by gaoyifan** [comment]
@Bambooin 
For stable consideration, we do not prefer to provide mirrors as a build server.  But we have other servers with available  CPU resource.

[This news](http://lineageos.org/Infrastructure-Status-and-Official-Builds/) have mentioned that the build server need to finish building procedure within an hour. But I haven't find any document/wiki about how to build, while [GitHub Organization](https://github.com/lineageos) have dozens of projects.

Can you provide a test method and procedure, so that we can check whether our server meet the standard.

**Comment by Bambooin** [comment]
@zhsj I think it will easy as the original ROM is mirrored.
@gaoyifan I will write an email to infra@lineageos.org(cc you), explain our question, and maybe they can resolve our worry.

Thank all you!

**Comment by zifnab06** [comment]
Hey guys, 

We may be interested in mirror space after our first builds go out - I'll need to check stats once they're live to see what our chinese userbase looks like and what our current mirrors load looks like. Mirroring is just rsync, however, our main mirror has limited bandwidth and I need to verify that we a) have bandwidth, and b) have a need for a chinese mirror. There's already 2 1gbit mirrors surrounding china (in russia and singapore). 

(Note: I'm the infra guy for LineageOS right now). 

Thanks!

**Comment by zhsj** [comment]
@zifnab06 thanks for contact, a mirror inside China is much appreciated since the large amount of previous CM users in China. We can sync from Singapore or other mirrors if they provide rsync too. And if we setup the mirror, we can also provide rsync service if other mirrors needed.

**Comment by hosiet** [comment]
ping @zifnab06 now LineageOS project is operating normally. What do you think now?

We could see a large userbase of Chinese users of LineageOS on [stats](https://stats.lineageos.org) page (This page is now 500 Server Internal Error BTW). As a user myself, I couldn't say current mirror is "fast".

**Comment by zifnab06** [comment]
Thanks for the reminder. Stats check out, there are more users in china than I thought. 

If this is still available - I'll need an IP to whitelist, and an https/rsync endpoint to point mirrorbits at. Once you're whitelisted you can rsync from rsync://mirror-sync.lineageos.org

Thanks!

**Comment by zhsj** [comment]
@zifnab06 we have three ipv4 addresses and one ipv6.

202.38.95.110
202.141.160.110
202.141.176.110
2001:da8:d800:95::110

**Comment by Bambooin** [comment]
The amount of users in China is second under India according the [LineageOS Statistics](https://stats.lineageos.org/).

Actually the download mirror is one of these in mainland of China.

- https://mirrors.dotsrc.org
- https://lnos4.mirrorhub.io
- https://lineageos.mirror.karneval.cz

And I have to try all of them to select the most fast one every time.

Thanks all of you for doing the wonderful contribution to a libre Android ROM.

**Comment by hosiet** [comment]
@zifnab06 IP addresses are provided by zhsj above. HTTP/HTTPS access would be available as https://mirrors.ustc.edu.cn/lineageos/ . Rsync **clients** should access rsync://rsync.mirrors.ustc.edu.cn/lineageos/ then.

**Comment by IronBlood** [comment]
@hosiet @zhsj Hey guys, https://mirrors.ustc.edu.cn/lineageos/ returns `404` to me. Have you guys start rsync yet?

**Comment by zhsj** [comment]
@IronBlood Not started. We haven't  got response from Lineage OS team.

@zifnab06 Can you whitelist our server? Currently we get:
```
zsj@mirrors2:~$ rsync --address=202.141.176.110 rsync://mirror-sync.lineageos.org/mirror/
@ERROR: access denied to mirror from mirrors.ustc.edu.cn (202.141.176.110)
```

**Comment by IronBlood** [comment]
@zhsj currently I'm rsyning from `rsync://mirror.math.princeton.edu/pub/lineageos/` at 1MB/s, perhaps you are interested to have a try before regularly rsync.

**Comment by zifnab06** [comment]
I really need to find a better way to manage github notifications, sorry about that. 

Your IPs have been white listed. Please let me know once you've completed the initial sync. 

Also - just a note - week keep roughly the last 3-4 builds per device. You'll want to have `--delete` in your rsync crontab. 

Thanks! I'll keep an eye on this and get it live once you confirm the rsync works.

**Comment by zhsj** [comment]
@zifnab06 We have started syncing, current speed is about 3-4M/s. How much space does lineageos take, so that we can estimate the initial sync time.

**Comment by hosiet** [comment]
@zhsj "500Gb" according to http://lineageos.org/mirroring/. Gbit or GByte?

**Comment by IronBlood** [comment]
@zifnab06 Can you whitelist my IP? I wrote an email several days ago to infra, applying to be one of the mirrors in China. I've already rsynced from one of your mirrors.

@hosiet @zhsj currently it's 351.24GB

**Comment by hosiet** [comment]
@zifnab06 The initial synchronization has finished. Later sync is scheduled once an hour.

* http://mirrors.ustc.edu.cn/lineageos/
* https://mirrors.ustc.edu.cn/lineageos/
* ftp://mirrors.ustc.edu.cn/lineageos/

Rsync support might be added later.

**Comment by gaoyifan** [comment]
@hosiet 需要这么频繁么？

**Comment by hosiet** [comment]
@gaoyifan 官方推荐15分钟一次……

**Comment by zifnab06** [comment]
@hosiet Your mirror has been added. I've limited (both) of the CN mirrors to CN only, as they're unavailable outside of china to certain IPs (which I"m assuming is the GFW). 

Please let me know if traffic volumes are too high and I'll lower the score. If there are any problems, infra <at> lineageos.org and/or irc://irc.freenode.net/#lineageos-infra are the easiest ways to get in contact with someone.

**Comment by hosiet** [comment]
Great. thanks!

**Comment by shankerwangmiao** [comment]
Hi, all. I found neither USTC nor TUNA get shown in the mirror list (e.g. https://mirrorbits.lineageos.org/full/bardock/20210803/lineage-18.1-20210803-nightly-bardock-signed.zip?mirrorlist) , when requested from Tsinghua. Do you have similar issues? I've reported it to @zifnab06 and see if there is anything to do to help diagnose this problem.

**Comment by taoky** [comment]
> Hi, all. I found neither USTC nor TUNA get shown in the mirror list (e.g. https://mirrorbits.lineageos.org/full/bardock/20210803/lineage-18.1-20210803-nightly-bardock-signed.zip?mirrorlist) , when requested from Tsinghua. Do you have similar issues? 

Yes. I tested this link in USTC campus network and also found no CN mirrors shown in the list.
