### ISSUE TITLE
请求增加Linuxbrew镜像

### ISSUE THREAD

**Issue by DelightRun** [ustclug/mirrorrequest#98]
Linuxbrew是Homebrew移植到Linux下的一个版本，其功能和运行原理和Homebrew一致。
唯一的区别就在于GitHub上的Repo地址不同，Linuxbrew为https://github.com/Linuxbrew/brew。
因此希望增加Linuxbrew的镜像。

Linuxbrew官方网站：http://linuxbrew.sh
GitHub地址：https://github.com/Linuxbrew

**Comment by athrunsun** [comment]
+1
linuxbrew也包含有linux独有的formula，比如[jdk8](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/jdk.rb)和[jdk7](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/jdk7.rb).

**Comment by wzpan** [comment]
+1
请求增加

**Comment by OuSatoru** [comment]
also linuxbrew bottles in https://bintray.com/linuxbrew

**Comment by zhangpy** [comment]
linuxbrew bintray: https://linuxbrew.bintray.com

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/linuxbrew-core.git/ 同步完成。

`linuxbrew-bottles` 也正在初次同步中。

**Comment by taoky** [comment]
> `linuxbrew-bottles` 也正在初次同步中。

`linuxbrew-bottles` 初次同步完成：https://mirrors.ustc.edu.cn/linuxbrew-bottles/

相关配置仍需要在 https://github.com/ustclug/mirrorhelp 添加。

**Comment by taoky** [comment]
> 相关配置仍需要在 https://github.com/ustclug/mirrorhelp 添加。

Done. (https://github.com/ustclug/mirrorhelp/commit/c5a1ffe3cae4591109c36012e96b718f1ff980d5)

**Comment by athrunsun** [comment]
@taoky 非常感谢！
